/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nmpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s3[11] = 
  {4, 4, 0, 1, 2, 3, 4, 0,
  1, 2, 3};
static const casadi_int casadi_s4[18] = 
  {17, 1, 0, 14, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13};
static const casadi_int casadi_s5[3] = {13, 1, 1};
static const casadi_int casadi_s6[3] = {4, 1, 1};
static const casadi_int casadi_s7[3] = {0, 1, 1};
static const casadi_int casadi_s8[3] = {28, 1, 1};
static const casadi_int casadi_s9[3] = {1, 1, 1};
static const casadi_int casadi_s10[3] = {17, 1, 1};

static const casadi_real casadi_zeros[28] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* quadrotor_nmpc_cost_ext_cost_0_fun_jac:(i0[13],i1[4],i2[0],i3[28])->(o0,o1[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+5, *w04=w+36, *w05=w+39, *w06=w+42, w07, *w08=w+46, *w09=w+49, *w10=w+52, w11;
  casadi_real *w12=w+56, w13, w14, w15, *w16=w+63, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, w26, *w27=w+77, *w28=w+81, *w29=w+85, *w30=w+88, *w31=w+91, *w33=w+97, *w34=w+100, w35, *w36=w+104;
  casadi_real *w38=w+112, *w39=w+116, *w41=w+119, *w42=w+133;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr08, *wr09, *wr32, *wr37;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = @3[7:10] */
  wr05 = wr03+7;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  casadi_mtimes(w04, casadi_s0, wr05, casadi_s1, w06, casadi_s0, w, 0);
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #11: @8 = @3[22:25] */
  wr08 = wr03+22;
  /* #12: @2 = (@2-@8) */
  for (i=0, rr=w02, cs=wr08; i<3; ++i) (*rr++) -= (*cs++);
  /* #13: @8 = @2' */
  casadi_copy(w02, 3, w08);
  /* #14: @9 = @3[25:28] */
  wr09 = wr03+25;
  /* #15: @10 = mac(@8,@9,@1) */
  casadi_copy(w01, 3, w10);
  casadi_mtimes(w08, casadi_s0, wr09, casadi_s1, w10, casadi_s0, w, 0);
  /* #16: @11 = mac(@10,@2,@0) */
  casadi_copy((&w00), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w10+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #17: @7 = (@7+@11) */
  w07 += w11;
  /* #18: @12 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w12);
  /* #19: @11 = @12[0] */
  for (rr=(&w11), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #20: @13 = @12[1] */
  for (rr=(&w13), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #21: @13 = (-@13) */
  w13 = (- w13 );
  /* #22: @14 = @12[2] */
  for (rr=(&w14), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #23: @14 = (-@14) */
  w14 = (- w14 );
  /* #24: @15 = @12[3] */
  for (rr=(&w15), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #25: @15 = (-@15) */
  w15 = (- w15 );
  /* #26: @16 = vertcat(@11, @13, @14, @15) */
  rr=w16;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #27: @11 = ||@12||_F */
  w11 = casadi_norm_2(4, w12);
  /* #28: @16 = (@16/@11) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w11;
  /* #29: @13 = @16[0] */
  for (rr=(&w13), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #30: @14 = @3[3] */
  w14 = wr03[3];
  /* #31: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #32: @17 = @16[1] */
  for (rr=(&w17), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #33: @18 = @3[4] */
  w18 = wr03[4];
  /* #34: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #35: @15 = (@15-@19) */
  w15 -= w19;
  /* #36: @19 = @16[2] */
  for (rr=(&w19), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #37: @20 = @3[5] */
  w20 = wr03[5];
  /* #38: @21 = (@19*@20) */
  w21  = (w19*w20);
  /* #39: @15 = (@15-@21) */
  w15 -= w21;
  /* #40: @21 = @16[3] */
  for (rr=(&w21), cs=w16+3; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #41: @22 = @3[6] */
  w22 = wr03[6];
  /* #42: @23 = (@21*@22) */
  w23  = (w21*w22);
  /* #43: @15 = (@15-@23) */
  w15 -= w23;
  /* #44: @23 = (@15<@0) */
  w23  = (w15<w00);
  /* #45: @24 = (@13*@18) */
  w24  = (w13*w18);
  /* #46: @25 = (@17*@14) */
  w25  = (w17*w14);
  /* #47: @24 = (@24+@25) */
  w24 += w25;
  /* #48: @25 = (@19*@22) */
  w25  = (w19*w22);
  /* #49: @24 = (@24+@25) */
  w24 += w25;
  /* #50: @25 = (@21*@20) */
  w25  = (w21*w20);
  /* #51: @24 = (@24-@25) */
  w24 -= w25;
  /* #52: @25 = (@13*@20) */
  w25  = (w13*w20);
  /* #53: @26 = (@17*@22) */
  w26  = (w17*w22);
  /* #54: @25 = (@25-@26) */
  w25 -= w26;
  /* #55: @26 = (@19*@14) */
  w26  = (w19*w14);
  /* #56: @25 = (@25+@26) */
  w25 += w26;
  /* #57: @26 = (@21*@18) */
  w26  = (w21*w18);
  /* #58: @25 = (@25+@26) */
  w25 += w26;
  /* #59: @13 = (@13*@22) */
  w13 *= w22;
  /* #60: @17 = (@17*@20) */
  w17 *= w20;
  /* #61: @13 = (@13+@17) */
  w13 += w17;
  /* #62: @19 = (@19*@18) */
  w19 *= w18;
  /* #63: @13 = (@13-@19) */
  w13 -= w19;
  /* #64: @21 = (@21*@14) */
  w21 *= w14;
  /* #65: @13 = (@13+@21) */
  w13 += w21;
  /* #66: @27 = vertcat(@15, @24, @25, @13) */
  rr=w27;
  *rr++ = w15;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w13;
  /* #67: @28 = (-@27) */
  for (i=0, rr=w28, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #68: @28 = (@23?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #69: @15 = (!@23) */
  w15 = (! w23 );
  /* #70: @27 = (@15?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #71: @28 = (@28+@27) */
  for (i=0, rr=w28, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #72: @2 = @28[1:4] */
  for (rr=w02, cs=w28+1; cs!=w28+4; cs+=1) *rr++ = *cs;
  /* #73: @29 = (2.*@2) */
  for (i=0, rr=w29, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #74: @24 = 1e-12 */
  w24 = 9.9999999999999998e-13;
  /* #75: @25 = dot(@2, @2) */
  w25 = casadi_dot(3, w02, w02);
  /* #76: @24 = (@24+@25) */
  w24 += w25;
  /* #77: @25 = sqrt(@24) */
  w25 = sqrt( w24 );
  /* #78: @13 = @28[0] */
  for (rr=(&w13), cs=w28+0; cs!=w28+1; cs+=1) *rr++ = *cs;
  /* #79: @21 = atan2(@25,@13) */
  w21  = atan2(w25,w13);
  /* #80: @30 = (@29*@21) */
  for (i=0, rr=w30, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #81: @30 = (@30/@25) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w25;
  /* #82: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #83: @32 = @3[10:13] */
  wr32 = wr03+10;
  /* #84: @33 = mac(@31,@32,@1) */
  casadi_copy(w01, 3, w33);
  casadi_mtimes(w31, casadi_s0, wr32, casadi_s1, w33, casadi_s0, w, 0);
  /* #85: @19 = mac(@33,@30,@0) */
  casadi_copy((&w00), 1, (&w19));
  for (i=0, rr=(&w19); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #86: @7 = (@7+@19) */
  w07 += w19;
  /* #87: @28 = zeros(1x4) */
  casadi_clear(w28, 4);
  /* #88: @19 = input[1][0] */
  w19 = arg[1] ? arg[1][0] : 0;
  /* #89: @17 = 9.81 */
  w17 = 9.8100000000000005e+00;
  /* #90: @26 = @3[17] */
  w26 = wr03[17];
  /* #91: @17 = (@17*@26) */
  w17 *= w26;
  /* #92: @19 = (@19-@17) */
  w19 -= w17;
  /* #93: @34 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w34);
  /* #94: @17 = @34[0] */
  for (rr=(&w17), cs=w34+0; cs!=w34+1; cs+=1) *rr++ = *cs;
  /* #95: @26 = @34[1] */
  for (rr=(&w26), cs=w34+1; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #96: @35 = @34[2] */
  for (rr=(&w35), cs=w34+2; cs!=w34+3; cs+=1) *rr++ = *cs;
  /* #97: @27 = vertcat(@19, @17, @26, @35) */
  rr=w27;
  *rr++ = w19;
  *rr++ = w17;
  *rr++ = w26;
  *rr++ = w35;
  /* #98: @36 = @27' */
  casadi_copy(w27, 4, w36);
  /* #99: @37 = @3[13:17] */
  wr37 = wr03+13;
  /* #100: @38 = mac(@36,@37,@28) */
  casadi_copy(w28, 4, w38);
  casadi_mtimes(w36, casadi_s2, wr37, casadi_s3, w38, casadi_s2, w, 0);
  /* #101: @0 = mac(@38,@27,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w27+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #102: @7 = (@7+@0) */
  w07 += w00;
  /* #103: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  /* #104: @38 = @38' */
  /* #105: @27 = @37' */
  casadi_trans(wr37,casadi_s3, w27, casadi_s3, iw);
  /* #106: @28 = mac(@36,@27,@28) */
  casadi_mtimes(w36, casadi_s2, w27, casadi_s3, w28, casadi_s2, w, 0);
  /* #107: @28 = @28' */
  /* #108: @38 = (@38+@28) */
  for (i=0, rr=w38, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #109: {@7, @0, @19, @17} = vertsplit(@38) */
  w07 = w38[0];
  w00 = w38[1];
  w19 = w38[2];
  w17 = w38[3];
  /* #110: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #111: (@34[2] += @17) */
  for (rr=w34+2, cs=(&w17); rr!=w34+3; rr+=1) *rr += *cs++;
  /* #112: (@34[1] += @19) */
  for (rr=w34+1, cs=(&w19); rr!=w34+2; rr+=1) *rr += *cs++;
  /* #113: (@34[0] += @0) */
  for (rr=w34+0, cs=(&w00); rr!=w34+1; rr+=1) *rr += *cs++;
  /* #114: @6 = @6' */
  /* #115: @39 = @5' */
  casadi_trans(wr05,casadi_s1, w39, casadi_s1, iw);
  /* #116: @5 = mac(@4,@39,@1) */
  casadi_copy(w01, 3, w05);
  casadi_mtimes(w04, casadi_s0, w39, casadi_s1, w05, casadi_s0, w, 0);
  /* #117: @5 = @5' */
  /* #118: @6 = (@6+@5) */
  for (i=0, rr=w06, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #119: @10 = @10' */
  /* #120: @5 = @9' */
  casadi_trans(wr09,casadi_s1, w05, casadi_s1, iw);
  /* #121: @9 = mac(@8,@5,@1) */
  casadi_copy(w01, 3, w09);
  casadi_mtimes(w08, casadi_s0, w05, casadi_s1, w09, casadi_s0, w, 0);
  /* #122: @9 = @9' */
  /* #123: @10 = (@10+@9) */
  for (i=0, rr=w10, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #124: @16 = (@16/@11) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w11;
  /* #125: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<4; ++i) *rr++ = (- *cs++ );
  /* #126: @38 = zeros(4x1) */
  casadi_clear(w38, 4);
  /* #127: @0 = sq(@13) */
  w00 = casadi_sq( w13 );
  /* #128: @24 = (@24+@0) */
  w24 += w00;
  /* #129: @0 = (@25/@24) */
  w00  = (w25/w24);
  /* #130: @33 = @33' */
  /* #131: @9 = @32' */
  casadi_trans(wr32,casadi_s1, w09, casadi_s1, iw);
  /* #132: @1 = mac(@31,@9,@1) */
  casadi_mtimes(w31, casadi_s0, w09, casadi_s1, w01, casadi_s0, w, 0);
  /* #133: @1 = @1' */
  /* #134: @33 = (@33+@1) */
  for (i=0, rr=w33, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #135: @1 = (@33/@25) */
  for (i=0, rr=w01, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #136: @19 = dot(@29, @1) */
  w19 = casadi_dot(3, w29, w01);
  /* #137: @0 = (@0*@19) */
  w00 *= w19;
  /* #138: @0 = (-@0) */
  w00 = (- w00 );
  /* #139: @28 = @38; (@28[0] += @0) */
  casadi_copy(w38, 4, w28);
  for (rr=w28+0, cs=(&w00); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #140: @30 = (@30/@25) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w25;
  /* #141: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #142: @0 = dot(@30, @33) */
  w00 = casadi_dot(3, w30, w33);
  /* #143: @13 = (@13/@24) */
  w13 /= w24;
  /* #144: @13 = (@13*@19) */
  w13 *= w19;
  /* #145: @0 = (@0+@13) */
  w00 += w13;
  /* #146: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #147: @0 = (@0/@25) */
  w00 /= w25;
  /* #148: @2 = (@0*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #149: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #150: @1 = (@21*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #151: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #152: @2 = (@2+@1) */
  for (i=0, rr=w02, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #153: (@28[1:4] += @2) */
  for (rr=w28+1, cs=w02; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #154: @36 = (@15?@28:0) */
  for (i=0, rr=w36, cs=w28; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #155: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #156: @28 = (@23?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #157: @36 = (@36+@28) */
  for (i=0, rr=w36, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #158: {@23, @15, @21, @0} = vertsplit(@36) */
  w23 = w36[0];
  w15 = w36[1];
  w21 = w36[2];
  w00 = w36[3];
  /* #159: @25 = (@14*@0) */
  w25  = (w14*w00);
  /* #160: (@38[3] += @25) */
  for (rr=w38+3, cs=(&w25); rr!=w38+4; rr+=1) *rr += *cs++;
  /* #161: @25 = (@18*@0) */
  w25  = (w18*w00);
  /* #162: @25 = (-@25) */
  w25 = (- w25 );
  /* #163: (@38[2] += @25) */
  for (rr=w38+2, cs=(&w25); rr!=w38+3; rr+=1) *rr += *cs++;
  /* #164: @25 = (@20*@0) */
  w25  = (w20*w00);
  /* #165: (@38[1] += @25) */
  for (rr=w38+1, cs=(&w25); rr!=w38+2; rr+=1) *rr += *cs++;
  /* #166: @0 = (@22*@0) */
  w00  = (w22*w00);
  /* #167: (@38[0] += @0) */
  for (rr=w38+0, cs=(&w00); rr!=w38+1; rr+=1) *rr += *cs++;
  /* #168: @0 = (@18*@21) */
  w00  = (w18*w21);
  /* #169: (@38[3] += @0) */
  for (rr=w38+3, cs=(&w00); rr!=w38+4; rr+=1) *rr += *cs++;
  /* #170: @0 = (@14*@21) */
  w00  = (w14*w21);
  /* #171: (@38[2] += @0) */
  for (rr=w38+2, cs=(&w00); rr!=w38+3; rr+=1) *rr += *cs++;
  /* #172: @0 = (@22*@21) */
  w00  = (w22*w21);
  /* #173: @0 = (-@0) */
  w00 = (- w00 );
  /* #174: (@38[1] += @0) */
  for (rr=w38+1, cs=(&w00); rr!=w38+2; rr+=1) *rr += *cs++;
  /* #175: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #176: (@38[0] += @21) */
  for (rr=w38+0, cs=(&w21); rr!=w38+1; rr+=1) *rr += *cs++;
  /* #177: @21 = (@20*@15) */
  w21  = (w20*w15);
  /* #178: @21 = (-@21) */
  w21 = (- w21 );
  /* #179: (@38[3] += @21) */
  for (rr=w38+3, cs=(&w21); rr!=w38+4; rr+=1) *rr += *cs++;
  /* #180: @21 = (@22*@15) */
  w21  = (w22*w15);
  /* #181: (@38[2] += @21) */
  for (rr=w38+2, cs=(&w21); rr!=w38+3; rr+=1) *rr += *cs++;
  /* #182: @21 = (@14*@15) */
  w21  = (w14*w15);
  /* #183: (@38[1] += @21) */
  for (rr=w38+1, cs=(&w21); rr!=w38+2; rr+=1) *rr += *cs++;
  /* #184: @15 = (@18*@15) */
  w15  = (w18*w15);
  /* #185: (@38[0] += @15) */
  for (rr=w38+0, cs=(&w15); rr!=w38+1; rr+=1) *rr += *cs++;
  /* #186: @22 = (@22*@23) */
  w22 *= w23;
  /* #187: @22 = (-@22) */
  w22 = (- w22 );
  /* #188: (@38[3] += @22) */
  for (rr=w38+3, cs=(&w22); rr!=w38+4; rr+=1) *rr += *cs++;
  /* #189: @20 = (@20*@23) */
  w20 *= w23;
  /* #190: @20 = (-@20) */
  w20 = (- w20 );
  /* #191: (@38[2] += @20) */
  for (rr=w38+2, cs=(&w20); rr!=w38+3; rr+=1) *rr += *cs++;
  /* #192: @18 = (@18*@23) */
  w18 *= w23;
  /* #193: @18 = (-@18) */
  w18 = (- w18 );
  /* #194: (@38[1] += @18) */
  for (rr=w38+1, cs=(&w18); rr!=w38+2; rr+=1) *rr += *cs++;
  /* #195: @14 = (@14*@23) */
  w14 *= w23;
  /* #196: (@38[0] += @14) */
  for (rr=w38+0, cs=(&w14); rr!=w38+1; rr+=1) *rr += *cs++;
  /* #197: @14 = dot(@16, @38) */
  w14 = casadi_dot(4, w16, w38);
  /* #198: @14 = (@14/@11) */
  w14 /= w11;
  /* #199: @12 = (@14*@12) */
  for (i=0, rr=w12, cs=w12; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #200: @38 = (@38/@11) */
  for (i=0, rr=w38; i<4; ++i) (*rr++) /= w11;
  /* #201: {@11, @14, @23, @18} = vertsplit(@38) */
  w11 = w38[0];
  w14 = w38[1];
  w23 = w38[2];
  w18 = w38[3];
  /* #202: @18 = (-@18) */
  w18 = (- w18 );
  /* #203: (@12[3] += @18) */
  for (rr=w12+3, cs=(&w18); rr!=w12+4; rr+=1) *rr += *cs++;
  /* #204: @23 = (-@23) */
  w23 = (- w23 );
  /* #205: (@12[2] += @23) */
  for (rr=w12+2, cs=(&w23); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #206: @14 = (-@14) */
  w14 = (- w14 );
  /* #207: (@12[1] += @14) */
  for (rr=w12+1, cs=(&w14); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #208: (@12[0] += @11) */
  for (rr=w12+0, cs=(&w11); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #209: @40 = zeros(3x1,0nz) */
  /* #210: @41 = vertcat(@7, @34, @6, @10, @12, @40) */
  rr=w41;
  *rr++ = w07;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #211: @42 = dense(@41) */
  casadi_densify(w41, casadi_s4, w42, 0);
  /* #212: output[1][0] = @42 */
  casadi_copy(w42, 17, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nmpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 150;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 150*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
