/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nmpc_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[3] = {13, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {22, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* quadrotor_nmpc_cost_ext_cost_e_fun:(i0[13],i1[0],i2[0],i3[22])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+5, *w04=w+30, *w06=w+36, w07, *w08=w+40, w09, w10, w11, w12;
  casadi_real *w13=w+48, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  const casadi_real *cs, *ct, *wr03, *wr04, *wr05;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = @3[7:10] */
  wr05 = wr03+7;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  casadi_mtimes(w04, casadi_s0, wr05, casadi_s1, w06, casadi_s0, w, 0);
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @8 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w08);
  /* #11: @9 = @8[0] */
  for (rr=(&w09), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #12: @10 = @8[1] */
  for (rr=(&w10), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #13: @10 = (-@10) */
  w10 = (- w10 );
  /* #14: @11 = @8[2] */
  for (rr=(&w11), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #15: @11 = (-@11) */
  w11 = (- w11 );
  /* #16: @12 = @8[3] */
  for (rr=(&w12), cs=w08+3; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #17: @12 = (-@12) */
  w12 = (- w12 );
  /* #18: @13 = vertcat(@9, @10, @11, @12) */
  rr=w13;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #19: @9 = ||@8||_F */
  w09 = casadi_norm_2(4, w08);
  /* #20: @13 = (@13/@9) */
  for (i=0, rr=w13; i<4; ++i) (*rr++) /= w09;
  /* #21: @9 = @13[0] */
  for (rr=(&w09), cs=w13+0; cs!=w13+1; cs+=1) *rr++ = *cs;
  /* #22: @10 = @3[3] */
  w10 = wr03[3];
  /* #23: @11 = (@9*@10) */
  w11  = (w09*w10);
  /* #24: @12 = @13[1] */
  for (rr=(&w12), cs=w13+1; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #25: @14 = @3[4] */
  w14 = wr03[4];
  /* #26: @15 = (@12*@14) */
  w15  = (w12*w14);
  /* #27: @11 = (@11-@15) */
  w11 -= w15;
  /* #28: @15 = @13[2] */
  for (rr=(&w15), cs=w13+2; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #29: @16 = @3[5] */
  w16 = wr03[5];
  /* #30: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #31: @11 = (@11-@17) */
  w11 -= w17;
  /* #32: @17 = @13[3] */
  for (rr=(&w17), cs=w13+3; cs!=w13+4; cs+=1) *rr++ = *cs;
  /* #33: @18 = @3[6] */
  w18 = wr03[6];
  /* #34: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #35: @11 = (@11-@19) */
  w11 -= w19;
  /* #36: @19 = (@11<@0) */
  w19  = (w11<w00);
  /* #37: @20 = (@9*@14) */
  w20  = (w09*w14);
  /* #38: @21 = (@12*@10) */
  w21  = (w12*w10);
  /* #39: @20 = (@20+@21) */
  w20 += w21;
  /* #40: @21 = (@15*@18) */
  w21  = (w15*w18);
  /* #41: @20 = (@20+@21) */
  w20 += w21;
  /* #42: @21 = (@17*@16) */
  w21  = (w17*w16);
  /* #43: @20 = (@20-@21) */
  w20 -= w21;
  /* #44: @21 = (@9*@16) */
  w21  = (w09*w16);
  /* #45: @22 = (@12*@18) */
  w22  = (w12*w18);
  /* #46: @21 = (@21-@22) */
  w21 -= w22;
  /* #47: @22 = (@15*@10) */
  w22  = (w15*w10);
  /* #48: @21 = (@21+@22) */
  w21 += w22;
  /* #49: @22 = (@17*@14) */
  w22  = (w17*w14);
  /* #50: @21 = (@21+@22) */
  w21 += w22;
  /* #51: @9 = (@9*@18) */
  w09 *= w18;
  /* #52: @12 = (@12*@16) */
  w12 *= w16;
  /* #53: @9 = (@9+@12) */
  w09 += w12;
  /* #54: @15 = (@15*@14) */
  w15 *= w14;
  /* #55: @9 = (@9-@15) */
  w09 -= w15;
  /* #56: @17 = (@17*@10) */
  w17 *= w10;
  /* #57: @9 = (@9+@17) */
  w09 += w17;
  /* #58: @13 = vertcat(@11, @20, @21, @9) */
  rr=w13;
  *rr++ = w11;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w09;
  /* #59: @8 = (-@13) */
  for (i=0, rr=w08, cs=w13; i<4; ++i) *rr++ = (- *cs++ );
  /* #60: @8 = (@19?@8:0) */
  for (i=0, rr=w08, cs=w08; i<4; ++i) (*rr++)  = (w19?cs[i]:0);
  /* #61: @19 = (!@19) */
  w19 = (! w19 );
  /* #62: @13 = (@19?@13:0) */
  for (i=0, rr=w13, cs=w13; i<4; ++i) (*rr++)  = (w19?cs[i]:0);
  /* #63: @8 = (@8+@13) */
  for (i=0, rr=w08, cs=w13; i<4; ++i) (*rr++) += (*cs++);
  /* #64: @6 = @8[1:4] */
  for (rr=w06, cs=w08+1; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #65: @2 = (2.*@6) */
  for (i=0, rr=w02, cs=w06; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #66: @19 = 1e-12 */
  w19 = 9.9999999999999998e-13;
  /* #67: @11 = dot(@6, @6) */
  w11 = casadi_dot(3, w06, w06);
  /* #68: @19 = (@19+@11) */
  w19 += w11;
  /* #69: @19 = sqrt(@19) */
  w19 = sqrt( w19 );
  /* #70: @11 = @8[0] */
  for (rr=(&w11), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #71: @11 = atan2(@19,@11) */
  w11  = atan2(w19,w11);
  /* #72: @2 = (@2*@11) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w11;
  /* #73: @2 = (@2/@19) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) /= w19;
  /* #74: @6 = @2' */
  casadi_copy(w02, 3, w06);
  /* #75: @4 = @3[10:13] */
  wr04 = wr03+10;
  /* #76: @1 = mac(@6,@4,@1) */
  casadi_mtimes(w06, casadi_s0, wr04, casadi_s1, w01, casadi_s0, w, 0);
  /* #77: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #78: @7 = (@7+@0) */
  w07 += w00;
  /* #79: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nmpc_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 61;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 61*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
