/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nmpc_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[17] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* quadrotor_nmpc_cost_ext_cost_e_fun:(i0[13],i1[0],i2[0],i3[17])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, *w02=w+20, w03, w04, w05, *w06=w+26, w07, w08, *w09=w+32, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18;
  const casadi_real *cs, *wr01, *wr02;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w00);
  /* #1: @1 = input[3][0] */
  wr01 = arg[3] ? arg[3] : casadi_zeros;
  /* #2: @2 = @1[:3] */
  wr02 = wr01+0;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w00, cs=wr02; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: @3 = @0[0] */
  for (rr=(&w03), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #5: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #6: @4 = @1[7] */
  w04 = wr01[7];
  /* #7: @3 = (@3*@4) */
  w03 *= w04;
  /* #8: @4 = @0[1] */
  for (rr=(&w04), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #9: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #10: @5 = @1[8] */
  w05 = wr01[8];
  /* #11: @4 = (@4*@5) */
  w04 *= w05;
  /* #12: @3 = (@3+@4) */
  w03 += w04;
  /* #13: @4 = @0[2] */
  for (rr=(&w04), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #14: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #15: @5 = @1[9] */
  w05 = wr01[9];
  /* #16: @4 = (@4*@5) */
  w04 *= w05;
  /* #17: @3 = (@3+@4) */
  w03 += w04;
  /* #18: @6 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w06);
  /* #19: @4 = @6[0] */
  for (rr=(&w04), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #20: @5 = @6[1] */
  for (rr=(&w05), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #21: @5 = (-@5) */
  w05 = (- w05 );
  /* #22: @7 = @6[2] */
  for (rr=(&w07), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #23: @7 = (-@7) */
  w07 = (- w07 );
  /* #24: @8 = @6[3] */
  for (rr=(&w08), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #25: @8 = (-@8) */
  w08 = (- w08 );
  /* #26: @9 = vertcat(@4, @5, @7, @8) */
  rr=w09;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w08;
  /* #27: @4 = ||@6||_F */
  w04 = casadi_norm_2(4, w06);
  /* #28: @9 = (@9/@4) */
  for (i=0, rr=w09; i<4; ++i) (*rr++) /= w04;
  /* #29: @4 = @9[0] */
  for (rr=(&w04), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #30: @5 = @1[3] */
  w05 = wr01[3];
  /* #31: @7 = (@4*@5) */
  w07  = (w04*w05);
  /* #32: @8 = @9[1] */
  for (rr=(&w08), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #33: @10 = @1[4] */
  w10 = wr01[4];
  /* #34: @11 = (@8*@10) */
  w11  = (w08*w10);
  /* #35: @7 = (@7-@11) */
  w07 -= w11;
  /* #36: @11 = @9[2] */
  for (rr=(&w11), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #37: @12 = @1[5] */
  w12 = wr01[5];
  /* #38: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #39: @7 = (@7-@13) */
  w07 -= w13;
  /* #40: @13 = @9[3] */
  for (rr=(&w13), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #41: @14 = @1[6] */
  w14 = wr01[6];
  /* #42: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #43: @7 = (@7-@15) */
  w07 -= w15;
  /* #44: @15 = 0 */
  w15 = 0.;
  /* #45: @15 = (@7<@15) */
  w15  = (w07<w15);
  /* #46: @16 = (@4*@10) */
  w16  = (w04*w10);
  /* #47: @17 = (@8*@5) */
  w17  = (w08*w05);
  /* #48: @16 = (@16+@17) */
  w16 += w17;
  /* #49: @17 = (@11*@14) */
  w17  = (w11*w14);
  /* #50: @16 = (@16+@17) */
  w16 += w17;
  /* #51: @17 = (@13*@12) */
  w17  = (w13*w12);
  /* #52: @16 = (@16-@17) */
  w16 -= w17;
  /* #53: @17 = (@4*@12) */
  w17  = (w04*w12);
  /* #54: @18 = (@8*@14) */
  w18  = (w08*w14);
  /* #55: @17 = (@17-@18) */
  w17 -= w18;
  /* #56: @18 = (@11*@5) */
  w18  = (w11*w05);
  /* #57: @17 = (@17+@18) */
  w17 += w18;
  /* #58: @18 = (@13*@10) */
  w18  = (w13*w10);
  /* #59: @17 = (@17+@18) */
  w17 += w18;
  /* #60: @4 = (@4*@14) */
  w04 *= w14;
  /* #61: @8 = (@8*@12) */
  w08 *= w12;
  /* #62: @4 = (@4+@8) */
  w04 += w08;
  /* #63: @11 = (@11*@10) */
  w11 *= w10;
  /* #64: @4 = (@4-@11) */
  w04 -= w11;
  /* #65: @13 = (@13*@5) */
  w13 *= w05;
  /* #66: @4 = (@4+@13) */
  w04 += w13;
  /* #67: @9 = vertcat(@7, @16, @17, @4) */
  rr=w09;
  *rr++ = w07;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w04;
  /* #68: @6 = (-@9) */
  for (i=0, rr=w06, cs=w09; i<4; ++i) *rr++ = (- *cs++ );
  /* #69: @6 = (@15?@6:0) */
  for (i=0, rr=w06, cs=w06; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #70: @15 = (!@15) */
  w15 = (! w15 );
  /* #71: @9 = (@15?@9:0) */
  for (i=0, rr=w09, cs=w09; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #72: @6 = (@6+@9) */
  for (i=0, rr=w06, cs=w09; i<4; ++i) (*rr++) += (*cs++);
  /* #73: @0 = @6[1:4] */
  for (rr=w00, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #74: @2 = (2.*@0) */
  for (i=0, rr=w02, cs=w00; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #75: @15 = ||@0||_F */
  w15 = casadi_norm_2(3, w00);
  /* #76: @7 = @6[0] */
  for (rr=(&w07), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #77: @7 = atan2(@15,@7) */
  w07  = atan2(w15,w07);
  /* #78: @2 = (@2*@7) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w07;
  /* #79: @7 = 1e-09 */
  w07 = 1.0000000000000001e-09;
  /* #80: @7 = (@7+@15) */
  w07 += w15;
  /* #81: @2 = (@2/@7) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) /= w07;
  /* #82: @7 = @2[0] */
  for (rr=(&w07), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #83: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #84: @15 = @1[10] */
  w15 = wr01[10];
  /* #85: @7 = (@7*@15) */
  w07 *= w15;
  /* #86: @15 = @2[1] */
  for (rr=(&w15), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #87: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #88: @16 = @1[11] */
  w16 = wr01[11];
  /* #89: @15 = (@15*@16) */
  w15 *= w16;
  /* #90: @7 = (@7+@15) */
  w07 += w15;
  /* #91: @15 = @2[2] */
  for (rr=(&w15), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #92: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #93: @16 = @1[12] */
  w16 = wr01[12];
  /* #94: @15 = (@15*@16) */
  w15 *= w16;
  /* #95: @7 = (@7+@15) */
  w07 += w15;
  /* #96: @3 = (@3+@7) */
  w03 += w07;
  /* #97: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nmpc_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 45;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 45*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
