/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

static const casadi_int casadi_s0[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[14] = 
  {13, 1, 0, 10, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[10] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  14, 18};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s8[38] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 10, 14, 18, 22, 22, 22, 22,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 6, 7, 8, 9, 6, 7,
  8, 9, 6, 7, 8, 9};
static const casadi_int casadi_s9[3] = {13, 1, 1};
static const casadi_int casadi_s10[3] = {0, 1, 1};
static const casadi_int casadi_s11[3] = {23, 1, 1};
static const casadi_int casadi_s12[3] = {1, 1, 1};
static const casadi_int casadi_s13[3] = {0, 0, 1};
static const casadi_int casadi_s14[3] = {0, 13, 1};

static const casadi_real casadi_zeros[23] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[0],i2[0],i3[23])->(o0,o1[13],o2[13x13,22nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+5, *w04=w+31, *w05=w+34, *w06=w+37, w07, *w08=w+41, *w09=w+44, *w10=w+47, w11;
  casadi_real *w12=w+51, w13, w14, w15, *w16=w+58, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, w26, *w27=w+72, *w28=w+76, *w29=w+80, *w30=w+83, *w31=w+86, *w33=w+92, *w34=w+95, *w35=w+98, *w36=w+101;
  casadi_real *w37=w+105, *w38=w+108, *w39=w+111, w40, w41, w42, w43, w44, *w45=w+120, *w47=w+124, *w48=w+134, *w49=w+147;
  casadi_real *w51=w+169, w52, w53, w54, w55, w56, w57, *w58=w+179, *w59=w+183, *w60=w+186, *w61=w+190, w62;
  casadi_real w63, w64, w65, *w66=w+204;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr08, *wr09, *wr32;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = @2' */
  casadi_copy(w02, 3, w04);
  /* #7: @5 = @3[7:10] */
  wr05 = wr03+7;
  /* #8: @6 = mac(@4,@5,@1) */
  casadi_copy(w01, 3, w06);
  casadi_mtimes(w04, casadi_s0, wr05, casadi_s1, w06, casadi_s0, w, 0);
  /* #9: @7 = mac(@6,@2,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #10: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #11: @8 = @3[17:20] */
  wr08 = wr03+17;
  /* #12: @2 = (@2-@8) */
  for (i=0, rr=w02, cs=wr08; i<3; ++i) (*rr++) -= (*cs++);
  /* #13: @8 = @2' */
  casadi_copy(w02, 3, w08);
  /* #14: @9 = @3[20:23] */
  wr09 = wr03+20;
  /* #15: @10 = mac(@8,@9,@1) */
  casadi_copy(w01, 3, w10);
  casadi_mtimes(w08, casadi_s0, wr09, casadi_s1, w10, casadi_s0, w, 0);
  /* #16: @11 = mac(@10,@2,@0) */
  casadi_copy((&w00), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w10+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #17: @7 = (@7+@11) */
  w07 += w11;
  /* #18: @12 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w12);
  /* #19: @11 = @12[0] */
  for (rr=(&w11), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #20: @13 = @12[1] */
  for (rr=(&w13), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #21: @13 = (-@13) */
  w13 = (- w13 );
  /* #22: @14 = @12[2] */
  for (rr=(&w14), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #23: @14 = (-@14) */
  w14 = (- w14 );
  /* #24: @15 = @12[3] */
  for (rr=(&w15), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #25: @15 = (-@15) */
  w15 = (- w15 );
  /* #26: @16 = vertcat(@11, @13, @14, @15) */
  rr=w16;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #27: @11 = ||@12||_F */
  w11 = casadi_norm_2(4, w12);
  /* #28: @16 = (@16/@11) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w11;
  /* #29: @13 = @16[0] */
  for (rr=(&w13), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #30: @14 = @3[3] */
  w14 = wr03[3];
  /* #31: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #32: @17 = @16[1] */
  for (rr=(&w17), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #33: @18 = @3[4] */
  w18 = wr03[4];
  /* #34: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #35: @15 = (@15-@19) */
  w15 -= w19;
  /* #36: @19 = @16[2] */
  for (rr=(&w19), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #37: @20 = @3[5] */
  w20 = wr03[5];
  /* #38: @21 = (@19*@20) */
  w21  = (w19*w20);
  /* #39: @15 = (@15-@21) */
  w15 -= w21;
  /* #40: @21 = @16[3] */
  for (rr=(&w21), cs=w16+3; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #41: @22 = @3[6] */
  w22 = wr03[6];
  /* #42: @23 = (@21*@22) */
  w23  = (w21*w22);
  /* #43: @15 = (@15-@23) */
  w15 -= w23;
  /* #44: @23 = (@15<@0) */
  w23  = (w15<w00);
  /* #45: @24 = (@13*@18) */
  w24  = (w13*w18);
  /* #46: @25 = (@17*@14) */
  w25  = (w17*w14);
  /* #47: @24 = (@24+@25) */
  w24 += w25;
  /* #48: @25 = (@19*@22) */
  w25  = (w19*w22);
  /* #49: @24 = (@24+@25) */
  w24 += w25;
  /* #50: @25 = (@21*@20) */
  w25  = (w21*w20);
  /* #51: @24 = (@24-@25) */
  w24 -= w25;
  /* #52: @25 = (@13*@20) */
  w25  = (w13*w20);
  /* #53: @26 = (@17*@22) */
  w26  = (w17*w22);
  /* #54: @25 = (@25-@26) */
  w25 -= w26;
  /* #55: @26 = (@19*@14) */
  w26  = (w19*w14);
  /* #56: @25 = (@25+@26) */
  w25 += w26;
  /* #57: @26 = (@21*@18) */
  w26  = (w21*w18);
  /* #58: @25 = (@25+@26) */
  w25 += w26;
  /* #59: @13 = (@13*@22) */
  w13 *= w22;
  /* #60: @17 = (@17*@20) */
  w17 *= w20;
  /* #61: @13 = (@13+@17) */
  w13 += w17;
  /* #62: @19 = (@19*@18) */
  w19 *= w18;
  /* #63: @13 = (@13-@19) */
  w13 -= w19;
  /* #64: @21 = (@21*@14) */
  w21 *= w14;
  /* #65: @13 = (@13+@21) */
  w13 += w21;
  /* #66: @27 = vertcat(@15, @24, @25, @13) */
  rr=w27;
  *rr++ = w15;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w13;
  /* #67: @28 = (-@27) */
  for (i=0, rr=w28, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #68: @28 = (@23?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #69: @15 = (!@23) */
  w15 = (! w23 );
  /* #70: @27 = (@15?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #71: @28 = (@28+@27) */
  for (i=0, rr=w28, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #72: @2 = @28[1:4] */
  for (rr=w02, cs=w28+1; cs!=w28+4; cs+=1) *rr++ = *cs;
  /* #73: @29 = (2.*@2) */
  for (i=0, rr=w29, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #74: @24 = 1e-12 */
  w24 = 9.9999999999999998e-13;
  /* #75: @25 = dot(@2, @2) */
  w25 = casadi_dot(3, w02, w02);
  /* #76: @24 = (@24+@25) */
  w24 += w25;
  /* #77: @25 = sqrt(@24) */
  w25 = sqrt( w24 );
  /* #78: @13 = @28[0] */
  for (rr=(&w13), cs=w28+0; cs!=w28+1; cs+=1) *rr++ = *cs;
  /* #79: @21 = atan2(@25,@13) */
  w21  = atan2(w25,w13);
  /* #80: @30 = (@29*@21) */
  for (i=0, rr=w30, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #81: @30 = (@30/@25) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w25;
  /* #82: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #83: @32 = @3[10:13] */
  wr32 = wr03+10;
  /* #84: @33 = mac(@31,@32,@1) */
  casadi_copy(w01, 3, w33);
  casadi_mtimes(w31, casadi_s0, wr32, casadi_s1, w33, casadi_s0, w, 0);
  /* #85: @0 = mac(@33,@30,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #86: @7 = (@7+@0) */
  w07 += w00;
  /* #87: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  /* #88: @6 = @6' */
  /* #89: @34 = @5' */
  casadi_trans(wr05,casadi_s1, w34, casadi_s1, iw);
  /* #90: @35 = mac(@4,@34,@1) */
  casadi_copy(w01, 3, w35);
  casadi_mtimes(w04, casadi_s0, w34, casadi_s1, w35, casadi_s0, w, 0);
  /* #91: @35 = @35' */
  /* #92: @6 = (@6+@35) */
  for (i=0, rr=w06, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #93: @10 = @10' */
  /* #94: @35 = @9' */
  casadi_trans(wr09,casadi_s1, w35, casadi_s1, iw);
  /* #95: @4 = mac(@8,@35,@1) */
  casadi_copy(w01, 3, w04);
  casadi_mtimes(w08, casadi_s0, w35, casadi_s1, w04, casadi_s0, w, 0);
  /* #96: @4 = @4' */
  /* #97: @10 = (@10+@4) */
  for (i=0, rr=w10, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #98: @16 = (@16/@11) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w11;
  /* #99: @28 = (-@16) */
  for (i=0, rr=w28, cs=w16; i<4; ++i) *rr++ = (- *cs++ );
  /* #100: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #101: @7 = sq(@13) */
  w07 = casadi_sq( w13 );
  /* #102: @24 = (@24+@7) */
  w24 += w07;
  /* #103: @7 = (@25/@24) */
  w07  = (w25/w24);
  /* #104: @33 = @33' */
  /* #105: @4 = @32' */
  casadi_trans(wr32,casadi_s1, w04, casadi_s1, iw);
  /* #106: @8 = mac(@31,@4,@1) */
  casadi_copy(w01, 3, w08);
  casadi_mtimes(w31, casadi_s0, w04, casadi_s1, w08, casadi_s0, w, 0);
  /* #107: @8 = @8' */
  /* #108: @33 = (@33+@8) */
  for (i=0, rr=w33, cs=w08; i<3; ++i) (*rr++) += (*cs++);
  /* #109: @8 = (@33/@25) */
  for (i=0, rr=w08, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #110: @0 = dot(@29, @8) */
  w00 = casadi_dot(3, w29, w08);
  /* #111: @19 = (@7*@0) */
  w19  = (w07*w00);
  /* #112: @19 = (-@19) */
  w19 = (- w19 );
  /* #113: @36 = @27; (@36[0] += @19) */
  casadi_copy(w27, 4, w36);
  for (rr=w36+0, cs=(&w19); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #114: @30 = (@30/@25) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w25;
  /* #115: @31 = (-@30) */
  for (i=0, rr=w31, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #116: @19 = dot(@31, @33) */
  w19 = casadi_dot(3, w31, w33);
  /* #117: @17 = (@13/@24) */
  w17  = (w13/w24);
  /* #118: @26 = (@17*@0) */
  w26  = (w17*w00);
  /* #119: @19 = (@19+@26) */
  w19 += w26;
  /* #120: @26 = (2.*@25) */
  w26 = (2.* w25 );
  /* #121: @19 = (@19/@26) */
  w19 /= w26;
  /* #122: @37 = (@19*@2) */
  for (i=0, rr=w37, cs=w02; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #123: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #124: @38 = (@21*@8) */
  for (i=0, rr=w38, cs=w08; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #125: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #126: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #127: (@36[1:4] += @37) */
  for (rr=w36+1, cs=w37; rr!=w36+4; rr+=1) *rr += *cs++;
  /* #128: @39 = (@15?@36:0) */
  for (i=0, rr=w39, cs=w36; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #129: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #130: @36 = (@23?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #131: @39 = (@39+@36) */
  for (i=0, rr=w39, cs=w36; i<4; ++i) (*rr++) += (*cs++);
  /* #132: {@40, @41, @42, @43} = vertsplit(@39) */
  w40 = w39[0];
  w41 = w39[1];
  w42 = w39[2];
  w43 = w39[3];
  /* #133: @44 = (@14*@43) */
  w44  = (w14*w43);
  /* #134: @39 = @27; (@39[3] += @44) */
  casadi_copy(w27, 4, w39);
  for (rr=w39+3, cs=(&w44); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #135: @44 = (@18*@43) */
  w44  = (w18*w43);
  /* #136: @44 = (-@44) */
  w44 = (- w44 );
  /* #137: (@39[2] += @44) */
  for (rr=w39+2, cs=(&w44); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #138: @44 = (@20*@43) */
  w44  = (w20*w43);
  /* #139: (@39[1] += @44) */
  for (rr=w39+1, cs=(&w44); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #140: @43 = (@22*@43) */
  w43  = (w22*w43);
  /* #141: (@39[0] += @43) */
  for (rr=w39+0, cs=(&w43); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #142: @43 = (@18*@42) */
  w43  = (w18*w42);
  /* #143: (@39[3] += @43) */
  for (rr=w39+3, cs=(&w43); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #144: @43 = (@14*@42) */
  w43  = (w14*w42);
  /* #145: (@39[2] += @43) */
  for (rr=w39+2, cs=(&w43); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #146: @43 = (@22*@42) */
  w43  = (w22*w42);
  /* #147: @43 = (-@43) */
  w43 = (- w43 );
  /* #148: (@39[1] += @43) */
  for (rr=w39+1, cs=(&w43); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #149: @42 = (@20*@42) */
  w42  = (w20*w42);
  /* #150: (@39[0] += @42) */
  for (rr=w39+0, cs=(&w42); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #151: @42 = (@20*@41) */
  w42  = (w20*w41);
  /* #152: @42 = (-@42) */
  w42 = (- w42 );
  /* #153: (@39[3] += @42) */
  for (rr=w39+3, cs=(&w42); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #154: @42 = (@22*@41) */
  w42  = (w22*w41);
  /* #155: (@39[2] += @42) */
  for (rr=w39+2, cs=(&w42); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #156: @42 = (@14*@41) */
  w42  = (w14*w41);
  /* #157: (@39[1] += @42) */
  for (rr=w39+1, cs=(&w42); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #158: @41 = (@18*@41) */
  w41  = (w18*w41);
  /* #159: (@39[0] += @41) */
  for (rr=w39+0, cs=(&w41); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #160: @41 = (@22*@40) */
  w41  = (w22*w40);
  /* #161: @41 = (-@41) */
  w41 = (- w41 );
  /* #162: (@39[3] += @41) */
  for (rr=w39+3, cs=(&w41); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #163: @41 = (@20*@40) */
  w41  = (w20*w40);
  /* #164: @41 = (-@41) */
  w41 = (- w41 );
  /* #165: (@39[2] += @41) */
  for (rr=w39+2, cs=(&w41); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #166: @41 = (@18*@40) */
  w41  = (w18*w40);
  /* #167: @41 = (-@41) */
  w41 = (- w41 );
  /* #168: (@39[1] += @41) */
  for (rr=w39+1, cs=(&w41); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #169: @40 = (@14*@40) */
  w40  = (w14*w40);
  /* #170: (@39[0] += @40) */
  for (rr=w39+0, cs=(&w40); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #171: @40 = dot(@28, @39) */
  w40 = casadi_dot(4, w28, w39);
  /* #172: @40 = (@40/@11) */
  w40 /= w11;
  /* #173: @36 = (@40*@12) */
  for (i=0, rr=w36, cs=w12; i<4; ++i) (*rr++)  = (w40*(*cs++));
  /* #174: @45 = (@39/@11) */
  for (i=0, rr=w45, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)/w11);
  /* #175: {@41, @42, @43, @44} = vertsplit(@45) */
  w41 = w45[0];
  w42 = w45[1];
  w43 = w45[2];
  w44 = w45[3];
  /* #176: @44 = (-@44) */
  w44 = (- w44 );
  /* #177: (@36[3] += @44) */
  for (rr=w36+3, cs=(&w44); rr!=w36+4; rr+=1) *rr += *cs++;
  /* #178: @43 = (-@43) */
  w43 = (- w43 );
  /* #179: (@36[2] += @43) */
  for (rr=w36+2, cs=(&w43); rr!=w36+3; rr+=1) *rr += *cs++;
  /* #180: @42 = (-@42) */
  w42 = (- w42 );
  /* #181: (@36[1] += @42) */
  for (rr=w36+1, cs=(&w42); rr!=w36+2; rr+=1) *rr += *cs++;
  /* #182: (@36[0] += @41) */
  for (rr=w36+0, cs=(&w41); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #183: @46 = zeros(3x1,0nz) */
  /* #184: @47 = vertcat(@6, @10, @36, @46) */
  rr=w47;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #185: @48 = dense(@47) */
  casadi_densify(w47, casadi_s2, w48, 0);
  /* #186: output[1][0] = @48 */
  casadi_copy(w48, 13, res[1]);
  /* #187: @49 = zeros(13x13,22nz) */
  casadi_clear(w49, 22);
  /* #188: @47 = ones(13x1,10nz) */
  casadi_fill(w47, 10, 1.);
  /* #189: {@6, @10, @41, NULL} = vertsplit(@47) */
  casadi_copy(w47, 3, w06);
  casadi_copy(w47+3, 3, w10);
  w41 = w47[6];
  /* #190: @6 = @6' */
  /* #191: @37 = mac(@6,@5,@1) */
  casadi_copy(w01, 3, w37);
  casadi_mtimes(w06, casadi_s0, wr05, casadi_s1, w37, casadi_s0, w, 0);
  /* #192: @37 = @37' */
  /* #193: @5 = mac(@6,@34,@1) */
  casadi_copy(w01, 3, w05);
  casadi_mtimes(w06, casadi_s0, w34, casadi_s1, w05, casadi_s0, w, 0);
  /* #194: @5 = @5' */
  /* #195: @37 = (@37+@5) */
  for (i=0, rr=w37, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #196: @10 = @10' */
  /* #197: @5 = mac(@10,@9,@1) */
  casadi_copy(w01, 3, w05);
  casadi_mtimes(w10, casadi_s0, wr09, casadi_s1, w05, casadi_s0, w, 0);
  /* #198: @5 = @5' */
  /* #199: @9 = mac(@10,@35,@1) */
  casadi_copy(w01, 3, w09);
  casadi_mtimes(w10, casadi_s0, w35, casadi_s1, w09, casadi_s0, w, 0);
  /* #200: @9 = @9' */
  /* #201: @5 = (@5+@9) */
  for (i=0, rr=w05, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #202: @42 = @41[0] */
  for (rr=(&w42), cs=(&w41)+0; cs!=(&w41)+1; cs+=1) *rr++ = *cs;
  /* #203: @50 = 00 */
  /* #204: @43 = vertcat(@42, @50, @50, @50) */
  rr=(&w43);
  *rr++ = w42;
  /* #205: @43 = (@43/@11) */
  w43 /= w11;
  /* #206: @36 = dense(@43) */
  casadi_densify((&w43), casadi_s3, w36, 0);
  /* #207: @43 = project(@12) */
  casadi_sparsify(w12, (&w43), casadi_s3, 0);
  /* #208: @42 = dot(@43, @41) */
  w42 = casadi_dot(1, (&w43), (&w41));
  /* #209: @42 = (@42/@11) */
  w42 /= w11;
  /* #210: @51 = (@16*@42) */
  for (i=0, rr=w51, cr=w16; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #211: @36 = (@36-@51) */
  for (i=0, rr=w36, cs=w51; i<4; ++i) (*rr++) -= (*cs++);
  /* #212: @43 = @36[0] */
  for (rr=(&w43), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #213: @44 = (@14*@43) */
  w44  = (w14*w43);
  /* #214: @52 = @36[1] */
  for (rr=(&w52), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #215: @53 = (@18*@52) */
  w53  = (w18*w52);
  /* #216: @44 = (@44-@53) */
  w44 -= w53;
  /* #217: @53 = @36[2] */
  for (rr=(&w53), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #218: @54 = (@20*@53) */
  w54  = (w20*w53);
  /* #219: @44 = (@44-@54) */
  w44 -= w54;
  /* #220: @54 = @36[3] */
  for (rr=(&w54), cs=w36+3; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #221: @55 = (@22*@54) */
  w55  = (w22*w54);
  /* #222: @44 = (@44-@55) */
  w44 -= w55;
  /* #223: @55 = (@18*@43) */
  w55  = (w18*w43);
  /* #224: @56 = (@14*@52) */
  w56  = (w14*w52);
  /* #225: @55 = (@55+@56) */
  w55 += w56;
  /* #226: @56 = (@22*@53) */
  w56  = (w22*w53);
  /* #227: @55 = (@55+@56) */
  w55 += w56;
  /* #228: @56 = (@20*@54) */
  w56  = (w20*w54);
  /* #229: @55 = (@55-@56) */
  w55 -= w56;
  /* #230: @56 = (@20*@43) */
  w56  = (w20*w43);
  /* #231: @57 = (@22*@52) */
  w57  = (w22*w52);
  /* #232: @56 = (@56-@57) */
  w56 -= w57;
  /* #233: @57 = (@14*@53) */
  w57  = (w14*w53);
  /* #234: @56 = (@56+@57) */
  w56 += w57;
  /* #235: @57 = (@18*@54) */
  w57  = (w18*w54);
  /* #236: @56 = (@56+@57) */
  w56 += w57;
  /* #237: @43 = (@22*@43) */
  w43  = (w22*w43);
  /* #238: @52 = (@20*@52) */
  w52  = (w20*w52);
  /* #239: @43 = (@43+@52) */
  w43 += w52;
  /* #240: @53 = (@18*@53) */
  w53  = (w18*w53);
  /* #241: @43 = (@43-@53) */
  w43 -= w53;
  /* #242: @54 = (@14*@54) */
  w54  = (w14*w54);
  /* #243: @43 = (@43+@54) */
  w43 += w54;
  /* #244: @51 = vertcat(@44, @55, @56, @43) */
  rr=w51;
  *rr++ = w44;
  *rr++ = w55;
  *rr++ = w56;
  *rr++ = w43;
  /* #245: @58 = (-@51) */
  for (i=0, rr=w58, cs=w51; i<4; ++i) *rr++ = (- *cs++ );
  /* #246: @58 = (@23?@58:0) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #247: @51 = (@15?@51:0) */
  for (i=0, rr=w51, cs=w51; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #248: @58 = (@58+@51) */
  for (i=0, rr=w58, cs=w51; i<4; ++i) (*rr++) += (*cs++);
  /* #249: @9 = @58[1:4] */
  for (rr=w09, cs=w58+1; cs!=w58+4; cs+=1) *rr++ = *cs;
  /* #250: @44 = dot(@2, @9) */
  w44 = casadi_dot(3, w02, w09);
  /* #251: @55 = dot(@9, @2) */
  w55 = casadi_dot(3, w09, w02);
  /* #252: @44 = (@44+@55) */
  w44 += w55;
  /* #253: @55 = (@44/@26) */
  w55  = (w44/w26);
  /* #254: @56 = (@55/@24) */
  w56  = (w55/w24);
  /* #255: @43 = (@7/@24) */
  w43  = (w07/w24);
  /* #256: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #257: @54 = @58[0] */
  for (rr=(&w54), cs=w58+0; cs!=w58+1; cs+=1) *rr++ = *cs;
  /* #258: @53 = (@13*@54) */
  w53  = (w13*w54);
  /* #259: @44 = (@44+@53) */
  w44 += w53;
  /* #260: @53 = (@43*@44) */
  w53  = (w43*w44);
  /* #261: @56 = (@56-@53) */
  w56 -= w53;
  /* #262: @56 = (@0*@56) */
  w56  = (w00*w56);
  /* #263: @10 = (2.*@9) */
  for (i=0, rr=w10, cs=w09; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #264: @35 = (@21*@10) */
  for (i=0, rr=w35, cs=w10; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #265: @53 = (@17*@55) */
  w53  = (w17*w55);
  /* #266: @52 = (@7*@54) */
  w52  = (w07*w54);
  /* #267: @53 = (@53-@52) */
  w53 -= w52;
  /* #268: @6 = (@29*@53) */
  for (i=0, rr=w06, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #269: @35 = (@35+@6) */
  for (i=0, rr=w35, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #270: @35 = (@35/@25) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w25;
  /* #271: @6 = (@30*@55) */
  for (i=0, rr=w06, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #272: @35 = (@35-@6) */
  for (i=0, rr=w35, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #273: @6 = @35' */
  casadi_copy(w35, 3, w06);
  /* #274: @34 = mac(@6,@32,@1) */
  casadi_copy(w01, 3, w34);
  casadi_mtimes(w06, casadi_s0, wr32, casadi_s1, w34, casadi_s0, w, 0);
  /* #275: @34 = @34' */
  /* #276: @38 = mac(@6,@4,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes(w06, casadi_s0, w04, casadi_s1, w38, casadi_s0, w, 0);
  /* #277: @38 = @38' */
  /* #278: @34 = (@34+@38) */
  for (i=0, rr=w34, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #279: @38 = (@34/@25) */
  for (i=0, rr=w38, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #280: @6 = (@8/@25) */
  for (i=0, rr=w06, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #281: @59 = (@6*@55) */
  for (i=0, rr=w59, cr=w06; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #282: @38 = (@38-@59) */
  for (i=0, rr=w38, cs=w59; i<3; ++i) (*rr++) -= (*cs++);
  /* #283: @52 = dot(@29, @38) */
  w52 = casadi_dot(3, w29, w38);
  /* #284: @57 = dot(@10, @8) */
  w57 = casadi_dot(3, w10, w08);
  /* #285: @52 = (@52+@57) */
  w52 += w57;
  /* #286: @57 = (@7*@52) */
  w57  = (w07*w52);
  /* #287: @56 = (@56+@57) */
  w56 += w57;
  /* #288: @56 = (-@56) */
  w56 = (- w56 );
  /* #289: @58 = @27; (@58[0] += @56) */
  casadi_copy(w27, 4, w58);
  for (rr=w58+0, cs=(&w56); rr!=w58+1; rr+=1) *rr += *cs++;
  /* #290: @56 = dot(@31, @34) */
  w56 = casadi_dot(3, w31, w34);
  /* #291: @35 = (@35/@25) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w25;
  /* #292: @34 = (@30/@25) */
  for (i=0, rr=w34, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #293: @10 = (@34*@55) */
  for (i=0, rr=w10, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #294: @35 = (@35-@10) */
  for (i=0, rr=w35, cs=w10; i<3; ++i) (*rr++) -= (*cs++);
  /* #295: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #296: @57 = dot(@35, @33) */
  w57 = casadi_dot(3, w35, w33);
  /* #297: @56 = (@56+@57) */
  w56 += w57;
  /* #298: @54 = (@54/@24) */
  w54 /= w24;
  /* #299: @57 = (@17/@24) */
  w57  = (w17/w24);
  /* #300: @44 = (@57*@44) */
  w44  = (w57*w44);
  /* #301: @54 = (@54-@44) */
  w54 -= w44;
  /* #302: @54 = (@0*@54) */
  w54  = (w00*w54);
  /* #303: @52 = (@17*@52) */
  w52  = (w17*w52);
  /* #304: @54 = (@54+@52) */
  w54 += w52;
  /* #305: @56 = (@56+@54) */
  w56 += w54;
  /* #306: @56 = (@56/@26) */
  w56 /= w26;
  /* #307: @54 = (@19/@26) */
  w54  = (w19/w26);
  /* #308: @55 = (2.*@55) */
  w55 = (2.* w55 );
  /* #309: @55 = (@54*@55) */
  w55  = (w54*w55);
  /* #310: @56 = (@56-@55) */
  w56 -= w55;
  /* #311: @35 = (@2*@56) */
  for (i=0, rr=w35, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w56);
  /* #312: @9 = (@19*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #313: @35 = (@35+@9) */
  for (i=0, rr=w35, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #314: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #315: @9 = (@8*@53) */
  for (i=0, rr=w09, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #316: @38 = (@21*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #317: @9 = (@9+@38) */
  for (i=0, rr=w09, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #318: @9 = (2.*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #319: @35 = (@35+@9) */
  for (i=0, rr=w35, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #320: (@58[1:4] += @35) */
  for (rr=w58+1, cs=w35; rr!=w58+4; rr+=1) *rr += *cs++;
  /* #321: @51 = (@15?@58:0) */
  for (i=0, rr=w51, cs=w58; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #322: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) *rr++ = (- *cs++ );
  /* #323: @58 = (@23?@58:0) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #324: @51 = (@51+@58) */
  for (i=0, rr=w51, cs=w58; i<4; ++i) (*rr++) += (*cs++);
  /* #325: {@53, @56, @55, @52} = vertsplit(@51) */
  w53 = w51[0];
  w56 = w51[1];
  w55 = w51[2];
  w52 = w51[3];
  /* #326: @44 = (@14*@52) */
  w44  = (w14*w52);
  /* #327: @51 = @27; (@51[3] += @44) */
  casadi_copy(w27, 4, w51);
  for (rr=w51+3, cs=(&w44); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #328: @44 = (@18*@52) */
  w44  = (w18*w52);
  /* #329: @44 = (-@44) */
  w44 = (- w44 );
  /* #330: (@51[2] += @44) */
  for (rr=w51+2, cs=(&w44); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #331: @44 = (@20*@52) */
  w44  = (w20*w52);
  /* #332: (@51[1] += @44) */
  for (rr=w51+1, cs=(&w44); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #333: @52 = (@22*@52) */
  w52  = (w22*w52);
  /* #334: (@51[0] += @52) */
  for (rr=w51+0, cs=(&w52); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #335: @52 = (@18*@55) */
  w52  = (w18*w55);
  /* #336: (@51[3] += @52) */
  for (rr=w51+3, cs=(&w52); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #337: @52 = (@14*@55) */
  w52  = (w14*w55);
  /* #338: (@51[2] += @52) */
  for (rr=w51+2, cs=(&w52); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #339: @52 = (@22*@55) */
  w52  = (w22*w55);
  /* #340: @52 = (-@52) */
  w52 = (- w52 );
  /* #341: (@51[1] += @52) */
  for (rr=w51+1, cs=(&w52); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #342: @55 = (@20*@55) */
  w55  = (w20*w55);
  /* #343: (@51[0] += @55) */
  for (rr=w51+0, cs=(&w55); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #344: @55 = (@20*@56) */
  w55  = (w20*w56);
  /* #345: @55 = (-@55) */
  w55 = (- w55 );
  /* #346: (@51[3] += @55) */
  for (rr=w51+3, cs=(&w55); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #347: @55 = (@22*@56) */
  w55  = (w22*w56);
  /* #348: (@51[2] += @55) */
  for (rr=w51+2, cs=(&w55); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #349: @55 = (@14*@56) */
  w55  = (w14*w56);
  /* #350: (@51[1] += @55) */
  for (rr=w51+1, cs=(&w55); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #351: @56 = (@18*@56) */
  w56  = (w18*w56);
  /* #352: (@51[0] += @56) */
  for (rr=w51+0, cs=(&w56); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #353: @56 = (@22*@53) */
  w56  = (w22*w53);
  /* #354: @56 = (-@56) */
  w56 = (- w56 );
  /* #355: (@51[3] += @56) */
  for (rr=w51+3, cs=(&w56); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #356: @56 = (@20*@53) */
  w56  = (w20*w53);
  /* #357: @56 = (-@56) */
  w56 = (- w56 );
  /* #358: (@51[2] += @56) */
  for (rr=w51+2, cs=(&w56); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #359: @56 = (@18*@53) */
  w56  = (w18*w53);
  /* #360: @56 = (-@56) */
  w56 = (- w56 );
  /* #361: (@51[1] += @56) */
  for (rr=w51+1, cs=(&w56); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #362: @53 = (@14*@53) */
  w53  = (w14*w53);
  /* #363: (@51[0] += @53) */
  for (rr=w51+0, cs=(&w53); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #364: @53 = dot(@28, @51) */
  w53 = casadi_dot(4, w28, w51);
  /* #365: @36 = (@36/@11) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w11;
  /* #366: @58 = (@16/@11) */
  for (i=0, rr=w58, cr=w16; i<4; ++i) (*rr++)  = ((*cr++)/w11);
  /* #367: @60 = (@58*@42) */
  for (i=0, rr=w60, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #368: @36 = (@36-@60) */
  for (i=0, rr=w36, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #369: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #370: @56 = dot(@36, @39) */
  w56 = casadi_dot(4, w36, w39);
  /* #371: @53 = (@53+@56) */
  w53 += w56;
  /* #372: @53 = (@53/@11) */
  w53 /= w11;
  /* #373: @56 = (@40/@11) */
  w56  = (w40/w11);
  /* #374: @55 = (@56*@42) */
  w55  = (w56*w42);
  /* #375: @53 = (@53-@55) */
  w53 -= w55;
  /* #376: @36 = (@12*@53) */
  for (i=0, rr=w36, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #377: @41 = (@40*@41) */
  w41  = (w40*w41);
  /* #378: @60 = dense(@41) */
  casadi_densify((&w41), casadi_s3, w60, 0);
  /* #379: @36 = (@36+@60) */
  for (i=0, rr=w36, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #380: @51 = (@51/@11) */
  for (i=0, rr=w51; i<4; ++i) (*rr++) /= w11;
  /* #381: @45 = (@45/@11) */
  for (i=0, rr=w45; i<4; ++i) (*rr++) /= w11;
  /* #382: @60 = (@45*@42) */
  for (i=0, rr=w60, cr=w45; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #383: @51 = (@51-@60) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #384: {@42, @41, @53, @55} = vertsplit(@51) */
  w42 = w51[0];
  w41 = w51[1];
  w53 = w51[2];
  w55 = w51[3];
  /* #385: @55 = (-@55) */
  w55 = (- w55 );
  /* #386: (@36[3] += @55) */
  for (rr=w36+3, cs=(&w55); rr!=w36+4; rr+=1) *rr += *cs++;
  /* #387: @53 = (-@53) */
  w53 = (- w53 );
  /* #388: (@36[2] += @53) */
  for (rr=w36+2, cs=(&w53); rr!=w36+3; rr+=1) *rr += *cs++;
  /* #389: @41 = (-@41) */
  w41 = (- w41 );
  /* #390: (@36[1] += @41) */
  for (rr=w36+1, cs=(&w41); rr!=w36+2; rr+=1) *rr += *cs++;
  /* #391: (@36[0] += @42) */
  for (rr=w36+0, cs=(&w42); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #392: @47 = vertcat(@37, @5, @36, @46) */
  rr=w47;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #393: @61 = @47[:10] */
  for (rr=w61, cs=w47+0; cs!=w47+10; cs+=1) *rr++ = *cs;
  /* #394: (@49[:10] = @61) */
  for (rr=w49+0, cs=w61; rr!=w49+10; rr+=1) *rr = *cs++;
  /* #395: (@49[0, 1, 2, 3, 4, 5, 6, 10, 14, 18] = @61) */
  for (cii=casadi_s4, rr=w49, cs=w61; cii!=casadi_s4+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #396: @42 = ones(13x1,1nz) */
  w42 = 1.;
  /* #397: {NULL, NULL, @41, NULL} = vertsplit(@42) */
  w41 = w42;
  /* #398: @42 = @41[0] */
  for (rr=(&w42), cs=(&w41)+0; cs!=(&w41)+1; cs+=1) *rr++ = *cs;
  /* #399: @42 = (-@42) */
  w42 = (- w42 );
  /* #400: @53 = vertcat(@50, @42, @50, @50) */
  rr=(&w53);
  *rr++ = w42;
  /* #401: @53 = (@53/@11) */
  w53 /= w11;
  /* #402: @36 = dense(@53) */
  casadi_densify((&w53), casadi_s5, w36, 0);
  /* #403: @53 = project(@12) */
  casadi_sparsify(w12, (&w53), casadi_s5, 0);
  /* #404: @42 = dot(@53, @41) */
  w42 = casadi_dot(1, (&w53), (&w41));
  /* #405: @42 = (@42/@11) */
  w42 /= w11;
  /* #406: @51 = (@16*@42) */
  for (i=0, rr=w51, cr=w16; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #407: @36 = (@36-@51) */
  for (i=0, rr=w36, cs=w51; i<4; ++i) (*rr++) -= (*cs++);
  /* #408: @53 = @36[0] */
  for (rr=(&w53), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #409: @55 = (@14*@53) */
  w55  = (w14*w53);
  /* #410: @52 = @36[1] */
  for (rr=(&w52), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #411: @44 = (@18*@52) */
  w44  = (w18*w52);
  /* #412: @55 = (@55-@44) */
  w55 -= w44;
  /* #413: @44 = @36[2] */
  for (rr=(&w44), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #414: @62 = (@20*@44) */
  w62  = (w20*w44);
  /* #415: @55 = (@55-@62) */
  w55 -= w62;
  /* #416: @62 = @36[3] */
  for (rr=(&w62), cs=w36+3; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #417: @63 = (@22*@62) */
  w63  = (w22*w62);
  /* #418: @55 = (@55-@63) */
  w55 -= w63;
  /* #419: @63 = (@18*@53) */
  w63  = (w18*w53);
  /* #420: @64 = (@14*@52) */
  w64  = (w14*w52);
  /* #421: @63 = (@63+@64) */
  w63 += w64;
  /* #422: @64 = (@22*@44) */
  w64  = (w22*w44);
  /* #423: @63 = (@63+@64) */
  w63 += w64;
  /* #424: @64 = (@20*@62) */
  w64  = (w20*w62);
  /* #425: @63 = (@63-@64) */
  w63 -= w64;
  /* #426: @64 = (@20*@53) */
  w64  = (w20*w53);
  /* #427: @65 = (@22*@52) */
  w65  = (w22*w52);
  /* #428: @64 = (@64-@65) */
  w64 -= w65;
  /* #429: @65 = (@14*@44) */
  w65  = (w14*w44);
  /* #430: @64 = (@64+@65) */
  w64 += w65;
  /* #431: @65 = (@18*@62) */
  w65  = (w18*w62);
  /* #432: @64 = (@64+@65) */
  w64 += w65;
  /* #433: @53 = (@22*@53) */
  w53  = (w22*w53);
  /* #434: @52 = (@20*@52) */
  w52  = (w20*w52);
  /* #435: @53 = (@53+@52) */
  w53 += w52;
  /* #436: @44 = (@18*@44) */
  w44  = (w18*w44);
  /* #437: @53 = (@53-@44) */
  w53 -= w44;
  /* #438: @62 = (@14*@62) */
  w62  = (w14*w62);
  /* #439: @53 = (@53+@62) */
  w53 += w62;
  /* #440: @51 = vertcat(@55, @63, @64, @53) */
  rr=w51;
  *rr++ = w55;
  *rr++ = w63;
  *rr++ = w64;
  *rr++ = w53;
  /* #441: @60 = (-@51) */
  for (i=0, rr=w60, cs=w51; i<4; ++i) *rr++ = (- *cs++ );
  /* #442: @60 = (@23?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #443: @51 = (@15?@51:0) */
  for (i=0, rr=w51, cs=w51; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #444: @60 = (@60+@51) */
  for (i=0, rr=w60, cs=w51; i<4; ++i) (*rr++) += (*cs++);
  /* #445: @37 = @60[1:4] */
  for (rr=w37, cs=w60+1; cs!=w60+4; cs+=1) *rr++ = *cs;
  /* #446: @55 = dot(@2, @37) */
  w55 = casadi_dot(3, w02, w37);
  /* #447: @63 = dot(@37, @2) */
  w63 = casadi_dot(3, w37, w02);
  /* #448: @55 = (@55+@63) */
  w55 += w63;
  /* #449: @63 = (@55/@26) */
  w63  = (w55/w26);
  /* #450: @64 = (@63/@24) */
  w64  = (w63/w24);
  /* #451: @53 = @60[0] */
  for (rr=(&w53), cs=w60+0; cs!=w60+1; cs+=1) *rr++ = *cs;
  /* #452: @62 = (@13*@53) */
  w62  = (w13*w53);
  /* #453: @55 = (@55+@62) */
  w55 += w62;
  /* #454: @62 = (@43*@55) */
  w62  = (w43*w55);
  /* #455: @64 = (@64-@62) */
  w64 -= w62;
  /* #456: @64 = (@0*@64) */
  w64  = (w00*w64);
  /* #457: @5 = (2.*@37) */
  for (i=0, rr=w05, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #458: @35 = (@21*@5) */
  for (i=0, rr=w35, cs=w05; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #459: @62 = (@17*@63) */
  w62  = (w17*w63);
  /* #460: @44 = (@7*@53) */
  w44  = (w07*w53);
  /* #461: @62 = (@62-@44) */
  w62 -= w44;
  /* #462: @9 = (@29*@62) */
  for (i=0, rr=w09, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #463: @35 = (@35+@9) */
  for (i=0, rr=w35, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #464: @35 = (@35/@25) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w25;
  /* #465: @9 = (@30*@63) */
  for (i=0, rr=w09, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #466: @35 = (@35-@9) */
  for (i=0, rr=w35, cs=w09; i<3; ++i) (*rr++) -= (*cs++);
  /* #467: @9 = @35' */
  casadi_copy(w35, 3, w09);
  /* #468: @38 = mac(@9,@32,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes(w09, casadi_s0, wr32, casadi_s1, w38, casadi_s0, w, 0);
  /* #469: @38 = @38' */
  /* #470: @10 = mac(@9,@4,@1) */
  casadi_copy(w01, 3, w10);
  casadi_mtimes(w09, casadi_s0, w04, casadi_s1, w10, casadi_s0, w, 0);
  /* #471: @10 = @10' */
  /* #472: @38 = (@38+@10) */
  for (i=0, rr=w38, cs=w10; i<3; ++i) (*rr++) += (*cs++);
  /* #473: @10 = (@38/@25) */
  for (i=0, rr=w10, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #474: @9 = (@6*@63) */
  for (i=0, rr=w09, cr=w06; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #475: @10 = (@10-@9) */
  for (i=0, rr=w10, cs=w09; i<3; ++i) (*rr++) -= (*cs++);
  /* #476: @44 = dot(@29, @10) */
  w44 = casadi_dot(3, w29, w10);
  /* #477: @52 = dot(@5, @8) */
  w52 = casadi_dot(3, w05, w08);
  /* #478: @44 = (@44+@52) */
  w44 += w52;
  /* #479: @52 = (@7*@44) */
  w52  = (w07*w44);
  /* #480: @64 = (@64+@52) */
  w64 += w52;
  /* #481: @64 = (-@64) */
  w64 = (- w64 );
  /* #482: @60 = @27; (@60[0] += @64) */
  casadi_copy(w27, 4, w60);
  for (rr=w60+0, cs=(&w64); rr!=w60+1; rr+=1) *rr += *cs++;
  /* #483: @64 = dot(@31, @38) */
  w64 = casadi_dot(3, w31, w38);
  /* #484: @35 = (@35/@25) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w25;
  /* #485: @38 = (@34*@63) */
  for (i=0, rr=w38, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #486: @35 = (@35-@38) */
  for (i=0, rr=w35, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #487: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #488: @52 = dot(@35, @33) */
  w52 = casadi_dot(3, w35, w33);
  /* #489: @64 = (@64+@52) */
  w64 += w52;
  /* #490: @53 = (@53/@24) */
  w53 /= w24;
  /* #491: @55 = (@57*@55) */
  w55  = (w57*w55);
  /* #492: @53 = (@53-@55) */
  w53 -= w55;
  /* #493: @53 = (@0*@53) */
  w53  = (w00*w53);
  /* #494: @44 = (@17*@44) */
  w44  = (w17*w44);
  /* #495: @53 = (@53+@44) */
  w53 += w44;
  /* #496: @64 = (@64+@53) */
  w64 += w53;
  /* #497: @64 = (@64/@26) */
  w64 /= w26;
  /* #498: @63 = (2.*@63) */
  w63 = (2.* w63 );
  /* #499: @63 = (@54*@63) */
  w63  = (w54*w63);
  /* #500: @64 = (@64-@63) */
  w64 -= w63;
  /* #501: @35 = (@2*@64) */
  for (i=0, rr=w35, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w64);
  /* #502: @37 = (@19*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #503: @35 = (@35+@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #504: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #505: @37 = (@8*@62) */
  for (i=0, rr=w37, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #506: @10 = (@21*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #507: @37 = (@37+@10) */
  for (i=0, rr=w37, cs=w10; i<3; ++i) (*rr++) += (*cs++);
  /* #508: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #509: @35 = (@35+@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #510: (@60[1:4] += @35) */
  for (rr=w60+1, cs=w35; rr!=w60+4; rr+=1) *rr += *cs++;
  /* #511: @51 = (@15?@60:0) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #512: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #513: @60 = (@23?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #514: @51 = (@51+@60) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #515: {@62, @64, @63, @53} = vertsplit(@51) */
  w62 = w51[0];
  w64 = w51[1];
  w63 = w51[2];
  w53 = w51[3];
  /* #516: @44 = (@14*@53) */
  w44  = (w14*w53);
  /* #517: @51 = @27; (@51[3] += @44) */
  casadi_copy(w27, 4, w51);
  for (rr=w51+3, cs=(&w44); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #518: @44 = (@18*@53) */
  w44  = (w18*w53);
  /* #519: @44 = (-@44) */
  w44 = (- w44 );
  /* #520: (@51[2] += @44) */
  for (rr=w51+2, cs=(&w44); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #521: @44 = (@20*@53) */
  w44  = (w20*w53);
  /* #522: (@51[1] += @44) */
  for (rr=w51+1, cs=(&w44); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #523: @53 = (@22*@53) */
  w53  = (w22*w53);
  /* #524: (@51[0] += @53) */
  for (rr=w51+0, cs=(&w53); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #525: @53 = (@18*@63) */
  w53  = (w18*w63);
  /* #526: (@51[3] += @53) */
  for (rr=w51+3, cs=(&w53); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #527: @53 = (@14*@63) */
  w53  = (w14*w63);
  /* #528: (@51[2] += @53) */
  for (rr=w51+2, cs=(&w53); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #529: @53 = (@22*@63) */
  w53  = (w22*w63);
  /* #530: @53 = (-@53) */
  w53 = (- w53 );
  /* #531: (@51[1] += @53) */
  for (rr=w51+1, cs=(&w53); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #532: @63 = (@20*@63) */
  w63  = (w20*w63);
  /* #533: (@51[0] += @63) */
  for (rr=w51+0, cs=(&w63); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #534: @63 = (@20*@64) */
  w63  = (w20*w64);
  /* #535: @63 = (-@63) */
  w63 = (- w63 );
  /* #536: (@51[3] += @63) */
  for (rr=w51+3, cs=(&w63); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #537: @63 = (@22*@64) */
  w63  = (w22*w64);
  /* #538: (@51[2] += @63) */
  for (rr=w51+2, cs=(&w63); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #539: @63 = (@14*@64) */
  w63  = (w14*w64);
  /* #540: (@51[1] += @63) */
  for (rr=w51+1, cs=(&w63); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #541: @64 = (@18*@64) */
  w64  = (w18*w64);
  /* #542: (@51[0] += @64) */
  for (rr=w51+0, cs=(&w64); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #543: @64 = (@22*@62) */
  w64  = (w22*w62);
  /* #544: @64 = (-@64) */
  w64 = (- w64 );
  /* #545: (@51[3] += @64) */
  for (rr=w51+3, cs=(&w64); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #546: @64 = (@20*@62) */
  w64  = (w20*w62);
  /* #547: @64 = (-@64) */
  w64 = (- w64 );
  /* #548: (@51[2] += @64) */
  for (rr=w51+2, cs=(&w64); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #549: @64 = (@18*@62) */
  w64  = (w18*w62);
  /* #550: @64 = (-@64) */
  w64 = (- w64 );
  /* #551: (@51[1] += @64) */
  for (rr=w51+1, cs=(&w64); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #552: @62 = (@14*@62) */
  w62  = (w14*w62);
  /* #553: (@51[0] += @62) */
  for (rr=w51+0, cs=(&w62); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #554: @62 = dot(@28, @51) */
  w62 = casadi_dot(4, w28, w51);
  /* #555: @36 = (@36/@11) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w11;
  /* #556: @60 = (@58*@42) */
  for (i=0, rr=w60, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #557: @36 = (@36-@60) */
  for (i=0, rr=w36, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #558: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #559: @64 = dot(@36, @39) */
  w64 = casadi_dot(4, w36, w39);
  /* #560: @62 = (@62+@64) */
  w62 += w64;
  /* #561: @62 = (@62/@11) */
  w62 /= w11;
  /* #562: @64 = (@56*@42) */
  w64  = (w56*w42);
  /* #563: @62 = (@62-@64) */
  w62 -= w64;
  /* #564: @36 = (@12*@62) */
  for (i=0, rr=w36, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w62);
  /* #565: @41 = (@40*@41) */
  w41  = (w40*w41);
  /* #566: @60 = dense(@41) */
  casadi_densify((&w41), casadi_s5, w60, 0);
  /* #567: @36 = (@36+@60) */
  for (i=0, rr=w36, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #568: @51 = (@51/@11) */
  for (i=0, rr=w51; i<4; ++i) (*rr++) /= w11;
  /* #569: @60 = (@45*@42) */
  for (i=0, rr=w60, cr=w45; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #570: @51 = (@51-@60) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #571: {@42, @41, @62, @64} = vertsplit(@51) */
  w42 = w51[0];
  w41 = w51[1];
  w62 = w51[2];
  w64 = w51[3];
  /* #572: @64 = (-@64) */
  w64 = (- w64 );
  /* #573: (@36[3] += @64) */
  for (rr=w36+3, cs=(&w64); rr!=w36+4; rr+=1) *rr += *cs++;
  /* #574: @62 = (-@62) */
  w62 = (- w62 );
  /* #575: (@36[2] += @62) */
  for (rr=w36+2, cs=(&w62); rr!=w36+3; rr+=1) *rr += *cs++;
  /* #576: @41 = (-@41) */
  w41 = (- w41 );
  /* #577: (@36[1] += @41) */
  for (rr=w36+1, cs=(&w41); rr!=w36+2; rr+=1) *rr += *cs++;
  /* #578: (@36[0] += @42) */
  for (rr=w36+0, cs=(&w42); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #579: (@49[10:14] = @36) */
  for (rr=w49+10, cs=w36; rr!=w49+14; rr+=1) *rr = *cs++;
  /* #580: (@49[7:23:4] = @36) */
  for (rr=w49+7, cs=w36; rr!=w49+23; rr+=4) *rr = *cs++;
  /* #581: @42 = ones(13x1,1nz) */
  w42 = 1.;
  /* #582: {NULL, NULL, @41, NULL} = vertsplit(@42) */
  w41 = w42;
  /* #583: @42 = @41[0] */
  for (rr=(&w42), cs=(&w41)+0; cs!=(&w41)+1; cs+=1) *rr++ = *cs;
  /* #584: @42 = (-@42) */
  w42 = (- w42 );
  /* #585: @62 = vertcat(@50, @50, @42, @50) */
  rr=(&w62);
  *rr++ = w42;
  /* #586: @62 = (@62/@11) */
  w62 /= w11;
  /* #587: @36 = dense(@62) */
  casadi_densify((&w62), casadi_s6, w36, 0);
  /* #588: @62 = project(@12) */
  casadi_sparsify(w12, (&w62), casadi_s6, 0);
  /* #589: @42 = dot(@62, @41) */
  w42 = casadi_dot(1, (&w62), (&w41));
  /* #590: @42 = (@42/@11) */
  w42 /= w11;
  /* #591: @51 = (@16*@42) */
  for (i=0, rr=w51, cr=w16; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #592: @36 = (@36-@51) */
  for (i=0, rr=w36, cs=w51; i<4; ++i) (*rr++) -= (*cs++);
  /* #593: @62 = @36[0] */
  for (rr=(&w62), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #594: @64 = (@14*@62) */
  w64  = (w14*w62);
  /* #595: @63 = @36[1] */
  for (rr=(&w63), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #596: @53 = (@18*@63) */
  w53  = (w18*w63);
  /* #597: @64 = (@64-@53) */
  w64 -= w53;
  /* #598: @53 = @36[2] */
  for (rr=(&w53), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #599: @44 = (@20*@53) */
  w44  = (w20*w53);
  /* #600: @64 = (@64-@44) */
  w64 -= w44;
  /* #601: @44 = @36[3] */
  for (rr=(&w44), cs=w36+3; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #602: @55 = (@22*@44) */
  w55  = (w22*w44);
  /* #603: @64 = (@64-@55) */
  w64 -= w55;
  /* #604: @55 = (@18*@62) */
  w55  = (w18*w62);
  /* #605: @52 = (@14*@63) */
  w52  = (w14*w63);
  /* #606: @55 = (@55+@52) */
  w55 += w52;
  /* #607: @52 = (@22*@53) */
  w52  = (w22*w53);
  /* #608: @55 = (@55+@52) */
  w55 += w52;
  /* #609: @52 = (@20*@44) */
  w52  = (w20*w44);
  /* #610: @55 = (@55-@52) */
  w55 -= w52;
  /* #611: @52 = (@20*@62) */
  w52  = (w20*w62);
  /* #612: @65 = (@22*@63) */
  w65  = (w22*w63);
  /* #613: @52 = (@52-@65) */
  w52 -= w65;
  /* #614: @65 = (@14*@53) */
  w65  = (w14*w53);
  /* #615: @52 = (@52+@65) */
  w52 += w65;
  /* #616: @65 = (@18*@44) */
  w65  = (w18*w44);
  /* #617: @52 = (@52+@65) */
  w52 += w65;
  /* #618: @62 = (@22*@62) */
  w62  = (w22*w62);
  /* #619: @63 = (@20*@63) */
  w63  = (w20*w63);
  /* #620: @62 = (@62+@63) */
  w62 += w63;
  /* #621: @53 = (@18*@53) */
  w53  = (w18*w53);
  /* #622: @62 = (@62-@53) */
  w62 -= w53;
  /* #623: @44 = (@14*@44) */
  w44  = (w14*w44);
  /* #624: @62 = (@62+@44) */
  w62 += w44;
  /* #625: @51 = vertcat(@64, @55, @52, @62) */
  rr=w51;
  *rr++ = w64;
  *rr++ = w55;
  *rr++ = w52;
  *rr++ = w62;
  /* #626: @60 = (-@51) */
  for (i=0, rr=w60, cs=w51; i<4; ++i) *rr++ = (- *cs++ );
  /* #627: @60 = (@23?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #628: @51 = (@15?@51:0) */
  for (i=0, rr=w51, cs=w51; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #629: @60 = (@60+@51) */
  for (i=0, rr=w60, cs=w51; i<4; ++i) (*rr++) += (*cs++);
  /* #630: @35 = @60[1:4] */
  for (rr=w35, cs=w60+1; cs!=w60+4; cs+=1) *rr++ = *cs;
  /* #631: @64 = dot(@2, @35) */
  w64 = casadi_dot(3, w02, w35);
  /* #632: @55 = dot(@35, @2) */
  w55 = casadi_dot(3, w35, w02);
  /* #633: @64 = (@64+@55) */
  w64 += w55;
  /* #634: @55 = (@64/@26) */
  w55  = (w64/w26);
  /* #635: @52 = (@55/@24) */
  w52  = (w55/w24);
  /* #636: @62 = @60[0] */
  for (rr=(&w62), cs=w60+0; cs!=w60+1; cs+=1) *rr++ = *cs;
  /* #637: @44 = (@13*@62) */
  w44  = (w13*w62);
  /* #638: @64 = (@64+@44) */
  w64 += w44;
  /* #639: @44 = (@43*@64) */
  w44  = (w43*w64);
  /* #640: @52 = (@52-@44) */
  w52 -= w44;
  /* #641: @52 = (@0*@52) */
  w52  = (w00*w52);
  /* #642: @37 = (2.*@35) */
  for (i=0, rr=w37, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #643: @10 = (@21*@37) */
  for (i=0, rr=w10, cs=w37; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #644: @44 = (@17*@55) */
  w44  = (w17*w55);
  /* #645: @53 = (@7*@62) */
  w53  = (w07*w62);
  /* #646: @44 = (@44-@53) */
  w44 -= w53;
  /* #647: @38 = (@29*@44) */
  for (i=0, rr=w38, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #648: @10 = (@10+@38) */
  for (i=0, rr=w10, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #649: @10 = (@10/@25) */
  for (i=0, rr=w10; i<3; ++i) (*rr++) /= w25;
  /* #650: @38 = (@30*@55) */
  for (i=0, rr=w38, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #651: @10 = (@10-@38) */
  for (i=0, rr=w10, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #652: @38 = @10' */
  casadi_copy(w10, 3, w38);
  /* #653: @5 = mac(@38,@32,@1) */
  casadi_copy(w01, 3, w05);
  casadi_mtimes(w38, casadi_s0, wr32, casadi_s1, w05, casadi_s0, w, 0);
  /* #654: @5 = @5' */
  /* #655: @9 = mac(@38,@4,@1) */
  casadi_copy(w01, 3, w09);
  casadi_mtimes(w38, casadi_s0, w04, casadi_s1, w09, casadi_s0, w, 0);
  /* #656: @9 = @9' */
  /* #657: @5 = (@5+@9) */
  for (i=0, rr=w05, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #658: @9 = (@5/@25) */
  for (i=0, rr=w09, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #659: @38 = (@6*@55) */
  for (i=0, rr=w38, cr=w06; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #660: @9 = (@9-@38) */
  for (i=0, rr=w09, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #661: @53 = dot(@29, @9) */
  w53 = casadi_dot(3, w29, w09);
  /* #662: @63 = dot(@37, @8) */
  w63 = casadi_dot(3, w37, w08);
  /* #663: @53 = (@53+@63) */
  w53 += w63;
  /* #664: @63 = (@7*@53) */
  w63  = (w07*w53);
  /* #665: @52 = (@52+@63) */
  w52 += w63;
  /* #666: @52 = (-@52) */
  w52 = (- w52 );
  /* #667: @60 = @27; (@60[0] += @52) */
  casadi_copy(w27, 4, w60);
  for (rr=w60+0, cs=(&w52); rr!=w60+1; rr+=1) *rr += *cs++;
  /* #668: @52 = dot(@31, @5) */
  w52 = casadi_dot(3, w31, w05);
  /* #669: @10 = (@10/@25) */
  for (i=0, rr=w10; i<3; ++i) (*rr++) /= w25;
  /* #670: @5 = (@34*@55) */
  for (i=0, rr=w05, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #671: @10 = (@10-@5) */
  for (i=0, rr=w10, cs=w05; i<3; ++i) (*rr++) -= (*cs++);
  /* #672: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (- *cs++ );
  /* #673: @63 = dot(@10, @33) */
  w63 = casadi_dot(3, w10, w33);
  /* #674: @52 = (@52+@63) */
  w52 += w63;
  /* #675: @62 = (@62/@24) */
  w62 /= w24;
  /* #676: @64 = (@57*@64) */
  w64  = (w57*w64);
  /* #677: @62 = (@62-@64) */
  w62 -= w64;
  /* #678: @62 = (@0*@62) */
  w62  = (w00*w62);
  /* #679: @53 = (@17*@53) */
  w53  = (w17*w53);
  /* #680: @62 = (@62+@53) */
  w62 += w53;
  /* #681: @52 = (@52+@62) */
  w52 += w62;
  /* #682: @52 = (@52/@26) */
  w52 /= w26;
  /* #683: @55 = (2.*@55) */
  w55 = (2.* w55 );
  /* #684: @55 = (@54*@55) */
  w55  = (w54*w55);
  /* #685: @52 = (@52-@55) */
  w52 -= w55;
  /* #686: @10 = (@2*@52) */
  for (i=0, rr=w10, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #687: @35 = (@19*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #688: @10 = (@10+@35) */
  for (i=0, rr=w10, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #689: @10 = (2.*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #690: @35 = (@8*@44) */
  for (i=0, rr=w35, cr=w08; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #691: @9 = (@21*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #692: @35 = (@35+@9) */
  for (i=0, rr=w35, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #693: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #694: @10 = (@10+@35) */
  for (i=0, rr=w10, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #695: (@60[1:4] += @10) */
  for (rr=w60+1, cs=w10; rr!=w60+4; rr+=1) *rr += *cs++;
  /* #696: @51 = (@15?@60:0) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #697: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #698: @60 = (@23?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #699: @51 = (@51+@60) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #700: {@44, @52, @55, @62} = vertsplit(@51) */
  w44 = w51[0];
  w52 = w51[1];
  w55 = w51[2];
  w62 = w51[3];
  /* #701: @53 = (@14*@62) */
  w53  = (w14*w62);
  /* #702: @51 = @27; (@51[3] += @53) */
  casadi_copy(w27, 4, w51);
  for (rr=w51+3, cs=(&w53); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #703: @53 = (@18*@62) */
  w53  = (w18*w62);
  /* #704: @53 = (-@53) */
  w53 = (- w53 );
  /* #705: (@51[2] += @53) */
  for (rr=w51+2, cs=(&w53); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #706: @53 = (@20*@62) */
  w53  = (w20*w62);
  /* #707: (@51[1] += @53) */
  for (rr=w51+1, cs=(&w53); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #708: @62 = (@22*@62) */
  w62  = (w22*w62);
  /* #709: (@51[0] += @62) */
  for (rr=w51+0, cs=(&w62); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #710: @62 = (@18*@55) */
  w62  = (w18*w55);
  /* #711: (@51[3] += @62) */
  for (rr=w51+3, cs=(&w62); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #712: @62 = (@14*@55) */
  w62  = (w14*w55);
  /* #713: (@51[2] += @62) */
  for (rr=w51+2, cs=(&w62); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #714: @62 = (@22*@55) */
  w62  = (w22*w55);
  /* #715: @62 = (-@62) */
  w62 = (- w62 );
  /* #716: (@51[1] += @62) */
  for (rr=w51+1, cs=(&w62); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #717: @55 = (@20*@55) */
  w55  = (w20*w55);
  /* #718: (@51[0] += @55) */
  for (rr=w51+0, cs=(&w55); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #719: @55 = (@20*@52) */
  w55  = (w20*w52);
  /* #720: @55 = (-@55) */
  w55 = (- w55 );
  /* #721: (@51[3] += @55) */
  for (rr=w51+3, cs=(&w55); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #722: @55 = (@22*@52) */
  w55  = (w22*w52);
  /* #723: (@51[2] += @55) */
  for (rr=w51+2, cs=(&w55); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #724: @55 = (@14*@52) */
  w55  = (w14*w52);
  /* #725: (@51[1] += @55) */
  for (rr=w51+1, cs=(&w55); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #726: @52 = (@18*@52) */
  w52  = (w18*w52);
  /* #727: (@51[0] += @52) */
  for (rr=w51+0, cs=(&w52); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #728: @52 = (@22*@44) */
  w52  = (w22*w44);
  /* #729: @52 = (-@52) */
  w52 = (- w52 );
  /* #730: (@51[3] += @52) */
  for (rr=w51+3, cs=(&w52); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #731: @52 = (@20*@44) */
  w52  = (w20*w44);
  /* #732: @52 = (-@52) */
  w52 = (- w52 );
  /* #733: (@51[2] += @52) */
  for (rr=w51+2, cs=(&w52); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #734: @52 = (@18*@44) */
  w52  = (w18*w44);
  /* #735: @52 = (-@52) */
  w52 = (- w52 );
  /* #736: (@51[1] += @52) */
  for (rr=w51+1, cs=(&w52); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #737: @44 = (@14*@44) */
  w44  = (w14*w44);
  /* #738: (@51[0] += @44) */
  for (rr=w51+0, cs=(&w44); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #739: @44 = dot(@28, @51) */
  w44 = casadi_dot(4, w28, w51);
  /* #740: @36 = (@36/@11) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w11;
  /* #741: @60 = (@58*@42) */
  for (i=0, rr=w60, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #742: @36 = (@36-@60) */
  for (i=0, rr=w36, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #743: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #744: @52 = dot(@36, @39) */
  w52 = casadi_dot(4, w36, w39);
  /* #745: @44 = (@44+@52) */
  w44 += w52;
  /* #746: @44 = (@44/@11) */
  w44 /= w11;
  /* #747: @52 = (@56*@42) */
  w52  = (w56*w42);
  /* #748: @44 = (@44-@52) */
  w44 -= w52;
  /* #749: @36 = (@12*@44) */
  for (i=0, rr=w36, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #750: @41 = (@40*@41) */
  w41  = (w40*w41);
  /* #751: @60 = dense(@41) */
  casadi_densify((&w41), casadi_s6, w60, 0);
  /* #752: @36 = (@36+@60) */
  for (i=0, rr=w36, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #753: @51 = (@51/@11) */
  for (i=0, rr=w51; i<4; ++i) (*rr++) /= w11;
  /* #754: @60 = (@45*@42) */
  for (i=0, rr=w60, cr=w45; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #755: @51 = (@51-@60) */
  for (i=0, rr=w51, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #756: {@42, @41, @44, @52} = vertsplit(@51) */
  w42 = w51[0];
  w41 = w51[1];
  w44 = w51[2];
  w52 = w51[3];
  /* #757: @52 = (-@52) */
  w52 = (- w52 );
  /* #758: (@36[3] += @52) */
  for (rr=w36+3, cs=(&w52); rr!=w36+4; rr+=1) *rr += *cs++;
  /* #759: @44 = (-@44) */
  w44 = (- w44 );
  /* #760: (@36[2] += @44) */
  for (rr=w36+2, cs=(&w44); rr!=w36+3; rr+=1) *rr += *cs++;
  /* #761: @41 = (-@41) */
  w41 = (- w41 );
  /* #762: (@36[1] += @41) */
  for (rr=w36+1, cs=(&w41); rr!=w36+2; rr+=1) *rr += *cs++;
  /* #763: (@36[0] += @42) */
  for (rr=w36+0, cs=(&w42); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #764: (@49[14:18] = @36) */
  for (rr=w49+14, cs=w36; rr!=w49+18; rr+=1) *rr = *cs++;
  /* #765: (@49[8:24:4] = @36) */
  for (rr=w49+8, cs=w36; rr!=w49+24; rr+=4) *rr = *cs++;
  /* #766: @42 = ones(13x1,1nz) */
  w42 = 1.;
  /* #767: {NULL, NULL, @41, NULL} = vertsplit(@42) */
  w41 = w42;
  /* #768: @42 = @41[0] */
  for (rr=(&w42), cs=(&w41)+0; cs!=(&w41)+1; cs+=1) *rr++ = *cs;
  /* #769: @42 = (-@42) */
  w42 = (- w42 );
  /* #770: @44 = vertcat(@50, @50, @50, @42) */
  rr=(&w44);
  *rr++ = w42;
  /* #771: @44 = (@44/@11) */
  w44 /= w11;
  /* #772: @36 = dense(@44) */
  casadi_densify((&w44), casadi_s7, w36, 0);
  /* #773: @44 = project(@12) */
  casadi_sparsify(w12, (&w44), casadi_s7, 0);
  /* #774: @42 = dot(@44, @41) */
  w42 = casadi_dot(1, (&w44), (&w41));
  /* #775: @42 = (@42/@11) */
  w42 /= w11;
  /* #776: @16 = (@16*@42) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) *= w42;
  /* #777: @36 = (@36-@16) */
  for (i=0, rr=w36, cs=w16; i<4; ++i) (*rr++) -= (*cs++);
  /* #778: @44 = @36[0] */
  for (rr=(&w44), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #779: @52 = (@14*@44) */
  w52  = (w14*w44);
  /* #780: @55 = @36[1] */
  for (rr=(&w55), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #781: @62 = (@18*@55) */
  w62  = (w18*w55);
  /* #782: @52 = (@52-@62) */
  w52 -= w62;
  /* #783: @62 = @36[2] */
  for (rr=(&w62), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #784: @53 = (@20*@62) */
  w53  = (w20*w62);
  /* #785: @52 = (@52-@53) */
  w52 -= w53;
  /* #786: @53 = @36[3] */
  for (rr=(&w53), cs=w36+3; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #787: @64 = (@22*@53) */
  w64  = (w22*w53);
  /* #788: @52 = (@52-@64) */
  w52 -= w64;
  /* #789: @64 = (@18*@44) */
  w64  = (w18*w44);
  /* #790: @63 = (@14*@55) */
  w63  = (w14*w55);
  /* #791: @64 = (@64+@63) */
  w64 += w63;
  /* #792: @63 = (@22*@62) */
  w63  = (w22*w62);
  /* #793: @64 = (@64+@63) */
  w64 += w63;
  /* #794: @63 = (@20*@53) */
  w63  = (w20*w53);
  /* #795: @64 = (@64-@63) */
  w64 -= w63;
  /* #796: @63 = (@20*@44) */
  w63  = (w20*w44);
  /* #797: @65 = (@22*@55) */
  w65  = (w22*w55);
  /* #798: @63 = (@63-@65) */
  w63 -= w65;
  /* #799: @65 = (@14*@62) */
  w65  = (w14*w62);
  /* #800: @63 = (@63+@65) */
  w63 += w65;
  /* #801: @65 = (@18*@53) */
  w65  = (w18*w53);
  /* #802: @63 = (@63+@65) */
  w63 += w65;
  /* #803: @44 = (@22*@44) */
  w44  = (w22*w44);
  /* #804: @55 = (@20*@55) */
  w55  = (w20*w55);
  /* #805: @44 = (@44+@55) */
  w44 += w55;
  /* #806: @62 = (@18*@62) */
  w62  = (w18*w62);
  /* #807: @44 = (@44-@62) */
  w44 -= w62;
  /* #808: @53 = (@14*@53) */
  w53  = (w14*w53);
  /* #809: @44 = (@44+@53) */
  w44 += w53;
  /* #810: @16 = vertcat(@52, @64, @63, @44) */
  rr=w16;
  *rr++ = w52;
  *rr++ = w64;
  *rr++ = w63;
  *rr++ = w44;
  /* #811: @51 = (-@16) */
  for (i=0, rr=w51, cs=w16; i<4; ++i) *rr++ = (- *cs++ );
  /* #812: @51 = (@23?@51:0) */
  for (i=0, rr=w51, cs=w51; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #813: @16 = (@15?@16:0) */
  for (i=0, rr=w16, cs=w16; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #814: @51 = (@51+@16) */
  for (i=0, rr=w51, cs=w16; i<4; ++i) (*rr++) += (*cs++);
  /* #815: @10 = @51[1:4] */
  for (rr=w10, cs=w51+1; cs!=w51+4; cs+=1) *rr++ = *cs;
  /* #816: @52 = dot(@2, @10) */
  w52 = casadi_dot(3, w02, w10);
  /* #817: @64 = dot(@10, @2) */
  w64 = casadi_dot(3, w10, w02);
  /* #818: @52 = (@52+@64) */
  w52 += w64;
  /* #819: @64 = (@52/@26) */
  w64  = (w52/w26);
  /* #820: @63 = (@64/@24) */
  w63  = (w64/w24);
  /* #821: @44 = @51[0] */
  for (rr=(&w44), cs=w51+0; cs!=w51+1; cs+=1) *rr++ = *cs;
  /* #822: @13 = (@13*@44) */
  w13 *= w44;
  /* #823: @52 = (@52+@13) */
  w52 += w13;
  /* #824: @43 = (@43*@52) */
  w43 *= w52;
  /* #825: @63 = (@63-@43) */
  w63 -= w43;
  /* #826: @63 = (@0*@63) */
  w63  = (w00*w63);
  /* #827: @35 = (2.*@10) */
  for (i=0, rr=w35, cs=w10; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #828: @9 = (@21*@35) */
  for (i=0, rr=w09, cs=w35; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #829: @43 = (@17*@64) */
  w43  = (w17*w64);
  /* #830: @13 = (@7*@44) */
  w13  = (w07*w44);
  /* #831: @43 = (@43-@13) */
  w43 -= w13;
  /* #832: @5 = (@29*@43) */
  for (i=0, rr=w05, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #833: @9 = (@9+@5) */
  for (i=0, rr=w09, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #834: @9 = (@9/@25) */
  for (i=0, rr=w09; i<3; ++i) (*rr++) /= w25;
  /* #835: @30 = (@30*@64) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) *= w64;
  /* #836: @9 = (@9-@30) */
  for (i=0, rr=w09, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #837: @30 = @9' */
  casadi_copy(w09, 3, w30);
  /* #838: @5 = mac(@30,@32,@1) */
  casadi_copy(w01, 3, w05);
  casadi_mtimes(w30, casadi_s0, wr32, casadi_s1, w05, casadi_s0, w, 0);
  /* #839: @5 = @5' */
  /* #840: @1 = mac(@30,@4,@1) */
  casadi_mtimes(w30, casadi_s0, w04, casadi_s1, w01, casadi_s0, w, 0);
  /* #841: @1 = @1' */
  /* #842: @5 = (@5+@1) */
  for (i=0, rr=w05, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #843: @1 = (@5/@25) */
  for (i=0, rr=w01, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)/w25);
  /* #844: @6 = (@6*@64) */
  for (i=0, rr=w06; i<3; ++i) (*rr++) *= w64;
  /* #845: @1 = (@1-@6) */
  for (i=0, rr=w01, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #846: @13 = dot(@29, @1) */
  w13 = casadi_dot(3, w29, w01);
  /* #847: @53 = dot(@35, @8) */
  w53 = casadi_dot(3, w35, w08);
  /* #848: @13 = (@13+@53) */
  w13 += w53;
  /* #849: @7 = (@7*@13) */
  w07 *= w13;
  /* #850: @63 = (@63+@7) */
  w63 += w07;
  /* #851: @63 = (-@63) */
  w63 = (- w63 );
  /* #852: @51 = @27; (@51[0] += @63) */
  casadi_copy(w27, 4, w51);
  for (rr=w51+0, cs=(&w63); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #853: @63 = dot(@31, @5) */
  w63 = casadi_dot(3, w31, w05);
  /* #854: @9 = (@9/@25) */
  for (i=0, rr=w09; i<3; ++i) (*rr++) /= w25;
  /* #855: @34 = (@34*@64) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) *= w64;
  /* #856: @9 = (@9-@34) */
  for (i=0, rr=w09, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #857: @9 = (-@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) *rr++ = (- *cs++ );
  /* #858: @25 = dot(@9, @33) */
  w25 = casadi_dot(3, w09, w33);
  /* #859: @63 = (@63+@25) */
  w63 += w25;
  /* #860: @44 = (@44/@24) */
  w44 /= w24;
  /* #861: @57 = (@57*@52) */
  w57 *= w52;
  /* #862: @44 = (@44-@57) */
  w44 -= w57;
  /* #863: @0 = (@0*@44) */
  w00 *= w44;
  /* #864: @17 = (@17*@13) */
  w17 *= w13;
  /* #865: @0 = (@0+@17) */
  w00 += w17;
  /* #866: @63 = (@63+@0) */
  w63 += w00;
  /* #867: @63 = (@63/@26) */
  w63 /= w26;
  /* #868: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #869: @54 = (@54*@64) */
  w54 *= w64;
  /* #870: @63 = (@63-@54) */
  w63 -= w54;
  /* #871: @2 = (@2*@63) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w63;
  /* #872: @10 = (@19*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #873: @2 = (@2+@10) */
  for (i=0, rr=w02, cs=w10; i<3; ++i) (*rr++) += (*cs++);
  /* #874: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #875: @8 = (@8*@43) */
  for (i=0, rr=w08; i<3; ++i) (*rr++) *= w43;
  /* #876: @1 = (@21*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #877: @8 = (@8+@1) */
  for (i=0, rr=w08, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #878: @8 = (2.*@8) */
  for (i=0, rr=w08, cs=w08; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #879: @2 = (@2+@8) */
  for (i=0, rr=w02, cs=w08; i<3; ++i) (*rr++) += (*cs++);
  /* #880: (@51[1:4] += @2) */
  for (rr=w51+1, cs=w02; rr!=w51+4; rr+=1) *rr += *cs++;
  /* #881: @16 = (@15?@51:0) */
  for (i=0, rr=w16, cs=w51; i<4; ++i) (*rr++)  = (w15?cs[i]:0);
  /* #882: @51 = (-@51) */
  for (i=0, rr=w51, cs=w51; i<4; ++i) *rr++ = (- *cs++ );
  /* #883: @51 = (@23?@51:0) */
  for (i=0, rr=w51, cs=w51; i<4; ++i) (*rr++)  = (w23?cs[i]:0);
  /* #884: @16 = (@16+@51) */
  for (i=0, rr=w16, cs=w51; i<4; ++i) (*rr++) += (*cs++);
  /* #885: {@23, @15, @21, @43} = vertsplit(@16) */
  w23 = w16[0];
  w15 = w16[1];
  w21 = w16[2];
  w43 = w16[3];
  /* #886: @19 = (@14*@43) */
  w19  = (w14*w43);
  /* #887: (@27[3] += @19) */
  for (rr=w27+3, cs=(&w19); rr!=w27+4; rr+=1) *rr += *cs++;
  /* #888: @19 = (@18*@43) */
  w19  = (w18*w43);
  /* #889: @19 = (-@19) */
  w19 = (- w19 );
  /* #890: (@27[2] += @19) */
  for (rr=w27+2, cs=(&w19); rr!=w27+3; rr+=1) *rr += *cs++;
  /* #891: @19 = (@20*@43) */
  w19  = (w20*w43);
  /* #892: (@27[1] += @19) */
  for (rr=w27+1, cs=(&w19); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #893: @43 = (@22*@43) */
  w43  = (w22*w43);
  /* #894: (@27[0] += @43) */
  for (rr=w27+0, cs=(&w43); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #895: @43 = (@18*@21) */
  w43  = (w18*w21);
  /* #896: (@27[3] += @43) */
  for (rr=w27+3, cs=(&w43); rr!=w27+4; rr+=1) *rr += *cs++;
  /* #897: @43 = (@14*@21) */
  w43  = (w14*w21);
  /* #898: (@27[2] += @43) */
  for (rr=w27+2, cs=(&w43); rr!=w27+3; rr+=1) *rr += *cs++;
  /* #899: @43 = (@22*@21) */
  w43  = (w22*w21);
  /* #900: @43 = (-@43) */
  w43 = (- w43 );
  /* #901: (@27[1] += @43) */
  for (rr=w27+1, cs=(&w43); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #902: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #903: (@27[0] += @21) */
  for (rr=w27+0, cs=(&w21); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #904: @21 = (@20*@15) */
  w21  = (w20*w15);
  /* #905: @21 = (-@21) */
  w21 = (- w21 );
  /* #906: (@27[3] += @21) */
  for (rr=w27+3, cs=(&w21); rr!=w27+4; rr+=1) *rr += *cs++;
  /* #907: @21 = (@22*@15) */
  w21  = (w22*w15);
  /* #908: (@27[2] += @21) */
  for (rr=w27+2, cs=(&w21); rr!=w27+3; rr+=1) *rr += *cs++;
  /* #909: @21 = (@14*@15) */
  w21  = (w14*w15);
  /* #910: (@27[1] += @21) */
  for (rr=w27+1, cs=(&w21); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #911: @15 = (@18*@15) */
  w15  = (w18*w15);
  /* #912: (@27[0] += @15) */
  for (rr=w27+0, cs=(&w15); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #913: @22 = (@22*@23) */
  w22 *= w23;
  /* #914: @22 = (-@22) */
  w22 = (- w22 );
  /* #915: (@27[3] += @22) */
  for (rr=w27+3, cs=(&w22); rr!=w27+4; rr+=1) *rr += *cs++;
  /* #916: @20 = (@20*@23) */
  w20 *= w23;
  /* #917: @20 = (-@20) */
  w20 = (- w20 );
  /* #918: (@27[2] += @20) */
  for (rr=w27+2, cs=(&w20); rr!=w27+3; rr+=1) *rr += *cs++;
  /* #919: @18 = (@18*@23) */
  w18 *= w23;
  /* #920: @18 = (-@18) */
  w18 = (- w18 );
  /* #921: (@27[1] += @18) */
  for (rr=w27+1, cs=(&w18); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #922: @14 = (@14*@23) */
  w14 *= w23;
  /* #923: (@27[0] += @14) */
  for (rr=w27+0, cs=(&w14); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #924: @14 = dot(@28, @27) */
  w14 = casadi_dot(4, w28, w27);
  /* #925: @36 = (@36/@11) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w11;
  /* #926: @58 = (@58*@42) */
  for (i=0, rr=w58; i<4; ++i) (*rr++) *= w42;
  /* #927: @36 = (@36-@58) */
  for (i=0, rr=w36, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #928: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #929: @23 = dot(@36, @39) */
  w23 = casadi_dot(4, w36, w39);
  /* #930: @14 = (@14+@23) */
  w14 += w23;
  /* #931: @14 = (@14/@11) */
  w14 /= w11;
  /* #932: @56 = (@56*@42) */
  w56 *= w42;
  /* #933: @14 = (@14-@56) */
  w14 -= w56;
  /* #934: @12 = (@12*@14) */
  for (i=0, rr=w12; i<4; ++i) (*rr++) *= w14;
  /* #935: @40 = (@40*@41) */
  w40 *= w41;
  /* #936: @36 = dense(@40) */
  casadi_densify((&w40), casadi_s7, w36, 0);
  /* #937: @12 = (@12+@36) */
  for (i=0, rr=w12, cs=w36; i<4; ++i) (*rr++) += (*cs++);
  /* #938: @27 = (@27/@11) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w11;
  /* #939: @45 = (@45*@42) */
  for (i=0, rr=w45; i<4; ++i) (*rr++) *= w42;
  /* #940: @27 = (@27-@45) */
  for (i=0, rr=w27, cs=w45; i<4; ++i) (*rr++) -= (*cs++);
  /* #941: {@42, @11, @40, @41} = vertsplit(@27) */
  w42 = w27[0];
  w11 = w27[1];
  w40 = w27[2];
  w41 = w27[3];
  /* #942: @41 = (-@41) */
  w41 = (- w41 );
  /* #943: (@12[3] += @41) */
  for (rr=w12+3, cs=(&w41); rr!=w12+4; rr+=1) *rr += *cs++;
  /* #944: @40 = (-@40) */
  w40 = (- w40 );
  /* #945: (@12[2] += @40) */
  for (rr=w12+2, cs=(&w40); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #946: @11 = (-@11) */
  w11 = (- w11 );
  /* #947: (@12[1] += @11) */
  for (rr=w12+1, cs=(&w11); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #948: (@12[0] += @42) */
  for (rr=w12+0, cs=(&w42); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #949: (@49[18:22] = @12) */
  for (rr=w49+18, cs=w12; rr!=w49+22; rr+=1) *rr = *cs++;
  /* #950: (@49[9:25:4] = @12) */
  for (rr=w49+9, cs=w12; rr!=w49+25; rr+=4) *rr = *cs++;
  /* #951: @66 = @49' */
  casadi_trans(w49,casadi_s8, w66, casadi_s8, iw);
  /* #952: output[2][0] = @66 */
  casadi_copy(w66, 22, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s10;
    case 3: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s9;
    case 2: return casadi_s8;
    case 3: return casadi_s13;
    case 4: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 226;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 226*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
