/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[13] = 
  {12, 1, 0, 9, 3, 4, 5, 6,
  7, 8, 9, 10, 11};
static const casadi_int casadi_s1[24] = 
  {12, 12, 0, 0, 0, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 3,
  4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[3] = {9, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[3] = {33, 1, 1};
static const casadi_int casadi_s6[3] = {1, 1, 1};
static const casadi_int casadi_s7[3] = {12, 1, 1};
static const casadi_int casadi_s8[3] = {0, 0, 1};
static const casadi_int casadi_s9[3] = {0, 12, 1};

static const casadi_real casadi_zeros[33] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess:(i0[9],i1[3],i2[0],i3[33])->(o0,o1[12],o2[12x12,9nz],o3[],o4[0x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w01, *w02=w+34, *w03=w+37, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w24=w+59;
  casadi_real *w25=w+62, *w26=w+65, *w27=w+74, *w28=w+86, *w29=w+89, *w30=w+98;
  const casadi_real *cs, *wr00, *wr03;
  /* #0: @0 = input[3][0] */
  wr00 = arg[3] ? arg[3] : casadi_zeros;
  /* #1: @1 = @0[19] */
  w01 = wr00[19];
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = @0[10:13] */
  wr03 = wr00+10;
  /* #4: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=wr03; i<3; ++i) (*rr++) -= (*cs++);
  /* #5: @4 = @2[0] */
  for (rr=(&w04), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #6: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #7: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #8: @6 = @0[20] */
  w06 = wr00[20];
  /* #9: @7 = @2[1] */
  for (rr=(&w07), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #10: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #11: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #12: @5 = (@5+@8) */
  w05 += w08;
  /* #13: @8 = @0[21] */
  w08 = wr00[21];
  /* #14: @9 = @2[2] */
  for (rr=(&w09), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #15: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #16: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #17: @5 = (@5+@10) */
  w05 += w10;
  /* #18: @10 = @0[22] */
  w10 = wr00[22];
  /* #19: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #20: @3 = @0[13:16] */
  wr03 = wr00+13;
  /* #21: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=wr03; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: @11 = @2[0] */
  for (rr=(&w11), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #23: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #24: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #25: @5 = (@5+@12) */
  w05 += w12;
  /* #26: @12 = @0[23] */
  w12 = wr00[23];
  /* #27: @13 = @2[1] */
  for (rr=(&w13), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #28: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #29: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #30: @5 = (@5+@14) */
  w05 += w14;
  /* #31: @14 = @0[24] */
  w14 = wr00[24];
  /* #32: @15 = @2[2] */
  for (rr=(&w15), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #33: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #34: @16 = (@14*@16) */
  w16  = (w14*w16);
  /* #35: @5 = (@5+@16) */
  w05 += w16;
  /* #36: @16 = @0[25] */
  w16 = wr00[25];
  /* #37: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 3, w02);
  /* #38: @3 = @0[16:19] */
  wr03 = wr00+16;
  /* #39: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=wr03; i<3; ++i) (*rr++) -= (*cs++);
  /* #40: @17 = @2[0] */
  for (rr=(&w17), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #41: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #42: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #43: @5 = (@5+@18) */
  w05 += w18;
  /* #44: @18 = @0[26] */
  w18 = wr00[26];
  /* #45: @19 = @2[1] */
  for (rr=(&w19), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #46: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #47: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #48: @5 = (@5+@20) */
  w05 += w20;
  /* #49: @20 = @0[27] */
  w20 = wr00[27];
  /* #50: @21 = @2[2] */
  for (rr=(&w21), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #51: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #52: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #53: @5 = (@5+@22) */
  w05 += w22;
  /* #54: output[0][0] = @5 */
  if (res[0]) res[0][0] = w05;
  /* #55: @23 = zeros(3x1,0nz) */
  /* #56: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #57: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #58: @9 = (@9*@8) */
  w09 *= w08;
  /* #59: @3 = @2; (@3[2] += @9) */
  casadi_copy(w02, 3, w03);
  for (rr=w03+2, cs=(&w09); rr!=w03+3; rr+=1) *rr += *cs++;
  /* #60: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #61: @7 = (@7*@6) */
  w07 *= w06;
  /* #62: (@3[1] += @7) */
  for (rr=w03+1, cs=(&w07); rr!=w03+2; rr+=1) *rr += *cs++;
  /* #63: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #64: @4 = (@4*@1) */
  w04 *= w01;
  /* #65: (@3[0] += @4) */
  for (rr=w03+0, cs=(&w04); rr!=w03+1; rr+=1) *rr += *cs++;
  /* #66: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #67: @15 = (@15*@14) */
  w15 *= w14;
  /* #68: @24 = @2; (@24[2] += @15) */
  casadi_copy(w02, 3, w24);
  for (rr=w24+2, cs=(&w15); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #69: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #70: @13 = (@13*@12) */
  w13 *= w12;
  /* #71: (@24[1] += @13) */
  for (rr=w24+1, cs=(&w13); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #72: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #73: @11 = (@11*@10) */
  w11 *= w10;
  /* #74: (@24[0] += @11) */
  for (rr=w24+0, cs=(&w11); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #75: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #76: @21 = (@21*@20) */
  w21 *= w20;
  /* #77: @25 = @2; (@25[2] += @21) */
  casadi_copy(w02, 3, w25);
  for (rr=w25+2, cs=(&w21); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #78: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #79: @19 = (@19*@18) */
  w19 *= w18;
  /* #80: (@25[1] += @19) */
  for (rr=w25+1, cs=(&w19); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #81: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #82: @17 = (@17*@16) */
  w17 *= w16;
  /* #83: (@25[0] += @17) */
  for (rr=w25+0, cs=(&w17); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #84: @26 = vertcat(@23, @3, @24, @25) */
  rr=w26;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #85: @27 = dense(@26) */
  casadi_densify(w26, casadi_s0, w27, 0);
  /* #86: output[1][0] = @27 */
  casadi_copy(w27, 12, res[1]);
  /* #87: @26 = zeros(12x12,9nz) */
  casadi_clear(w26, 9);
  /* #88: @27 = ones(12x1) */
  casadi_fill(w27, 12, 1.);
  /* #89: {NULL, @3, @24, @25} = vertsplit(@27) */
  casadi_copy(w27+3, 3, w03);
  casadi_copy(w27+6, 3, w24);
  casadi_copy(w27+9, 3, w25);
  /* #90: @17 = @3[2] */
  for (rr=(&w17), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #91: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #92: @8 = (@8*@17) */
  w08 *= w17;
  /* #93: @28 = @2; (@28[2] += @8) */
  casadi_copy(w02, 3, w28);
  for (rr=w28+2, cs=(&w08); rr!=w28+3; rr+=1) *rr += *cs++;
  /* #94: @8 = @3[1] */
  for (rr=(&w08), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #95: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #96: @6 = (@6*@8) */
  w06 *= w08;
  /* #97: (@28[1] += @6) */
  for (rr=w28+1, cs=(&w06); rr!=w28+2; rr+=1) *rr += *cs++;
  /* #98: @6 = @3[0] */
  for (rr=(&w06), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #99: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #100: @1 = (@1*@6) */
  w01 *= w06;
  /* #101: (@28[0] += @1) */
  for (rr=w28+0, cs=(&w01); rr!=w28+1; rr+=1) *rr += *cs++;
  /* #102: @1 = @24[2] */
  for (rr=(&w01), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #103: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #104: @14 = (@14*@1) */
  w14 *= w01;
  /* #105: @3 = @2; (@3[2] += @14) */
  casadi_copy(w02, 3, w03);
  for (rr=w03+2, cs=(&w14); rr!=w03+3; rr+=1) *rr += *cs++;
  /* #106: @14 = @24[1] */
  for (rr=(&w14), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #107: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #108: @12 = (@12*@14) */
  w12 *= w14;
  /* #109: (@3[1] += @12) */
  for (rr=w03+1, cs=(&w12); rr!=w03+2; rr+=1) *rr += *cs++;
  /* #110: @12 = @24[0] */
  for (rr=(&w12), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #111: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #112: @10 = (@10*@12) */
  w10 *= w12;
  /* #113: (@3[0] += @10) */
  for (rr=w03+0, cs=(&w10); rr!=w03+1; rr+=1) *rr += *cs++;
  /* #114: @10 = @25[2] */
  for (rr=(&w10), cs=w25+2; cs!=w25+3; cs+=1) *rr++ = *cs;
  /* #115: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #116: @20 = (@20*@10) */
  w20 *= w10;
  /* #117: (@2[2] += @20) */
  for (rr=w02+2, cs=(&w20); rr!=w02+3; rr+=1) *rr += *cs++;
  /* #118: @20 = @25[1] */
  for (rr=(&w20), cs=w25+1; cs!=w25+2; cs+=1) *rr++ = *cs;
  /* #119: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #120: @18 = (@18*@20) */
  w18 *= w20;
  /* #121: (@2[1] += @18) */
  for (rr=w02+1, cs=(&w18); rr!=w02+2; rr+=1) *rr += *cs++;
  /* #122: @18 = @25[0] */
  for (rr=(&w18), cs=w25+0; cs!=w25+1; cs+=1) *rr++ = *cs;
  /* #123: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #124: @16 = (@16*@18) */
  w16 *= w18;
  /* #125: (@2[0] += @16) */
  for (rr=w02+0, cs=(&w16); rr!=w02+1; rr+=1) *rr += *cs++;
  /* #126: @29 = vertcat(@23, @28, @3, @2) */
  rr=w29;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  /* #127: @30 = @29[:9] */
  for (rr=w30, cs=w29+0; cs!=w29+9; cs+=1) *rr++ = *cs;
  /* #128: (@26[:9] = @30) */
  for (rr=w26+0, cs=w30; rr!=w26+9; rr+=1) *rr = *cs++;
  /* #129: (@26[:9] = @30) */
  for (rr=w26+0, cs=w30; rr!=w26+9; rr+=1) *rr = *cs++;
  /* #130: @30 = @26' */
  casadi_trans(w26,casadi_s1, w30, casadi_s1, iw);
  /* #131: output[2][0] = @30 */
  casadi_copy(w30, 9, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 107;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_d_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 107*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
