/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {34, 1, 1};
static const casadi_int casadi_s3[15] = 
  {14, 1, 0, 11, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_mhe_trans_expl_vde_adj:(i0[10],i1[10],i2[4],i3[34])->(o0[14x1,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w01, *w02=w+35, *w03=w+38, w07, *w09=w+61, w10, w11, w12;
  const casadi_real *cs, *wr00, *wr02, *wr04, *wr05, *wr06, *wr08;
  /* #0: @0 = input[3][0] */
  wr00 = arg[3] ? arg[3] : casadi_zeros;
  /* #1: @1 = @0[30] */
  w01 = wr00[30];
  /* #2: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #3: @3 = (@1*@2) */
  for (i=0, rr=w03, cs=w02; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #4: @4 = input[1][0] */
  wr04 = arg[1] ? arg[1] : casadi_zeros;
  /* #5: {@5, @6, @7, @8} = vertsplit(@4) */
  wr05 = wr04;
  wr06 = wr04+3;
  w07 = wr04[6];
  wr08 = wr04+7;
  /* #6: @9 = (-@6) */
  for (i=0, rr=w09, cs=wr06; i<3; ++i) *rr++ = (- *cs++ );
  /* #7: @10 = dot(@3, @9) */
  w10 = casadi_dot(3, w03, w09);
  /* #8: @11 = 1e-06 */
  w11 = 9.9999999999999995e-07;
  /* #9: @12 = dot(@2, @2) */
  w12 = casadi_dot(3, w02, w02);
  /* #10: @11 = (@11+@12) */
  w11 += w12;
  /* #11: @11 = sqrt(@11) */
  w11 = sqrt( w11 );
  /* #12: @12 = (2.*@11) */
  w12 = (2.* w11 );
  /* #13: @10 = (@10/@12) */
  w10 /= w12;
  /* #14: @2 = (@10*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #15: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #16: @3 = (@11*@6) */
  for (i=0, rr=w03, cs=wr06; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #17: @3 = (@1*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #18: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=w03; i<3; ++i) (*rr++) -= (*cs++);
  /* #19: @2 = (@2+@5) */
  for (i=0, rr=w02, cs=wr05; i<3; ++i) (*rr++) += (*cs++);
  /* #20: output[0][0] = @2 */
  casadi_copy(w02, 3, res[0]);
  /* #21: @1 = @0[6] */
  w01 = wr00[6];
  /* #22: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #23: @1 = (@1/@11) */
  w01 /= w11;
  /* #24: @1 = (@1/@11) */
  w01 /= w11;
  /* #25: @2 = @0[7:10] */
  wr02 = wr00+7;
  /* #26: @11 = dot(@2, @6) */
  w11 = casadi_dot(3, wr02, wr06);
  /* #27: @1 = (@1*@11) */
  w01 *= w11;
  /* #28: @1 = (-@1) */
  w01 = (- w01 );
  /* #29: output[0][1] = @1 */
  if (res[0]) res[0][3] = w01;
  /* #30: output[0][2] = @6 */
  if (res[0]) casadi_copy(wr06, 3, res[0]+4);
  /* #31: output[0][3] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #32: output[0][4] = @8 */
  if (res[0]) casadi_copy(wr08, 3, res[0]+8);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 67;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 67*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
