/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[37] = 
  {1, 17, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0};
static const casadi_int casadi_s1[37] = 
  {17, 17, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15, 16};
static const casadi_int casadi_s2[22] = 
  {23, 1, 0, 18, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 20, 21, 22};
static const casadi_int casadi_s3[3] = {18, 1, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {0, 1, 1};
static const casadi_int casadi_s6[3] = {52, 1, 1};
static const casadi_int casadi_s7[3] = {1, 1, 1};
static const casadi_int casadi_s8[3] = {23, 1, 1};

static const casadi_real casadi_zeros[52] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac:(i0[18],i1[5],i2[0],i3[52])->(o0,o1[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+19, *w04=w+74, *w05=w+77, w06, w07, w08, w09, *w10=w+84, *w11=w+88;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+102, *w23=w+105;
  casadi_real *w24=w+108, *w25=w+111, *w26=w+114, *w27=w+117, *w28=w+134, *w30=w+168, *w33=w+185, *w34=w+188, *w35=w+192, *w36=w+210;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr11, *wr25, *wr26, *wr29;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w01, 17);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[17:20] */
  wr04 = wr03+17;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w04);
  /* #7: @5 = @3[20:23] */
  wr05 = wr03+20;
  /* #8: @4 = (@4-@5) */
  for (i=0, rr=w04, cs=wr05; i<3; ++i) (*rr++) -= (*cs++);
  /* #9: @6 = @3[23] */
  w06 = wr03[23];
  /* #10: @7 = @3[24] */
  w07 = wr03[24];
  /* #11: @7 = (-@7) */
  w07 = (- w07 );
  /* #12: @8 = @3[25] */
  w08 = wr03[25];
  /* #13: @8 = (-@8) */
  w08 = (- w08 );
  /* #14: @9 = @3[26] */
  w09 = wr03[26];
  /* #15: @9 = (-@9) */
  w09 = (- w09 );
  /* #16: @10 = vertcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #17: @6 = 1e-12 */
  w06 = 9.9999999999999998e-13;
  /* #18: @11 = @3[23:27] */
  wr11 = wr03+23;
  /* #19: @7 = ||@11||_F */
  w07 = casadi_norm_2(4, wr11);
  /* #20: @7 = (@6+@7) */
  w07  = (w06+w07);
  /* #21: @10 = (@10/@7) */
  for (i=0, rr=w10; i<4; ++i) (*rr++) /= w07;
  /* #22: @7 = @10[0] */
  for (rr=(&w07), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #23: @11 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w11);
  /* #24: @8 = @11[0] */
  for (rr=(&w08), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #25: @9 = (@7*@8) */
  w09  = (w07*w08);
  /* #26: @12 = @10[1] */
  for (rr=(&w12), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #27: @13 = @11[1] */
  for (rr=(&w13), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #28: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #29: @9 = (@9-@14) */
  w09 -= w14;
  /* #30: @14 = @10[2] */
  for (rr=(&w14), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #31: @15 = @11[2] */
  for (rr=(&w15), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #32: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #33: @9 = (@9-@16) */
  w09 -= w16;
  /* #34: @16 = @10[3] */
  for (rr=(&w16), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #35: @17 = @11[3] */
  for (rr=(&w17), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #36: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #37: @9 = (@9-@18) */
  w09 -= w18;
  /* #38: @18 = (@9<@0) */
  w18  = (w09<w00);
  /* #39: @19 = (@7*@13) */
  w19  = (w07*w13);
  /* #40: @20 = (@12*@8) */
  w20  = (w12*w08);
  /* #41: @19 = (@19+@20) */
  w19 += w20;
  /* #42: @20 = (@14*@17) */
  w20  = (w14*w17);
  /* #43: @19 = (@19+@20) */
  w19 += w20;
  /* #44: @20 = (@16*@15) */
  w20  = (w16*w15);
  /* #45: @19 = (@19-@20) */
  w19 -= w20;
  /* #46: @20 = (@7*@15) */
  w20  = (w07*w15);
  /* #47: @21 = (@12*@17) */
  w21  = (w12*w17);
  /* #48: @20 = (@20-@21) */
  w20 -= w21;
  /* #49: @21 = (@14*@8) */
  w21  = (w14*w08);
  /* #50: @20 = (@20+@21) */
  w20 += w21;
  /* #51: @21 = (@16*@13) */
  w21  = (w16*w13);
  /* #52: @20 = (@20+@21) */
  w20 += w21;
  /* #53: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #54: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #55: @17 = (@17+@15) */
  w17 += w15;
  /* #56: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #57: @17 = (@17-@13) */
  w17 -= w13;
  /* #58: @8 = (@16*@8) */
  w08  = (w16*w08);
  /* #59: @17 = (@17+@8) */
  w17 += w08;
  /* #60: @11 = vertcat(@9, @19, @20, @17) */
  rr=w11;
  *rr++ = w09;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w17;
  /* #61: @10 = (-@11) */
  for (i=0, rr=w10, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #62: @10 = (@18?@10:0) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w18?cs[i]:0);
  /* #63: @9 = (!@18) */
  w09 = (! w18 );
  /* #64: @11 = (@9?@11:0) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w09?cs[i]:0);
  /* #65: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #66: @5 = @10[1:4] */
  for (rr=w05, cs=w10+1; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #67: @22 = (2.*@5) */
  for (i=0, rr=w22, cs=w05; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #68: @19 = dot(@5, @5) */
  w19 = casadi_dot(3, w05, w05);
  /* #69: @6 = (@6+@19) */
  w06 += w19;
  /* #70: @19 = sqrt(@6) */
  w19 = sqrt( w06 );
  /* #71: @20 = @10[0] */
  for (rr=(&w20), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #72: @17 = atan2(@19,@20) */
  w17  = atan2(w19,w20);
  /* #73: @23 = (@22*@17) */
  for (i=0, rr=w23, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #74: @23 = (@23/@19) */
  for (i=0, rr=w23; i<3; ++i) (*rr++) /= w19;
  /* #75: @24 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w24);
  /* #76: @25 = @3[27:30] */
  wr25 = wr03+27;
  /* #77: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=wr25; i<3; ++i) (*rr++) -= (*cs++);
  /* #78: @8 = input[0][4] */
  w08 = arg[0] ? arg[0][13] : 0;
  /* #79: @13 = @3[30] */
  w13 = wr03[30];
  /* #80: @8 = (@8-@13) */
  w08 -= w13;
  /* #81: @13 = input[0][5] */
  w13 = arg[0] ? arg[0][14] : 0;
  /* #82: @15 = @3[31] */
  w15 = wr03[31];
  /* #83: @13 = (@13-@15) */
  w13 -= w15;
  /* #84: @25 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 3, w25);
  /* #85: @26 = @3[32:35] */
  wr26 = wr03+32;
  /* #86: @25 = (@25-@26) */
  for (i=0, rr=w25, cs=wr26; i<3; ++i) (*rr++) -= (*cs++);
  /* #87: @27 = vertcat(@2, @4, @23, @24, @8, @13, @25) */
  rr=w27;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  *rr++ = w08;
  *rr++ = w13;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #88: @28 = @27' */
  casadi_copy(w27, 17, w28);
  /* #89: @29 = @3[35:52] */
  wr29 = wr03+35;
  /* #90: @30 = mac(@28,@29,@1) */
  casadi_copy(w01, 17, w30);
  casadi_mtimes(w28, casadi_s0, wr29, casadi_s1, w30, casadi_s0, w, 0);
  /* #91: @0 = mac(@30,@27,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w30+j, ct=w27+i*17; k<17; ++k) *rr += cs[k*1]**ct++;
  /* #92: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #93: @31 = 00 */
  /* #94: @32 = zeros(3x1,0nz) */
  /* #95: @30 = @30' */
  /* #96: @27 = @29' */
  casadi_trans(wr29,casadi_s1, w27, casadi_s1, iw);
  /* #97: @1 = mac(@28,@27,@1) */
  casadi_mtimes(w28, casadi_s0, w27, casadi_s1, w01, casadi_s0, w, 0);
  /* #98: @1 = @1' */
  /* #99: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w01; i<17; ++i) (*rr++) += (*cs++);
  /* #100: {@2, @4, @24, @25, @0, @8, @26} = vertsplit(@30) */
  casadi_copy(w30, 3, w02);
  casadi_copy(w30+3, 3, w04);
  casadi_copy(w30+6, 3, w24);
  casadi_copy(w30+9, 3, w25);
  w00 = w30[12];
  w08 = w30[13];
  casadi_copy(w30+14, 3, w26);
  /* #101: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #102: @13 = sq(@20) */
  w13 = casadi_sq( w20 );
  /* #103: @6 = (@6+@13) */
  w06 += w13;
  /* #104: @13 = (@19/@6) */
  w13  = (w19/w06);
  /* #105: @33 = (@24/@19) */
  for (i=0, rr=w33, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #106: @15 = dot(@22, @33) */
  w15 = casadi_dot(3, w22, w33);
  /* #107: @13 = (@13*@15) */
  w13 *= w15;
  /* #108: @13 = (-@13) */
  w13 = (- w13 );
  /* #109: @11 = @10; (@11[0] += @13) */
  casadi_copy(w10, 4, w11);
  for (rr=w11+0, cs=(&w13); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #110: @23 = (@23/@19) */
  for (i=0, rr=w23; i<3; ++i) (*rr++) /= w19;
  /* #111: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #112: @13 = dot(@23, @24) */
  w13 = casadi_dot(3, w23, w24);
  /* #113: @20 = (@20/@6) */
  w20 /= w06;
  /* #114: @20 = (@20*@15) */
  w20 *= w15;
  /* #115: @13 = (@13+@20) */
  w13 += w20;
  /* #116: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #117: @13 = (@13/@19) */
  w13 /= w19;
  /* #118: @5 = (@13*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #119: @5 = (2.*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #120: @33 = (@17*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #121: @33 = (2.*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #122: @5 = (@5+@33) */
  for (i=0, rr=w05, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #123: (@11[1:4] += @5) */
  for (rr=w11+1, cs=w05; rr!=w11+4; rr+=1) *rr += *cs++;
  /* #124: @34 = (@9?@11:0) */
  for (i=0, rr=w34, cs=w11; i<4; ++i) (*rr++)  = (w09?cs[i]:0);
  /* #125: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #126: @11 = (@18?@11:0) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w18?cs[i]:0);
  /* #127: @34 = (@34+@11) */
  for (i=0, rr=w34, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #128: {@18, @9, @17, @13} = vertsplit(@34) */
  w18 = w34[0];
  w09 = w34[1];
  w17 = w34[2];
  w13 = w34[3];
  /* #129: @19 = (@7*@13) */
  w19  = (w07*w13);
  /* #130: @20 = (@12*@17) */
  w20  = (w12*w17);
  /* #131: @19 = (@19-@20) */
  w19 -= w20;
  /* #132: @20 = (@14*@9) */
  w20  = (w14*w09);
  /* #133: @19 = (@19+@20) */
  w19 += w20;
  /* #134: @20 = (@16*@18) */
  w20  = (w16*w18);
  /* #135: @19 = (@19-@20) */
  w19 -= w20;
  /* #136: (@10[3] += @19) */
  for (rr=w10+3, cs=(&w19); rr!=w10+4; rr+=1) *rr += *cs++;
  /* #137: @19 = (@12*@13) */
  w19  = (w12*w13);
  /* #138: @20 = (@7*@17) */
  w20  = (w07*w17);
  /* #139: @19 = (@19+@20) */
  w19 += w20;
  /* #140: @20 = (@16*@9) */
  w20  = (w16*w09);
  /* #141: @19 = (@19-@20) */
  w19 -= w20;
  /* #142: @20 = (@14*@18) */
  w20  = (w14*w18);
  /* #143: @19 = (@19-@20) */
  w19 -= w20;
  /* #144: (@10[2] += @19) */
  for (rr=w10+2, cs=(&w19); rr!=w10+3; rr+=1) *rr += *cs++;
  /* #145: @19 = (@16*@17) */
  w19  = (w16*w17);
  /* #146: @20 = (@14*@13) */
  w20  = (w14*w13);
  /* #147: @19 = (@19-@20) */
  w19 -= w20;
  /* #148: @20 = (@7*@9) */
  w20  = (w07*w09);
  /* #149: @19 = (@19+@20) */
  w19 += w20;
  /* #150: @20 = (@12*@18) */
  w20  = (w12*w18);
  /* #151: @19 = (@19-@20) */
  w19 -= w20;
  /* #152: (@10[1] += @19) */
  for (rr=w10+1, cs=(&w19); rr!=w10+2; rr+=1) *rr += *cs++;
  /* #153: @16 = (@16*@13) */
  w16 *= w13;
  /* #154: @14 = (@14*@17) */
  w14 *= w17;
  /* #155: @16 = (@16+@14) */
  w16 += w14;
  /* #156: @12 = (@12*@9) */
  w12 *= w09;
  /* #157: @16 = (@16+@12) */
  w16 += w12;
  /* #158: @7 = (@7*@18) */
  w07 *= w18;
  /* #159: @16 = (@16+@7) */
  w16 += w07;
  /* #160: (@10[0] += @16) */
  for (rr=w10+0, cs=(&w16); rr!=w10+1; rr+=1) *rr += *cs++;
  /* #161: @35 = vertcat(@31, @31, @32, @2, @4, @10, @25, @0, @8, @26) */
  rr=w35;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  *rr++ = w00;
  *rr++ = w08;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #162: @36 = dense(@35) */
  casadi_densify(w35, casadi_s2, w36, 0);
  /* #163: output[1][0] = @36 */
  casadi_copy(w36, 23, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 233;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_nmpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 233*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
