/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[43] = 
  {1, 20, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0};
static const casadi_int casadi_s1[43] = 
  {20, 20, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19};
static const casadi_int casadi_s2[25] = 
  {26, 1, 0, 21, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 20, 21, 22, 23, 24,
  25};
static const casadi_int casadi_s3[3] = {21, 1, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {0, 1, 1};
static const casadi_int casadi_s6[3] = {59, 1, 1};
static const casadi_int casadi_s7[3] = {1, 1, 1};
static const casadi_int casadi_s8[3] = {26, 1, 1};

static const casadi_real casadi_zeros[59] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* quadrotor_mhe_cost_ext_cost_0_fun_jac:(i0[21],i1[5],i2[0],i3[59])->(o0,o1[26]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+22, *w04=w+84, *w05=w+87, w06, w07, w08, w09, *w10=w+94, *w11=w+98;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+112, *w23=w+115;
  casadi_real *w24=w+118, *w25=w+121, w26, w27, *w28=w+126, *w29=w+129, *w30=w+149, *w32=w+189, *w35=w+209, *w36=w+212, *w37=w+216, *w38=w+237;
  const casadi_real *cr, *cs, *ct, *wr03, *wr04, *wr05, *wr11, *wr25, *wr28, *wr31;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x20) */
  casadi_clear(w01, 20);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[18:21] */
  wr04 = wr03+18;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w04);
  /* #7: @5 = @3[21:24] */
  wr05 = wr03+21;
  /* #8: @4 = (@4-@5) */
  for (i=0, rr=w04, cs=wr05; i<3; ++i) (*rr++) -= (*cs++);
  /* #9: @6 = @3[24] */
  w06 = wr03[24];
  /* #10: @7 = @3[25] */
  w07 = wr03[25];
  /* #11: @7 = (-@7) */
  w07 = (- w07 );
  /* #12: @8 = @3[26] */
  w08 = wr03[26];
  /* #13: @8 = (-@8) */
  w08 = (- w08 );
  /* #14: @9 = @3[27] */
  w09 = wr03[27];
  /* #15: @9 = (-@9) */
  w09 = (- w09 );
  /* #16: @10 = vertcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #17: @6 = 1e-12 */
  w06 = 9.9999999999999998e-13;
  /* #18: @11 = @3[24:28] */
  wr11 = wr03+24;
  /* #19: @7 = ||@11||_F */
  w07 = casadi_norm_2(4, wr11);
  /* #20: @7 = (@6+@7) */
  w07  = (w06+w07);
  /* #21: @10 = (@10/@7) */
  for (i=0, rr=w10; i<4; ++i) (*rr++) /= w07;
  /* #22: @7 = @10[0] */
  for (rr=(&w07), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #23: @11 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w11);
  /* #24: @8 = @11[0] */
  for (rr=(&w08), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #25: @9 = (@7*@8) */
  w09  = (w07*w08);
  /* #26: @12 = @10[1] */
  for (rr=(&w12), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #27: @13 = @11[1] */
  for (rr=(&w13), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #28: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #29: @9 = (@9-@14) */
  w09 -= w14;
  /* #30: @14 = @10[2] */
  for (rr=(&w14), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #31: @15 = @11[2] */
  for (rr=(&w15), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #32: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #33: @9 = (@9-@16) */
  w09 -= w16;
  /* #34: @16 = @10[3] */
  for (rr=(&w16), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #35: @17 = @11[3] */
  for (rr=(&w17), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #36: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #37: @9 = (@9-@18) */
  w09 -= w18;
  /* #38: @18 = (@9<@0) */
  w18  = (w09<w00);
  /* #39: @19 = (@7*@13) */
  w19  = (w07*w13);
  /* #40: @20 = (@12*@8) */
  w20  = (w12*w08);
  /* #41: @19 = (@19+@20) */
  w19 += w20;
  /* #42: @20 = (@14*@17) */
  w20  = (w14*w17);
  /* #43: @19 = (@19+@20) */
  w19 += w20;
  /* #44: @20 = (@16*@15) */
  w20  = (w16*w15);
  /* #45: @19 = (@19-@20) */
  w19 -= w20;
  /* #46: @20 = (@7*@15) */
  w20  = (w07*w15);
  /* #47: @21 = (@12*@17) */
  w21  = (w12*w17);
  /* #48: @20 = (@20-@21) */
  w20 -= w21;
  /* #49: @21 = (@14*@8) */
  w21  = (w14*w08);
  /* #50: @20 = (@20+@21) */
  w20 += w21;
  /* #51: @21 = (@16*@13) */
  w21  = (w16*w13);
  /* #52: @20 = (@20+@21) */
  w20 += w21;
  /* #53: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #54: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #55: @17 = (@17+@15) */
  w17 += w15;
  /* #56: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #57: @17 = (@17-@13) */
  w17 -= w13;
  /* #58: @8 = (@16*@8) */
  w08  = (w16*w08);
  /* #59: @17 = (@17+@8) */
  w17 += w08;
  /* #60: @11 = vertcat(@9, @19, @20, @17) */
  rr=w11;
  *rr++ = w09;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w17;
  /* #61: @10 = (-@11) */
  for (i=0, rr=w10, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #62: @10 = (@18?@10:0) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w18?cs[i]:0);
  /* #63: @9 = (!@18) */
  w09 = (! w18 );
  /* #64: @11 = (@9?@11:0) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w09?cs[i]:0);
  /* #65: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #66: @5 = @10[1:4] */
  for (rr=w05, cs=w10+1; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #67: @22 = (2.*@5) */
  for (i=0, rr=w22, cs=w05; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #68: @19 = dot(@5, @5) */
  w19 = casadi_dot(3, w05, w05);
  /* #69: @6 = (@6+@19) */
  w06 += w19;
  /* #70: @19 = sqrt(@6) */
  w19 = sqrt( w06 );
  /* #71: @20 = @10[0] */
  for (rr=(&w20), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #72: @17 = atan2(@19,@20) */
  w17  = atan2(w19,w20);
  /* #73: @23 = (@22*@17) */
  for (i=0, rr=w23, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #74: @23 = (@23/@19) */
  for (i=0, rr=w23; i<3; ++i) (*rr++) /= w19;
  /* #75: @24 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w24);
  /* #76: @25 = @3[28:31] */
  wr25 = wr03+28;
  /* #77: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=wr25; i<3; ++i) (*rr++) -= (*cs++);
  /* #78: @8 = input[0][4] */
  w08 = arg[0] ? arg[0][13] : 0;
  /* #79: @13 = @3[31] */
  w13 = wr03[31];
  /* #80: @8 = (@8-@13) */
  w08 -= w13;
  /* #81: @13 = input[0][5] */
  w13 = arg[0] ? arg[0][14] : 0;
  /* #82: @15 = @3[32] */
  w15 = wr03[32];
  /* #83: @13 = (@13-@15) */
  w13 -= w15;
  /* #84: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][15] : 0;
  /* #85: @21 = @3[33] */
  w21 = wr03[33];
  /* #86: @15 = (@15-@21) */
  w15 -= w21;
  /* #87: @21 = input[0][7] */
  w21 = arg[0] ? arg[0][16] : 0;
  /* #88: @26 = @3[34] */
  w26 = wr03[34];
  /* #89: @21 = (@21-@26) */
  w21 -= w26;
  /* #90: @26 = input[0][8] */
  w26 = arg[0] ? arg[0][17] : 0;
  /* #91: @27 = @3[35] */
  w27 = wr03[35];
  /* #92: @26 = (@26-@27) */
  w26 -= w27;
  /* #93: @25 = input[0][9] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w25);
  /* #94: @28 = @3[36:39] */
  wr28 = wr03+36;
  /* #95: @25 = (@25-@28) */
  for (i=0, rr=w25, cs=wr28; i<3; ++i) (*rr++) -= (*cs++);
  /* #96: @29 = vertcat(@2, @4, @23, @24, @8, @13, @15, @21, @26, @25) */
  rr=w29;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w26;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #97: @30 = @29' */
  casadi_copy(w29, 20, w30);
  /* #98: @31 = @3[39:59] */
  wr31 = wr03+39;
  /* #99: @32 = mac(@30,@31,@1) */
  casadi_copy(w01, 20, w32);
  casadi_mtimes(w30, casadi_s0, wr31, casadi_s1, w32, casadi_s0, w, 0);
  /* #100: @0 = mac(@32,@29,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w29+i*20; k<20; ++k) *rr += cs[k*1]**ct++;
  /* #101: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #102: @33 = 00 */
  /* #103: @34 = zeros(3x1,0nz) */
  /* #104: @32 = @32' */
  /* #105: @29 = @31' */
  casadi_trans(wr31,casadi_s1, w29, casadi_s1, iw);
  /* #106: @1 = mac(@30,@29,@1) */
  casadi_mtimes(w30, casadi_s0, w29, casadi_s1, w01, casadi_s0, w, 0);
  /* #107: @1 = @1' */
  /* #108: @32 = (@32+@1) */
  for (i=0, rr=w32, cs=w01; i<20; ++i) (*rr++) += (*cs++);
  /* #109: {@2, @4, @24, @25, @0, @8, @13, @15, @21, @28} = vertsplit(@32) */
  casadi_copy(w32, 3, w02);
  casadi_copy(w32+3, 3, w04);
  casadi_copy(w32+6, 3, w24);
  casadi_copy(w32+9, 3, w25);
  w00 = w32[12];
  w08 = w32[13];
  w13 = w32[14];
  w15 = w32[15];
  w21 = w32[16];
  casadi_copy(w32+17, 3, w28);
  /* #110: @10 = zeros(4x1) */
  casadi_clear(w10, 4);
  /* #111: @26 = sq(@20) */
  w26 = casadi_sq( w20 );
  /* #112: @6 = (@6+@26) */
  w06 += w26;
  /* #113: @26 = (@19/@6) */
  w26  = (w19/w06);
  /* #114: @35 = (@24/@19) */
  for (i=0, rr=w35, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w19);
  /* #115: @27 = dot(@22, @35) */
  w27 = casadi_dot(3, w22, w35);
  /* #116: @26 = (@26*@27) */
  w26 *= w27;
  /* #117: @26 = (-@26) */
  w26 = (- w26 );
  /* #118: @11 = @10; (@11[0] += @26) */
  casadi_copy(w10, 4, w11);
  for (rr=w11+0, cs=(&w26); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #119: @23 = (@23/@19) */
  for (i=0, rr=w23; i<3; ++i) (*rr++) /= w19;
  /* #120: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #121: @26 = dot(@23, @24) */
  w26 = casadi_dot(3, w23, w24);
  /* #122: @20 = (@20/@6) */
  w20 /= w06;
  /* #123: @20 = (@20*@27) */
  w20 *= w27;
  /* #124: @26 = (@26+@20) */
  w26 += w20;
  /* #125: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #126: @26 = (@26/@19) */
  w26 /= w19;
  /* #127: @5 = (@26*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w26*(*cs++));
  /* #128: @5 = (2.*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #129: @35 = (@17*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #130: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #131: @5 = (@5+@35) */
  for (i=0, rr=w05, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #132: (@11[1:4] += @5) */
  for (rr=w11+1, cs=w05; rr!=w11+4; rr+=1) *rr += *cs++;
  /* #133: @36 = (@9?@11:0) */
  for (i=0, rr=w36, cs=w11; i<4; ++i) (*rr++)  = (w09?cs[i]:0);
  /* #134: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #135: @11 = (@18?@11:0) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w18?cs[i]:0);
  /* #136: @36 = (@36+@11) */
  for (i=0, rr=w36, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #137: {@18, @9, @17, @26} = vertsplit(@36) */
  w18 = w36[0];
  w09 = w36[1];
  w17 = w36[2];
  w26 = w36[3];
  /* #138: @19 = (@7*@26) */
  w19  = (w07*w26);
  /* #139: @20 = (@12*@17) */
  w20  = (w12*w17);
  /* #140: @19 = (@19-@20) */
  w19 -= w20;
  /* #141: @20 = (@14*@9) */
  w20  = (w14*w09);
  /* #142: @19 = (@19+@20) */
  w19 += w20;
  /* #143: @20 = (@16*@18) */
  w20  = (w16*w18);
  /* #144: @19 = (@19-@20) */
  w19 -= w20;
  /* #145: (@10[3] += @19) */
  for (rr=w10+3, cs=(&w19); rr!=w10+4; rr+=1) *rr += *cs++;
  /* #146: @19 = (@12*@26) */
  w19  = (w12*w26);
  /* #147: @20 = (@7*@17) */
  w20  = (w07*w17);
  /* #148: @19 = (@19+@20) */
  w19 += w20;
  /* #149: @20 = (@16*@9) */
  w20  = (w16*w09);
  /* #150: @19 = (@19-@20) */
  w19 -= w20;
  /* #151: @20 = (@14*@18) */
  w20  = (w14*w18);
  /* #152: @19 = (@19-@20) */
  w19 -= w20;
  /* #153: (@10[2] += @19) */
  for (rr=w10+2, cs=(&w19); rr!=w10+3; rr+=1) *rr += *cs++;
  /* #154: @19 = (@16*@17) */
  w19  = (w16*w17);
  /* #155: @20 = (@14*@26) */
  w20  = (w14*w26);
  /* #156: @19 = (@19-@20) */
  w19 -= w20;
  /* #157: @20 = (@7*@9) */
  w20  = (w07*w09);
  /* #158: @19 = (@19+@20) */
  w19 += w20;
  /* #159: @20 = (@12*@18) */
  w20  = (w12*w18);
  /* #160: @19 = (@19-@20) */
  w19 -= w20;
  /* #161: (@10[1] += @19) */
  for (rr=w10+1, cs=(&w19); rr!=w10+2; rr+=1) *rr += *cs++;
  /* #162: @16 = (@16*@26) */
  w16 *= w26;
  /* #163: @14 = (@14*@17) */
  w14 *= w17;
  /* #164: @16 = (@16+@14) */
  w16 += w14;
  /* #165: @12 = (@12*@9) */
  w12 *= w09;
  /* #166: @16 = (@16+@12) */
  w16 += w12;
  /* #167: @7 = (@7*@18) */
  w07 *= w18;
  /* #168: @16 = (@16+@7) */
  w16 += w07;
  /* #169: (@10[0] += @16) */
  for (rr=w10+0, cs=(&w16); rr!=w10+1; rr+=1) *rr += *cs++;
  /* #170: @37 = vertcat(@33, @33, @34, @2, @4, @10, @25, @0, @8, @13, @15, @21, @28) */
  rr=w37;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  *rr++ = w00;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w21;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #171: @38 = dense(@37) */
  casadi_densify(w37, casadi_s2, w38, 0);
  /* #172: output[1][0] = @38 */
  casadi_copy(w38, 26, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 21;
  if (sz_w) *sz_w = 263;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 12*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 21*sizeof(casadi_int);
  if (sz_w) *sz_w = 263*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
