/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[43] = 
  {1, 20, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0};
static const casadi_int casadi_s1[43] = 
  {20, 20, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19};
static const casadi_int casadi_s2[3] = {21, 1, 1};
static const casadi_int casadi_s3[3] = {5, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[3] = {59, 1, 1};
static const casadi_int casadi_s6[3] = {1, 1, 1};

static const casadi_real casadi_zeros[59] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* quadrotor_mhe_cost_ext_cost_0_fun:(i0[21],i1[5],i2[0],i3[59])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+22, *w04=w+84, *w05=w+87, w06, w07, w08, w09, *w10=w+94, *w11=w+98;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+112, *w23=w+115;
  casadi_real *w25=w+121, *w26=w+141;
  const casadi_real *cs, *ct, *wr03, *wr04, *wr05, *wr11, *wr23, *wr24, *wr27;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x20) */
  casadi_clear(w01, 20);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[18:21] */
  wr04 = wr03+18;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w04);
  /* #7: @5 = @3[21:24] */
  wr05 = wr03+21;
  /* #8: @4 = (@4-@5) */
  for (i=0, rr=w04, cs=wr05; i<3; ++i) (*rr++) -= (*cs++);
  /* #9: @6 = @3[24] */
  w06 = wr03[24];
  /* #10: @7 = @3[25] */
  w07 = wr03[25];
  /* #11: @7 = (-@7) */
  w07 = (- w07 );
  /* #12: @8 = @3[26] */
  w08 = wr03[26];
  /* #13: @8 = (-@8) */
  w08 = (- w08 );
  /* #14: @9 = @3[27] */
  w09 = wr03[27];
  /* #15: @9 = (-@9) */
  w09 = (- w09 );
  /* #16: @10 = vertcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  /* #17: @6 = 1e-12 */
  w06 = 9.9999999999999998e-13;
  /* #18: @11 = @3[24:28] */
  wr11 = wr03+24;
  /* #19: @7 = ||@11||_F */
  w07 = casadi_norm_2(4, wr11);
  /* #20: @7 = (@6+@7) */
  w07  = (w06+w07);
  /* #21: @10 = (@10/@7) */
  for (i=0, rr=w10; i<4; ++i) (*rr++) /= w07;
  /* #22: @7 = @10[0] */
  for (rr=(&w07), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #23: @11 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w11);
  /* #24: @8 = @11[0] */
  for (rr=(&w08), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #25: @9 = (@7*@8) */
  w09  = (w07*w08);
  /* #26: @12 = @10[1] */
  for (rr=(&w12), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #27: @13 = @11[1] */
  for (rr=(&w13), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #28: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #29: @9 = (@9-@14) */
  w09 -= w14;
  /* #30: @14 = @10[2] */
  for (rr=(&w14), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #31: @15 = @11[2] */
  for (rr=(&w15), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #32: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #33: @9 = (@9-@16) */
  w09 -= w16;
  /* #34: @16 = @10[3] */
  for (rr=(&w16), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #35: @17 = @11[3] */
  for (rr=(&w17), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #36: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #37: @9 = (@9-@18) */
  w09 -= w18;
  /* #38: @18 = (@9<@0) */
  w18  = (w09<w00);
  /* #39: @19 = (@7*@13) */
  w19  = (w07*w13);
  /* #40: @20 = (@12*@8) */
  w20  = (w12*w08);
  /* #41: @19 = (@19+@20) */
  w19 += w20;
  /* #42: @20 = (@14*@17) */
  w20  = (w14*w17);
  /* #43: @19 = (@19+@20) */
  w19 += w20;
  /* #44: @20 = (@16*@15) */
  w20  = (w16*w15);
  /* #45: @19 = (@19-@20) */
  w19 -= w20;
  /* #46: @20 = (@7*@15) */
  w20  = (w07*w15);
  /* #47: @21 = (@12*@17) */
  w21  = (w12*w17);
  /* #48: @20 = (@20-@21) */
  w20 -= w21;
  /* #49: @21 = (@14*@8) */
  w21  = (w14*w08);
  /* #50: @20 = (@20+@21) */
  w20 += w21;
  /* #51: @21 = (@16*@13) */
  w21  = (w16*w13);
  /* #52: @20 = (@20+@21) */
  w20 += w21;
  /* #53: @7 = (@7*@17) */
  w07 *= w17;
  /* #54: @12 = (@12*@15) */
  w12 *= w15;
  /* #55: @7 = (@7+@12) */
  w07 += w12;
  /* #56: @14 = (@14*@13) */
  w14 *= w13;
  /* #57: @7 = (@7-@14) */
  w07 -= w14;
  /* #58: @16 = (@16*@8) */
  w16 *= w08;
  /* #59: @7 = (@7+@16) */
  w07 += w16;
  /* #60: @11 = vertcat(@9, @19, @20, @7) */
  rr=w11;
  *rr++ = w09;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w07;
  /* #61: @10 = (-@11) */
  for (i=0, rr=w10, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #62: @10 = (@18?@10:0) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w18?cs[i]:0);
  /* #63: @18 = (!@18) */
  w18 = (! w18 );
  /* #64: @11 = (@18?@11:0) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w18?cs[i]:0);
  /* #65: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #66: @5 = @10[1:4] */
  for (rr=w05, cs=w10+1; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #67: @22 = (2.*@5) */
  for (i=0, rr=w22, cs=w05; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #68: @18 = dot(@5, @5) */
  w18 = casadi_dot(3, w05, w05);
  /* #69: @6 = (@6+@18) */
  w06 += w18;
  /* #70: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #71: @18 = @10[0] */
  for (rr=(&w18), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #72: @18 = atan2(@6,@18) */
  w18  = atan2(w06,w18);
  /* #73: @22 = (@22*@18) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) *= w18;
  /* #74: @22 = (@22/@6) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w06;
  /* #75: @5 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w05);
  /* #76: @23 = @3[28:31] */
  wr23 = wr03+28;
  /* #77: @5 = (@5-@23) */
  for (i=0, rr=w05, cs=wr23; i<3; ++i) (*rr++) -= (*cs++);
  /* #78: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][13] : 0;
  /* #79: @18 = @3[31] */
  w18 = wr03[31];
  /* #80: @6 = (@6-@18) */
  w06 -= w18;
  /* #81: @18 = input[0][5] */
  w18 = arg[0] ? arg[0][14] : 0;
  /* #82: @9 = @3[32] */
  w09 = wr03[32];
  /* #83: @18 = (@18-@9) */
  w18 -= w09;
  /* #84: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][15] : 0;
  /* #85: @19 = @3[33] */
  w19 = wr03[33];
  /* #86: @9 = (@9-@19) */
  w09 -= w19;
  /* #87: @19 = input[0][7] */
  w19 = arg[0] ? arg[0][16] : 0;
  /* #88: @20 = @3[34] */
  w20 = wr03[34];
  /* #89: @19 = (@19-@20) */
  w19 -= w20;
  /* #90: @20 = input[0][8] */
  w20 = arg[0] ? arg[0][17] : 0;
  /* #91: @7 = @3[35] */
  w07 = wr03[35];
  /* #92: @20 = (@20-@7) */
  w20 -= w07;
  /* #93: @23 = input[0][9] */
  casadi_copy(arg[0] ? arg[0]+18 : 0, 3, w23);
  /* #94: @24 = @3[36:39] */
  wr24 = wr03+36;
  /* #95: @23 = (@23-@24) */
  for (i=0, rr=w23, cs=wr24; i<3; ++i) (*rr++) -= (*cs++);
  /* #96: @25 = vertcat(@2, @4, @22, @5, @6, @18, @9, @19, @20, @23) */
  rr=w25;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  *rr++ = w06;
  *rr++ = w18;
  *rr++ = w09;
  *rr++ = w19;
  *rr++ = w20;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #97: @26 = @25' */
  casadi_copy(w25, 20, w26);
  /* #98: @27 = @3[39:59] */
  wr27 = wr03+39;
  /* #99: @1 = mac(@26,@27,@1) */
  casadi_mtimes(w26, casadi_s0, wr27, casadi_s1, w01, casadi_s0, w, 0);
  /* #100: @0 = mac(@1,@25,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w25+i*20; k<20; ++k) *rr += cs[k*1]**ct++;
  /* #101: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 181;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 181*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
