/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s35 CASADI_PREFIX(s35)
#define casadi_s36 CASADI_PREFIX(s36)
#define casadi_s37 CASADI_PREFIX(s37)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[15] = 
  {1, 6, 0, 1, 2, 3, 4, 5,
  6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[45] = 
  {6, 6, 0, 6, 12, 18, 24, 30,
  36, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5};
static const casadi_int casadi_s5[10] = 
  {1, 6, 0, 0, 0, 0, 1, 1,
  1, 0};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s7[14] = 
  {0, 1, 2, 3, 34, 35, 36, 37,
  38, 39, 40, 41, 42, 43};
static const casadi_int casadi_s8[14] = 
  {0, 4, 8, 12, 19, 25, 31, 37,
  47, 57, 64, 71, 76, 81};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s10[10] = 
  {1, 6, 0, 0, 0, 0, 0, 1,
  1, 0};
static const casadi_int casadi_s11[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s12[14] = 
  {4, 5, 6, 7, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53};
static const casadi_int casadi_s13[14] = 
  {1, 5, 9, 13, 20, 26, 32, 38,
  48, 58, 65, 72, 77, 82};
static const casadi_int casadi_s14[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s15[10] = 
  {1, 6, 0, 0, 0, 0, 0, 0,
  1, 0};
static const casadi_int casadi_s16[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s17[14] = 
  {8, 9, 10, 11, 54, 55, 56, 57,
  58, 59, 60, 61, 62, 63};
static const casadi_int casadi_s18[14] = 
  {2, 6, 10, 14, 21, 27, 33, 39,
  49, 59, 66, 73, 78, 83};
static const casadi_int casadi_s19[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s20[10] = 
  {1, 6, 0, 1, 1, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s21[11] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  11, 12, 13};
static const casadi_int casadi_s22[11] = 
  {12, 13, 14, 15, 16, 17, 18, 67,
  68, 69, 70};
static const casadi_int casadi_s23[11] = 
  {3, 7, 11, 15, 16, 22, 28, 67,
  74, 79, 84};
static const casadi_int casadi_s24[10] = 
  {1, 6, 0, 0, 1, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s25[6] = {22, 23, 24, 75, 80, 85};
static const casadi_int casadi_s26[6] = {17, 23, 29, 75, 80, 85};
static const casadi_int casadi_s27[10] = 
  {1, 6, 0, 0, 0, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s28[6] = {18, 24, 30, 36, 46, 56};
static const casadi_int casadi_s29[103] = 
  {14, 14, 0, 4, 8, 12, 16, 22,
  28, 34, 44, 54, 64, 71, 76, 81,
  86, 0, 1, 2, 3, 0, 1, 2,
  3, 0, 1, 2, 3, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 4,
  5, 6, 7, 8, 9, 4, 5, 6,
  7, 8, 9, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 7, 8, 9, 10, 11, 12, 13,
  7, 8, 9, 10, 11, 7, 8, 9,
  10, 12, 7, 8, 9, 10, 13};
static const casadi_int casadi_s30[3] = {10, 1, 1};
static const casadi_int casadi_s31[3] = {4, 1, 1};
static const casadi_int casadi_s32[3] = {0, 1, 1};
static const casadi_int casadi_s33[3] = {35, 1, 1};
static const casadi_int casadi_s34[3] = {1, 1, 1};
static const casadi_int casadi_s35[3] = {14, 1, 1};
static const casadi_int casadi_s36[3] = {0, 0, 1};
static const casadi_int casadi_s37[3] = {0, 14, 1};

static const casadi_real casadi_c0[36] = 
  {50., 0., 0., 0., 0., 0., 0., 50.,
  0., 0., 0., 0., 0., 0., 50., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 10.};
static const casadi_real casadi_c1[16] = 
  {1000., 0., 0., 0., 0., 1000., 0., 0.,
  0., 0., 1000., 0., 0., 0., 0., 1000.};

static const casadi_real casadi_zeros[35] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess:(i0[10],i1[4],i2[0],i3[35])->(o0,o1[14],o2[14x14,86nz],o3[],o4[0x14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, *w03=w+38, *w04=w+44, *w05=w+47, *w06=w+50, *w07=w+53, *w08=w+59, *w10=w+101, w11, *w12=w+108;
  casadi_real w13, *w14=w+113, *w15=w+117, *w17=w+137, *w18=w+141, *w19=w+144, w20, w21, w22, *w23=w+150, *w24=w+153, *w25=w+169;
  casadi_real *w26=w+205, w27, w28, *w29=w+210, *w30=w+296, w31, w33, w34, *w35=w+301, w36, w37, *w38=w+306;
  casadi_real w39, *w40=w+310, *w41=w+313, *w42=w+316, w44, *w45=w+331, *w46=w+342, *w47=w+352;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr00, *wr04, *wr05, *wr06, *wr09, *wr16;
  /* #0: @0 = input[3][0] */
  wr00 = arg[3] ? arg[3] : casadi_zeros;
  /* #1: @1 = @0[34] */
  w01 = wr00[34];
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = zeros(1x6) */
  casadi_clear(w03, 6);
  /* #4: @4 = input[0][0] */
  casadi_copy(arg[0], 3, w04);
  /* #5: @5 = @0[:3] */
  wr05 = wr00+0;
  /* #6: @4 = (@4-@5) */
  for (i=0, rr=w04, cs=wr05; i<3; ++i) (*rr++) -= (*cs++);
  /* #7: @5 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w05);
  /* #8: @6 = @0[3:6] */
  wr06 = wr00+3;
  /* #9: @6 = (@5-@6) */
  for (i=0, rr=w06, cr=w05, cs=wr06; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #10: @7 = vertcat(@4, @6) */
  rr=w07;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  /* #11: @8 = @7' */
  casadi_copy(w07, 6, w08);
  /* #12: @9 = 
  [[50, 0, 0, 0, 0, 0], 
   [0, 50, 0, 0, 0, 0], 
   [0, 0, 50, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 10]] */
  wr09 = casadi_c0;
  /* #13: @10 = mac(@8,@9,@3) */
  casadi_copy(w03, 6, w10);
  for (i=0, rr=w10; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w08+j, ct=wr09+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #14: @11 = mac(@10,@7,@2) */
  casadi_copy((&w02), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w10+j, ct=w07+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #15: @11 = (@1*@11) */
  w11  = (w01*w11);
  /* #16: @12 = zeros(1x4) */
  casadi_clear(w12, 4);
  /* #17: @13 = input[1][0] */
  w13 = arg[1] ? arg[1][0] : 0;
  /* #18: @4 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w04);
  /* #19: @14 = vertcat(@13, @4) */
  rr=w14;
  *rr++ = w13;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  /* #20: @15 = @14' */
  casadi_copy(w14, 4, w15);
  /* #21: @16 = 
  [[1000, 0, 0, 0], 
   [0, 1000, 0, 0], 
   [0, 0, 1000, 0], 
   [0, 0, 0, 1000]] */
  wr16 = casadi_c1;
  /* #22: @17 = mac(@15,@16,@12) */
  casadi_copy(w12, 4, w17);
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w15+j, ct=wr16+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #23: @2 = mac(@17,@14,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w17+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #24: @11 = (@11+@2) */
  w11 += w02;
  /* #25: @4 = @0[31:34] */
  wr04 = wr00+31;
  /* #26: @2 = @0[6] */
  w02 = wr00[6];
  /* #27: @13 = input[0][2] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #28: @2 = (@2/@13) */
  w02 /= w13;
  /* #29: @6 = @0[7:10] */
  wr06 = wr00+7;
  /* #30: @18 = (@2*@6) */
  for (i=0, rr=w18, cs=wr06; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #31: @19 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w19);
  /* #32: @18 = (@18+@19) */
  for (i=0, rr=w18, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #33: @20 = @0[30] */
  w20 = wr00[30];
  /* #34: @19 = (@20*@5) */
  for (i=0, rr=w19, cs=w05; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #35: @21 = 1e-06 */
  w21 = 9.9999999999999995e-07;
  /* #36: @22 = dot(@5, @5) */
  w22 = casadi_dot(3, w05, w05);
  /* #37: @21 = (@21+@22) */
  w21 += w22;
  /* #38: @21 = sqrt(@21) */
  w21 = sqrt( w21 );
  /* #39: @23 = (@19*@21) */
  for (i=0, rr=w23, cr=w19; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #40: @18 = (@18-@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) -= (*cs++);
  /* #41: @4 = (@4-@18) */
  for (i=0, rr=w04, cr=wr04, cs=w18; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #42: @22 = dot(@4, @4) */
  w22 = casadi_dot(3, w04, w04);
  /* #43: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #44: @11 = (@11+@22) */
  w11 += w22;
  /* #45: output[0][0] = @11 */
  if (res[0]) res[0][0] = w11;
  /* #46: @17 = @17' */
  /* #47: @24 = @16' */
  for (i=0, rr=w24, cs=wr16; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #48: @14 = mac(@15,@24,@12) */
  casadi_copy(w12, 4, w14);
  for (i=0, rr=w14; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w15+j, ct=w24+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #49: @14 = @14' */
  /* #50: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #51: {@11, @18} = vertsplit(@17) */
  w11 = w17[0];
  casadi_copy(w17+1, 3, w18);
  /* #52: output[1][0] = @11 */
  if (res[1]) res[1][0] = w11;
  /* #53: output[1][1] = @18 */
  if (res[1]) casadi_copy(w18, 3, res[1]+1);
  /* #54: @10 = @10' */
  /* #55: @10 = (@10*@1) */
  for (i=0, rr=w10; i<6; ++i) (*rr++) *= w01;
  /* #56: @8 = (@1*@8) */
  for (i=0, rr=w08, cs=w08; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #57: @25 = @9' */
  for (i=0, rr=w25, cs=wr09; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #58: @7 = mac(@8,@25,@3) */
  casadi_copy(w03, 6, w07);
  for (i=0, rr=w07; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w08+j, ct=w25+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #59: @7 = @7' */
  /* #60: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<6; ++i) (*rr++) += (*cs++);
  /* #61: {@18, @23} = vertsplit(@10) */
  casadi_copy(w10, 3, w18);
  casadi_copy(w10+3, 3, w23);
  /* #62: output[1][2] = @18 */
  if (res[1]) casadi_copy(w18, 3, res[1]+4);
  /* #63: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #64: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #65: @11 = dot(@19, @4) */
  w11 = casadi_dot(3, w19, w04);
  /* #66: @22 = (2.*@21) */
  w22 = (2.* w21 );
  /* #67: @11 = (@11/@22) */
  w11 /= w22;
  /* #68: @18 = (@11*@5) */
  for (i=0, rr=w18, cs=w05; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #69: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #70: @26 = (@21*@4) */
  for (i=0, rr=w26, cs=w04; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #71: @26 = (@20*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #72: @18 = (@18+@26) */
  for (i=0, rr=w18, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #73: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #74: output[1][3] = @18 */
  if (res[1]) casadi_copy(w18, 3, res[1]+7);
  /* #75: @2 = (@2/@13) */
  w02 /= w13;
  /* #76: @18 = (-@4) */
  for (i=0, rr=w18, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #77: @27 = dot(@6, @18) */
  w27 = casadi_dot(3, wr06, w18);
  /* #78: @28 = (@2*@27) */
  w28  = (w02*w27);
  /* #79: @28 = (-@28) */
  w28 = (- w28 );
  /* #80: output[1][4] = @28 */
  if (res[1]) res[1][10] = w28;
  /* #81: output[1][5] = @18 */
  if (res[1]) casadi_copy(w18, 3, res[1]+11);
  /* #82: @29 = zeros(14x14,86nz) */
  casadi_clear(w29, 86);
  /* #83: @30 = ones(14x1,2nz) */
  casadi_fill(w30, 2, 1.);
  /* #84: {@28, NULL, NULL, @31, NULL, NULL} = vertsplit(@30) */
  w28 = w30[0];
  w31 = w30[1];
  /* #85: @32 = zeros(3x1,0nz) */
  /* #86: @33 = vertcat(@28, @32) */
  rr=(&w33);
  *rr++ = w28;
  /* #87: @33 = @33' */
  /* #88: @17 = mac(@33,@16,@12) */
  casadi_copy(w12, 4, w17);
  casadi_mtimes((&w33), casadi_s2, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #89: @17 = @17' */
  /* #90: @14 = mac(@33,@24,@12) */
  casadi_copy(w12, 4, w14);
  casadi_mtimes((&w33), casadi_s2, w24, casadi_s1, w14, casadi_s0, w, 0);
  /* #91: @14 = @14' */
  /* #92: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #93: {@33, @18} = vertsplit(@17) */
  w33 = w17[0];
  casadi_copy(w17+1, 3, w18);
  /* #94: @28 = vertcat(@32, @31) */
  rr=(&w28);
  *rr++ = w31;
  /* #95: @28 = @28' */
  /* #96: @10 = mac(@28,@9,@3) */
  casadi_copy(w03, 6, w10);
  casadi_mtimes((&w28), casadi_s5, wr09, casadi_s4, w10, casadi_s3, w, 0);
  /* #97: @10 = @10' */
  /* #98: @10 = (@1*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #99: @28 = (@1*@28) */
  w28  = (w01*w28);
  /* #100: @7 = mac(@28,@25,@3) */
  casadi_copy(w03, 6, w07);
  casadi_mtimes((&w28), casadi_s5, w25, casadi_s4, w07, casadi_s3, w, 0);
  /* #101: @7 = @7' */
  /* #102: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<6; ++i) (*rr++) += (*cs++);
  /* #103: {@23, @26} = vertsplit(@10) */
  casadi_copy(w10, 3, w23);
  casadi_copy(w10+3, 3, w26);
  /* #104: @28 = (@20*@31) */
  w28  = (w20*w31);
  /* #105: @34 = (@21*@28) */
  w34  = (w21*w28);
  /* #106: @35 = dense(@34) */
  casadi_densify((&w34), casadi_s6, w35, 0);
  /* #107: @34 = project(@5) */
  casadi_sparsify(w05, (&w34), casadi_s6, 0);
  /* #108: @36 = dot(@34, @31) */
  w36 = casadi_dot(1, (&w34), (&w31));
  /* #109: @37 = dot(@31, @34) */
  w37 = casadi_dot(1, (&w31), (&w34));
  /* #110: @36 = (@36+@37) */
  w36 += w37;
  /* #111: @36 = (@36/@22) */
  w36 /= w22;
  /* #112: @38 = (@19*@36) */
  for (i=0, rr=w38, cr=w19; i<3; ++i) (*rr++)  = ((*cr++)*w36);
  /* #113: @35 = (@35+@38) */
  for (i=0, rr=w35, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #114: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #115: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #116: @37 = dot(@19, @35) */
  w37 = casadi_dot(3, w19, w35);
  /* #117: @34 = project(@4) */
  casadi_sparsify(w04, (&w34), casadi_s6, 0);
  /* #118: @39 = dot(@28, @34) */
  w39 = casadi_dot(1, (&w28), (&w34));
  /* #119: @37 = (@37+@39) */
  w37 += w39;
  /* #120: @37 = (@37/@22) */
  w37 /= w22;
  /* #121: @39 = (@11/@22) */
  w39  = (w11/w22);
  /* #122: @28 = (2.*@36) */
  w28 = (2.* w36 );
  /* #123: @28 = (@39*@28) */
  w28  = (w39*w28);
  /* #124: @37 = (@37-@28) */
  w37 -= w28;
  /* #125: @38 = (@5*@37) */
  for (i=0, rr=w38, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w37);
  /* #126: @31 = (@11*@31) */
  w31  = (w11*w31);
  /* #127: @40 = dense(@31) */
  casadi_densify((&w31), casadi_s6, w40, 0);
  /* #128: @38 = (@38+@40) */
  for (i=0, rr=w38, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #129: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #130: @40 = (@4*@36) */
  for (i=0, rr=w40, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w36);
  /* #131: @41 = (@21*@35) */
  for (i=0, rr=w41, cs=w35; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #132: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #133: @40 = (@20*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #134: @38 = (@38+@40) */
  for (i=0, rr=w38, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #135: @38 = (@38+@26) */
  for (i=0, rr=w38, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #136: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #137: @36 = dot(@6, @35) */
  w36 = casadi_dot(3, wr06, w35);
  /* #138: @36 = (@2*@36) */
  w36  = (w02*w36);
  /* #139: @36 = (-@36) */
  w36 = (- w36 );
  /* #140: @42 = vertcat(@33, @18, @23, @38, @36, @35) */
  rr=w42;
  *rr++ = w33;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  *rr++ = w36;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  /* #141: (@29[0, 1, 2, 3, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43] = @42) */
  for (cii=casadi_s7, rr=w29, cs=w42; cii!=casadi_s7+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #142: (@29[0, 4, 8, 12, 19, 25, 31, 37, 47, 57, 64, 71, 76, 81] = @42) */
  for (cii=casadi_s8, rr=w29, cs=w42; cii!=casadi_s8+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #143: @43 = 00 */
  /* #144: @30 = ones(14x1,2nz) */
  casadi_fill(w30, 2, 1.);
  /* #145: {NULL, @33, NULL, @36, NULL, NULL} = vertsplit(@30) */
  w33 = w30[0];
  w36 = w30[1];
  /* #146: @31 = vertcat(@43, @33) */
  rr=(&w31);
  *rr++ = w33;
  /* #147: @31 = @31' */
  /* #148: @17 = mac(@31,@16,@12) */
  casadi_copy(w12, 4, w17);
  casadi_mtimes((&w31), casadi_s9, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #149: @17 = @17' */
  /* #150: @14 = mac(@31,@24,@12) */
  casadi_copy(w12, 4, w14);
  casadi_mtimes((&w31), casadi_s9, w24, casadi_s1, w14, casadi_s0, w, 0);
  /* #151: @14 = @14' */
  /* #152: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #153: {@31, @18} = vertsplit(@17) */
  w31 = w17[0];
  casadi_copy(w17+1, 3, w18);
  /* #154: @33 = vertcat(@32, @36) */
  rr=(&w33);
  *rr++ = w36;
  /* #155: @33 = @33' */
  /* #156: @10 = mac(@33,@9,@3) */
  casadi_copy(w03, 6, w10);
  casadi_mtimes((&w33), casadi_s10, wr09, casadi_s4, w10, casadi_s3, w, 0);
  /* #157: @10 = @10' */
  /* #158: @10 = (@1*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #159: @33 = (@1*@33) */
  w33  = (w01*w33);
  /* #160: @7 = mac(@33,@25,@3) */
  casadi_copy(w03, 6, w07);
  casadi_mtimes((&w33), casadi_s10, w25, casadi_s4, w07, casadi_s3, w, 0);
  /* #161: @7 = @7' */
  /* #162: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<6; ++i) (*rr++) += (*cs++);
  /* #163: {@23, @38} = vertsplit(@10) */
  casadi_copy(w10, 3, w23);
  casadi_copy(w10+3, 3, w38);
  /* #164: @33 = (@20*@36) */
  w33  = (w20*w36);
  /* #165: @37 = (@21*@33) */
  w37  = (w21*w33);
  /* #166: @35 = dense(@37) */
  casadi_densify((&w37), casadi_s11, w35, 0);
  /* #167: @37 = project(@5) */
  casadi_sparsify(w05, (&w37), casadi_s11, 0);
  /* #168: @28 = dot(@37, @36) */
  w28 = casadi_dot(1, (&w37), (&w36));
  /* #169: @34 = dot(@36, @37) */
  w34 = casadi_dot(1, (&w36), (&w37));
  /* #170: @28 = (@28+@34) */
  w28 += w34;
  /* #171: @28 = (@28/@22) */
  w28 /= w22;
  /* #172: @26 = (@19*@28) */
  for (i=0, rr=w26, cr=w19; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #173: @35 = (@35+@26) */
  for (i=0, rr=w35, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #174: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #175: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #176: @34 = dot(@19, @35) */
  w34 = casadi_dot(3, w19, w35);
  /* #177: @37 = project(@4) */
  casadi_sparsify(w04, (&w37), casadi_s11, 0);
  /* #178: @44 = dot(@33, @37) */
  w44 = casadi_dot(1, (&w33), (&w37));
  /* #179: @34 = (@34+@44) */
  w34 += w44;
  /* #180: @34 = (@34/@22) */
  w34 /= w22;
  /* #181: @44 = (2.*@28) */
  w44 = (2.* w28 );
  /* #182: @44 = (@39*@44) */
  w44  = (w39*w44);
  /* #183: @34 = (@34-@44) */
  w34 -= w44;
  /* #184: @26 = (@5*@34) */
  for (i=0, rr=w26, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w34);
  /* #185: @36 = (@11*@36) */
  w36  = (w11*w36);
  /* #186: @40 = dense(@36) */
  casadi_densify((&w36), casadi_s11, w40, 0);
  /* #187: @26 = (@26+@40) */
  for (i=0, rr=w26, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #188: @26 = (2.*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #189: @40 = (@4*@28) */
  for (i=0, rr=w40, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #190: @41 = (@21*@35) */
  for (i=0, rr=w41, cs=w35; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #191: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #192: @40 = (@20*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #193: @26 = (@26+@40) */
  for (i=0, rr=w26, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #194: @26 = (@26+@38) */
  for (i=0, rr=w26, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #195: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #196: @28 = dot(@6, @35) */
  w28 = casadi_dot(3, wr06, w35);
  /* #197: @28 = (@2*@28) */
  w28  = (w02*w28);
  /* #198: @28 = (-@28) */
  w28 = (- w28 );
  /* #199: @42 = vertcat(@31, @18, @23, @26, @28, @35) */
  rr=w42;
  *rr++ = w31;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  *rr++ = w28;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  /* #200: (@29[4, 5, 6, 7, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53] = @42) */
  for (cii=casadi_s12, rr=w29, cs=w42; cii!=casadi_s12+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #201: (@29[1, 5, 9, 13, 20, 26, 32, 38, 48, 58, 65, 72, 77, 82] = @42) */
  for (cii=casadi_s13, rr=w29, cs=w42; cii!=casadi_s13+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #202: @30 = ones(14x1,2nz) */
  casadi_fill(w30, 2, 1.);
  /* #203: {NULL, @31, NULL, @28, NULL, NULL} = vertsplit(@30) */
  w31 = w30[0];
  w28 = w30[1];
  /* #204: @36 = vertcat(@43, @31) */
  rr=(&w36);
  *rr++ = w31;
  /* #205: @36 = @36' */
  /* #206: @17 = mac(@36,@16,@12) */
  casadi_copy(w12, 4, w17);
  casadi_mtimes((&w36), casadi_s14, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #207: @17 = @17' */
  /* #208: @14 = mac(@36,@24,@12) */
  casadi_copy(w12, 4, w14);
  casadi_mtimes((&w36), casadi_s14, w24, casadi_s1, w14, casadi_s0, w, 0);
  /* #209: @14 = @14' */
  /* #210: @17 = (@17+@14) */
  for (i=0, rr=w17, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #211: {@36, @18} = vertsplit(@17) */
  w36 = w17[0];
  casadi_copy(w17+1, 3, w18);
  /* #212: @31 = vertcat(@32, @28) */
  rr=(&w31);
  *rr++ = w28;
  /* #213: @31 = @31' */
  /* #214: @10 = mac(@31,@9,@3) */
  casadi_copy(w03, 6, w10);
  casadi_mtimes((&w31), casadi_s15, wr09, casadi_s4, w10, casadi_s3, w, 0);
  /* #215: @10 = @10' */
  /* #216: @10 = (@1*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #217: @31 = (@1*@31) */
  w31  = (w01*w31);
  /* #218: @7 = mac(@31,@25,@3) */
  casadi_copy(w03, 6, w07);
  casadi_mtimes((&w31), casadi_s15, w25, casadi_s4, w07, casadi_s3, w, 0);
  /* #219: @7 = @7' */
  /* #220: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<6; ++i) (*rr++) += (*cs++);
  /* #221: {@23, @26} = vertsplit(@10) */
  casadi_copy(w10, 3, w23);
  casadi_copy(w10+3, 3, w26);
  /* #222: @31 = (@20*@28) */
  w31  = (w20*w28);
  /* #223: @34 = (@21*@31) */
  w34  = (w21*w31);
  /* #224: @35 = dense(@34) */
  casadi_densify((&w34), casadi_s16, w35, 0);
  /* #225: @34 = project(@5) */
  casadi_sparsify(w05, (&w34), casadi_s16, 0);
  /* #226: @44 = dot(@34, @28) */
  w44 = casadi_dot(1, (&w34), (&w28));
  /* #227: @33 = dot(@28, @34) */
  w33 = casadi_dot(1, (&w28), (&w34));
  /* #228: @44 = (@44+@33) */
  w44 += w33;
  /* #229: @44 = (@44/@22) */
  w44 /= w22;
  /* #230: @38 = (@19*@44) */
  for (i=0, rr=w38, cr=w19; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #231: @35 = (@35+@38) */
  for (i=0, rr=w35, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #232: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #233: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #234: @33 = dot(@19, @35) */
  w33 = casadi_dot(3, w19, w35);
  /* #235: @34 = project(@4) */
  casadi_sparsify(w04, (&w34), casadi_s16, 0);
  /* #236: @37 = dot(@31, @34) */
  w37 = casadi_dot(1, (&w31), (&w34));
  /* #237: @33 = (@33+@37) */
  w33 += w37;
  /* #238: @33 = (@33/@22) */
  w33 /= w22;
  /* #239: @37 = (2.*@44) */
  w37 = (2.* w44 );
  /* #240: @39 = (@39*@37) */
  w39 *= w37;
  /* #241: @33 = (@33-@39) */
  w33 -= w39;
  /* #242: @38 = (@5*@33) */
  for (i=0, rr=w38, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w33);
  /* #243: @11 = (@11*@28) */
  w11 *= w28;
  /* #244: @40 = dense(@11) */
  casadi_densify((&w11), casadi_s16, w40, 0);
  /* #245: @38 = (@38+@40) */
  for (i=0, rr=w38, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #246: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #247: @4 = (@4*@44) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) *= w44;
  /* #248: @40 = (@21*@35) */
  for (i=0, rr=w40, cs=w35; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #249: @4 = (@4+@40) */
  for (i=0, rr=w04, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #250: @4 = (@20*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #251: @38 = (@38+@4) */
  for (i=0, rr=w38, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #252: @38 = (@38+@26) */
  for (i=0, rr=w38, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #253: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #254: @44 = dot(@6, @35) */
  w44 = casadi_dot(3, wr06, w35);
  /* #255: @44 = (@2*@44) */
  w44  = (w02*w44);
  /* #256: @44 = (-@44) */
  w44 = (- w44 );
  /* #257: @42 = vertcat(@36, @18, @23, @38, @44, @35) */
  rr=w42;
  *rr++ = w36;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  *rr++ = w44;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  /* #258: (@29[8, 9, 10, 11, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63] = @42) */
  for (cii=casadi_s17, rr=w29, cs=w42; cii!=casadi_s17+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #259: (@29[2, 6, 10, 14, 21, 27, 33, 39, 49, 59, 66, 73, 78, 83] = @42) */
  for (cii=casadi_s18, rr=w29, cs=w42; cii!=casadi_s18+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #260: @18 = ones(14x1,3nz) */
  casadi_fill(w18, 3, 1.);
  /* #261: {NULL, @36, @44, NULL, @11, NULL} = vertsplit(@18) */
  w36 = w18[0];
  w44 = w18[1];
  w11 = w18[2];
  /* #262: @28 = vertcat(@43, @36) */
  rr=(&w28);
  *rr++ = w36;
  /* #263: @28 = @28' */
  /* #264: @17 = mac(@28,@16,@12) */
  casadi_copy(w12, 4, w17);
  casadi_mtimes((&w28), casadi_s19, wr16, casadi_s1, w17, casadi_s0, w, 0);
  /* #265: @17 = @17' */
  /* #266: @12 = mac(@28,@24,@12) */
  casadi_mtimes((&w28), casadi_s19, w24, casadi_s1, w12, casadi_s0, w, 0);
  /* #267: @12 = @12' */
  /* #268: @17 = (@17+@12) */
  for (i=0, rr=w17, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #269: {@28, @18} = vertsplit(@17) */
  w28 = w17[0];
  casadi_copy(w17+1, 3, w18);
  /* #270: @36 = vertcat(@44, @32) */
  rr=(&w36);
  *rr++ = w44;
  /* #271: @36 = @36' */
  /* #272: @10 = mac(@36,@9,@3) */
  casadi_copy(w03, 6, w10);
  casadi_mtimes((&w36), casadi_s20, wr09, casadi_s4, w10, casadi_s3, w, 0);
  /* #273: @10 = @10' */
  /* #274: @10 = (@1*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #275: @36 = (@1*@36) */
  w36  = (w01*w36);
  /* #276: @7 = mac(@36,@25,@3) */
  casadi_copy(w03, 6, w07);
  casadi_mtimes((&w36), casadi_s20, w25, casadi_s4, w07, casadi_s3, w, 0);
  /* #277: @7 = @7' */
  /* #278: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<6; ++i) (*rr++) += (*cs++);
  /* #279: {@23, @38} = vertsplit(@10) */
  casadi_copy(w10, 3, w23);
  casadi_copy(w10+3, 3, w38);
  /* #280: @36 = (@2*@11) */
  w36  = (w02*w11);
  /* #281: @35 = (@6*@36) */
  for (i=0, rr=w35, cr=wr06; i<3; ++i) (*rr++)  = ((*cr++)*w36);
  /* #282: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #283: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #284: @44 = dot(@19, @35) */
  w44 = casadi_dot(3, w19, w35);
  /* #285: @44 = (@44/@22) */
  w44 /= w22;
  /* #286: @26 = (@5*@44) */
  for (i=0, rr=w26, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #287: @26 = (2.*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #288: @4 = (@21*@35) */
  for (i=0, rr=w04, cs=w35; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #289: @4 = (@20*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #290: @26 = (@26+@4) */
  for (i=0, rr=w26, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #291: @26 = (@26+@38) */
  for (i=0, rr=w26, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #292: @44 = (@2/@13) */
  w44  = (w02/w13);
  /* #293: @44 = (@44*@11) */
  w44 *= w11;
  /* #294: @44 = (-@44) */
  w44 = (- w44 );
  /* #295: @36 = (@36/@13) */
  w36 /= w13;
  /* #296: @44 = (@44-@36) */
  w44 -= w36;
  /* #297: @27 = (@27*@44) */
  w27 *= w44;
  /* #298: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #299: @44 = dot(@6, @35) */
  w44 = casadi_dot(3, wr06, w35);
  /* #300: @44 = (@2*@44) */
  w44  = (w02*w44);
  /* #301: @27 = (@27+@44) */
  w27 += w44;
  /* #302: @27 = (-@27) */
  w27 = (- w27 );
  /* #303: @42 = vertcat(@28, @18, @23, @26, @27, @35) */
  rr=w42;
  *rr++ = w28;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  *rr++ = w27;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  /* #304: @45 = @42[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s21, rr=w45, cs=w42; cii!=casadi_s21+11; ++cii) *rr++ = cs[*cii];
  /* #305: (@29[12, 13, 14, 15, 16, 17, 18, 67, 68, 69, 70] = @45) */
  for (cii=casadi_s22, rr=w29, cs=w45; cii!=casadi_s22+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #306: (@29[3, 7, 11, 15, 16, 22, 28, 67, 74, 79, 84] = @45) */
  for (cii=casadi_s23, rr=w29, cs=w45; cii!=casadi_s23+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #307: @17 = ones(14x1,4nz) */
  casadi_fill(w17, 4, 1.);
  /* #308: {NULL, NULL, @28, NULL, NULL, @18} = vertsplit(@17) */
  w28 = w17[0];
  casadi_copy(w17+1, 3, w18);
  /* #309: @27 = vertcat(@28, @32) */
  rr=(&w27);
  *rr++ = w28;
  /* #310: @27 = @27' */
  /* #311: @10 = mac(@27,@9,@3) */
  casadi_copy(w03, 6, w10);
  casadi_mtimes((&w27), casadi_s24, wr09, casadi_s4, w10, casadi_s3, w, 0);
  /* #312: @10 = @10' */
  /* #313: @10 = (@1*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #314: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #315: @7 = mac(@27,@25,@3) */
  casadi_copy(w03, 6, w07);
  casadi_mtimes((&w27), casadi_s24, w25, casadi_s4, w07, casadi_s3, w, 0);
  /* #316: @7 = @7' */
  /* #317: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<6; ++i) (*rr++) += (*cs++);
  /* #318: {@23, @26} = vertsplit(@10) */
  casadi_copy(w10, 3, w23);
  casadi_copy(w10+3, 3, w26);
  /* #319: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #320: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #321: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #322: @27 = dot(@19, @18) */
  w27 = casadi_dot(3, w19, w18);
  /* #323: @27 = (@27/@22) */
  w27 /= w22;
  /* #324: @5 = (@5*@27) */
  for (i=0, rr=w05; i<3; ++i) (*rr++) *= w27;
  /* #325: @5 = (2.*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #326: @19 = (@21*@18) */
  for (i=0, rr=w19, cs=w18; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #327: @19 = (@20*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #328: @5 = (@5+@19) */
  for (i=0, rr=w05, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #329: @5 = (@5+@26) */
  for (i=0, rr=w05, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #330: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #331: @20 = dot(@6, @18) */
  w20 = casadi_dot(3, wr06, w18);
  /* #332: @2 = (@2*@20) */
  w02 *= w20;
  /* #333: @2 = (-@2) */
  w02 = (- w02 );
  /* #334: @46 = vertcat(@43, @32, @23, @5, @2, @18) */
  rr=w46;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  *rr++ = w02;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #335: @10 = @46[:14:7;:3] */
  for (rr=w10, cs=w46+0; cs!=w46+14; cs+=7) for (ct=cs+0; ct!=cs+3; ct+=1) *rr++ = *ct;
  /* #336: (@29[22, 23, 24, 75, 80, 85] = @10) */
  for (cii=casadi_s25, rr=w29, cs=w10; cii!=casadi_s25+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #337: (@29[17, 23, 29, 75, 80, 85] = @10) */
  for (cii=casadi_s26, rr=w29, cs=w10; cii!=casadi_s26+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #338: @2 = ones(14x1,1nz) */
  w02 = 1.;
  /* #339: {NULL, NULL, @20, NULL, NULL, NULL} = vertsplit(@2) */
  w20 = w02;
  /* #340: @2 = vertcat(@20, @32) */
  rr=(&w02);
  *rr++ = w20;
  /* #341: @2 = @2' */
  /* #342: @10 = mac(@2,@9,@3) */
  casadi_copy(w03, 6, w10);
  casadi_mtimes((&w02), casadi_s27, wr09, casadi_s4, w10, casadi_s3, w, 0);
  /* #343: @10 = @10' */
  /* #344: @10 = (@1*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #345: @1 = (@1*@2) */
  w01 *= w02;
  /* #346: @3 = mac(@1,@25,@3) */
  casadi_mtimes((&w01), casadi_s27, w25, casadi_s4, w03, casadi_s3, w, 0);
  /* #347: @3 = @3' */
  /* #348: @10 = (@10+@3) */
  for (i=0, rr=w10, cs=w03; i<6; ++i) (*rr++) += (*cs++);
  /* #349: {@23, @5} = vertsplit(@10) */
  casadi_copy(w10, 3, w23);
  casadi_copy(w10+3, 3, w05);
  /* #350: @10 = vertcat(@43, @32, @23, @5, @43, @32) */
  rr=w10;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  /* #351: @3 = @10[:6] */
  for (rr=w03, cs=w10+0; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #352: (@29[28:34] = @3) */
  for (rr=w29+28, cs=w03; rr!=w29+34; rr+=1) *rr = *cs++;
  /* #353: (@29[18, 24, 30, 36, 46, 56] = @3) */
  for (cii=casadi_s28, rr=w29, cs=w03; cii!=casadi_s28+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #354: @47 = @29' */
  casadi_trans(w29,casadi_s29, w47, casadi_s29, iw);
  /* #355: output[2][0] = @47 */
  casadi_copy(w47, 86, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s30;
    case 1: return casadi_s31;
    case 2: return casadi_s32;
    case 3: return casadi_s33;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s34;
    case 1: return casadi_s35;
    case 2: return casadi_s29;
    case 3: return casadi_s36;
    case 4: return casadi_s37;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 15;
  if (sz_w) *sz_w = 438;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 15*sizeof(casadi_int);
  if (sz_w) *sz_w = 438*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
