/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s35 CASADI_PREFIX(s35)
#define casadi_s36 CASADI_PREFIX(s36)
#define casadi_s37 CASADI_PREFIX(s37)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[15] = 
  {1, 6, 0, 1, 2, 3, 4, 5,
  6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[45] = 
  {6, 6, 0, 6, 12, 18, 24, 30,
  36, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5};
static const casadi_int casadi_s5[10] = 
  {1, 6, 0, 0, 0, 0, 1, 1,
  1, 0};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s7[14] = 
  {0, 1, 2, 3, 34, 35, 36, 37,
  38, 39, 40, 41, 42, 43};
static const casadi_int casadi_s8[14] = 
  {0, 4, 8, 12, 19, 25, 31, 37,
  47, 57, 64, 71, 76, 81};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s10[10] = 
  {1, 6, 0, 0, 0, 0, 0, 1,
  1, 0};
static const casadi_int casadi_s11[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s12[14] = 
  {4, 5, 6, 7, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53};
static const casadi_int casadi_s13[14] = 
  {1, 5, 9, 13, 20, 26, 32, 38,
  48, 58, 65, 72, 77, 82};
static const casadi_int casadi_s14[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s15[10] = 
  {1, 6, 0, 0, 0, 0, 0, 0,
  1, 0};
static const casadi_int casadi_s16[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s17[14] = 
  {8, 9, 10, 11, 54, 55, 56, 57,
  58, 59, 60, 61, 62, 63};
static const casadi_int casadi_s18[14] = 
  {2, 6, 10, 14, 21, 27, 33, 39,
  49, 59, 66, 73, 78, 83};
static const casadi_int casadi_s19[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s20[10] = 
  {1, 6, 0, 1, 1, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s21[11] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  11, 12, 13};
static const casadi_int casadi_s22[11] = 
  {12, 13, 14, 15, 16, 17, 18, 67,
  68, 69, 70};
static const casadi_int casadi_s23[11] = 
  {3, 7, 11, 15, 16, 22, 28, 67,
  74, 79, 84};
static const casadi_int casadi_s24[10] = 
  {1, 6, 0, 0, 1, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s25[6] = {22, 23, 24, 75, 80, 85};
static const casadi_int casadi_s26[6] = {17, 23, 29, 75, 80, 85};
static const casadi_int casadi_s27[10] = 
  {1, 6, 0, 0, 0, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s28[6] = {18, 24, 30, 36, 46, 56};
static const casadi_int casadi_s29[103] = 
  {14, 14, 0, 4, 8, 12, 16, 22,
  28, 34, 44, 54, 64, 71, 76, 81,
  86, 0, 1, 2, 3, 0, 1, 2,
  3, 0, 1, 2, 3, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 4,
  5, 6, 7, 8, 9, 4, 5, 6,
  7, 8, 9, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 7, 8, 9, 10, 11, 12, 13,
  7, 8, 9, 10, 11, 7, 8, 9,
  10, 12, 7, 8, 9, 10, 13};
static const casadi_int casadi_s30[3] = {10, 1, 1};
static const casadi_int casadi_s31[3] = {4, 1, 1};
static const casadi_int casadi_s32[3] = {0, 1, 1};
static const casadi_int casadi_s33[3] = {34, 1, 1};
static const casadi_int casadi_s34[3] = {1, 1, 1};
static const casadi_int casadi_s35[3] = {14, 1, 1};
static const casadi_int casadi_s36[3] = {0, 0, 1};
static const casadi_int casadi_s37[3] = {0, 14, 1};

static const casadi_real casadi_c0[36] = 
  {50., 0., 0., 0., 0., 0., 0., 50.,
  0., 0., 0., 0., 0., 0., 50., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 10.};
static const casadi_real casadi_c1[16] = 
  {1000., 0., 0., 0., 0., 1000., 0., 0.,
  0., 0., 1000., 0., 0., 0., 0., 1000.};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess:(i0[10],i1[4],i2[0],i3[34])->(o0,o1[14],o2[14x14,86nz],o3[],o4[0x14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+8, *w04=w+45, *w05=w+48, *w06=w+51, *w07=w+57, *w09=w+99, w10, *w11=w+106, w12;
  casadi_real *w13=w+111, *w14=w+115, *w16=w+135, *w17=w+139, *w18=w+142, w19, w20, w21, *w22=w+148, *w23=w+151, *w24=w+167, *w25=w+203;
  casadi_real w26, w27, *w28=w+208, *w29=w+294, w30, w32, w33, *w34=w+299, w35, w36, *w37=w+304, w38;
  casadi_real *w39=w+308, *w40=w+311, *w41=w+314, w43, *w44=w+329, *w45=w+340, *w46=w+350;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr04, *wr05, *wr08, *wr15;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x6) */
  casadi_clear(w01, 6);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w04);
  /* #7: @5 = @3[3:6] */
  wr05 = wr03+3;
  /* #8: @5 = (@4-@5) */
  for (i=0, rr=w05, cr=w04, cs=wr05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #9: @6 = vertcat(@2, @5) */
  rr=w06;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  /* #10: @7 = @6' */
  casadi_copy(w06, 6, w07);
  /* #11: @8 = 
  [[50, 0, 0, 0, 0, 0], 
   [0, 50, 0, 0, 0, 0], 
   [0, 0, 50, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 10]] */
  wr08 = casadi_c0;
  /* #12: @9 = mac(@7,@8,@1) */
  casadi_copy(w01, 6, w09);
  for (i=0, rr=w09; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w07+j, ct=wr08+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #13: @10 = mac(@9,@6,@0) */
  casadi_copy((&w00), 1, (&w10));
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w06+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #14: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #15: @12 = input[1][0] */
  w12 = arg[1] ? arg[1][0] : 0;
  /* #16: @2 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w02);
  /* #17: @13 = vertcat(@12, @2) */
  rr=w13;
  *rr++ = w12;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  /* #18: @14 = @13' */
  casadi_copy(w13, 4, w14);
  /* #19: @15 = 
  [[1000, 0, 0, 0], 
   [0, 1000, 0, 0], 
   [0, 0, 1000, 0], 
   [0, 0, 0, 1000]] */
  wr15 = casadi_c1;
  /* #20: @16 = mac(@14,@15,@11) */
  casadi_copy(w11, 4, w16);
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w14+j, ct=wr15+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #21: @0 = mac(@16,@13,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=w13+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #22: @10 = (@10+@0) */
  w10 += w00;
  /* #23: @2 = @3[31:34] */
  wr02 = wr03+31;
  /* #24: @0 = @3[6] */
  w00 = wr03[6];
  /* #25: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @0 = (@0/@12) */
  w00 /= w12;
  /* #27: @5 = @3[7:10] */
  wr05 = wr03+7;
  /* #28: @17 = (@0*@5) */
  for (i=0, rr=w17, cs=wr05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #29: @18 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w18);
  /* #30: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #31: @19 = @3[30] */
  w19 = wr03[30];
  /* #32: @18 = (@19*@4) */
  for (i=0, rr=w18, cs=w04; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #33: @20 = 1e-06 */
  w20 = 9.9999999999999995e-07;
  /* #34: @21 = dot(@4, @4) */
  w21 = casadi_dot(3, w04, w04);
  /* #35: @20 = (@20+@21) */
  w20 += w21;
  /* #36: @20 = sqrt(@20) */
  w20 = sqrt( w20 );
  /* #37: @22 = (@18*@20) */
  for (i=0, rr=w22, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #38: @17 = (@17-@22) */
  for (i=0, rr=w17, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #39: @2 = (@2-@17) */
  for (i=0, rr=w02, cr=wr02, cs=w17; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #40: @21 = dot(@2, @2) */
  w21 = casadi_dot(3, w02, w02);
  /* #41: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #42: @10 = (@10+@21) */
  w10 += w21;
  /* #43: output[0][0] = @10 */
  if (res[0]) res[0][0] = w10;
  /* #44: @16 = @16' */
  /* #45: @23 = @15' */
  for (i=0, rr=w23, cs=wr15; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #46: @13 = mac(@14,@23,@11) */
  casadi_copy(w11, 4, w13);
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w14+j, ct=w23+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #47: @13 = @13' */
  /* #48: @16 = (@16+@13) */
  for (i=0, rr=w16, cs=w13; i<4; ++i) (*rr++) += (*cs++);
  /* #49: {@10, @17} = vertsplit(@16) */
  w10 = w16[0];
  casadi_copy(w16+1, 3, w17);
  /* #50: output[1][0] = @10 */
  if (res[1]) res[1][0] = w10;
  /* #51: output[1][1] = @17 */
  if (res[1]) casadi_copy(w17, 3, res[1]+1);
  /* #52: @9 = @9' */
  /* #53: @24 = @8' */
  for (i=0, rr=w24, cs=wr08; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #54: @6 = mac(@7,@24,@1) */
  casadi_copy(w01, 6, w06);
  for (i=0, rr=w06; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w07+j, ct=w24+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #55: @6 = @6' */
  /* #56: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #57: {@17, @22} = vertsplit(@9) */
  casadi_copy(w09, 3, w17);
  casadi_copy(w09+3, 3, w22);
  /* #58: output[1][2] = @17 */
  if (res[1]) casadi_copy(w17, 3, res[1]+4);
  /* #59: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #60: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #61: @10 = dot(@18, @2) */
  w10 = casadi_dot(3, w18, w02);
  /* #62: @21 = (2.*@20) */
  w21 = (2.* w20 );
  /* #63: @10 = (@10/@21) */
  w10 /= w21;
  /* #64: @17 = (@10*@4) */
  for (i=0, rr=w17, cs=w04; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #65: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #66: @25 = (@20*@2) */
  for (i=0, rr=w25, cs=w02; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #67: @25 = (@19*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #68: @17 = (@17+@25) */
  for (i=0, rr=w17, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #69: @17 = (@17+@22) */
  for (i=0, rr=w17, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #70: output[1][3] = @17 */
  if (res[1]) casadi_copy(w17, 3, res[1]+7);
  /* #71: @0 = (@0/@12) */
  w00 /= w12;
  /* #72: @17 = (-@2) */
  for (i=0, rr=w17, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #73: @26 = dot(@5, @17) */
  w26 = casadi_dot(3, wr05, w17);
  /* #74: @27 = (@0*@26) */
  w27  = (w00*w26);
  /* #75: @27 = (-@27) */
  w27 = (- w27 );
  /* #76: output[1][4] = @27 */
  if (res[1]) res[1][10] = w27;
  /* #77: output[1][5] = @17 */
  if (res[1]) casadi_copy(w17, 3, res[1]+11);
  /* #78: @28 = zeros(14x14,86nz) */
  casadi_clear(w28, 86);
  /* #79: @29 = ones(14x1,2nz) */
  casadi_fill(w29, 2, 1.);
  /* #80: {@27, NULL, NULL, @30, NULL, NULL} = vertsplit(@29) */
  w27 = w29[0];
  w30 = w29[1];
  /* #81: @31 = zeros(3x1,0nz) */
  /* #82: @32 = vertcat(@27, @31) */
  rr=(&w32);
  *rr++ = w27;
  /* #83: @32 = @32' */
  /* #84: @16 = mac(@32,@15,@11) */
  casadi_copy(w11, 4, w16);
  casadi_mtimes((&w32), casadi_s2, wr15, casadi_s1, w16, casadi_s0, w, 0);
  /* #85: @16 = @16' */
  /* #86: @13 = mac(@32,@23,@11) */
  casadi_copy(w11, 4, w13);
  casadi_mtimes((&w32), casadi_s2, w23, casadi_s1, w13, casadi_s0, w, 0);
  /* #87: @13 = @13' */
  /* #88: @16 = (@16+@13) */
  for (i=0, rr=w16, cs=w13; i<4; ++i) (*rr++) += (*cs++);
  /* #89: {@32, @17} = vertsplit(@16) */
  w32 = w16[0];
  casadi_copy(w16+1, 3, w17);
  /* #90: @27 = vertcat(@31, @30) */
  rr=(&w27);
  *rr++ = w30;
  /* #91: @27 = @27' */
  /* #92: @9 = mac(@27,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w27), casadi_s5, wr08, casadi_s4, w09, casadi_s3, w, 0);
  /* #93: @9 = @9' */
  /* #94: @6 = mac(@27,@24,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w27), casadi_s5, w24, casadi_s4, w06, casadi_s3, w, 0);
  /* #95: @6 = @6' */
  /* #96: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #97: {@22, @25} = vertsplit(@9) */
  casadi_copy(w09, 3, w22);
  casadi_copy(w09+3, 3, w25);
  /* #98: @27 = (@19*@30) */
  w27  = (w19*w30);
  /* #99: @33 = (@20*@27) */
  w33  = (w20*w27);
  /* #100: @34 = dense(@33) */
  casadi_densify((&w33), casadi_s6, w34, 0);
  /* #101: @33 = project(@4) */
  casadi_sparsify(w04, (&w33), casadi_s6, 0);
  /* #102: @35 = dot(@33, @30) */
  w35 = casadi_dot(1, (&w33), (&w30));
  /* #103: @36 = dot(@30, @33) */
  w36 = casadi_dot(1, (&w30), (&w33));
  /* #104: @35 = (@35+@36) */
  w35 += w36;
  /* #105: @35 = (@35/@21) */
  w35 /= w21;
  /* #106: @37 = (@18*@35) */
  for (i=0, rr=w37, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w35);
  /* #107: @34 = (@34+@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #108: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #109: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #110: @36 = dot(@18, @34) */
  w36 = casadi_dot(3, w18, w34);
  /* #111: @33 = project(@2) */
  casadi_sparsify(w02, (&w33), casadi_s6, 0);
  /* #112: @38 = dot(@27, @33) */
  w38 = casadi_dot(1, (&w27), (&w33));
  /* #113: @36 = (@36+@38) */
  w36 += w38;
  /* #114: @36 = (@36/@21) */
  w36 /= w21;
  /* #115: @38 = (@10/@21) */
  w38  = (w10/w21);
  /* #116: @27 = (2.*@35) */
  w27 = (2.* w35 );
  /* #117: @27 = (@38*@27) */
  w27  = (w38*w27);
  /* #118: @36 = (@36-@27) */
  w36 -= w27;
  /* #119: @37 = (@4*@36) */
  for (i=0, rr=w37, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w36);
  /* #120: @30 = (@10*@30) */
  w30  = (w10*w30);
  /* #121: @39 = dense(@30) */
  casadi_densify((&w30), casadi_s6, w39, 0);
  /* #122: @37 = (@37+@39) */
  for (i=0, rr=w37, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #123: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #124: @39 = (@2*@35) */
  for (i=0, rr=w39, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w35);
  /* #125: @40 = (@20*@34) */
  for (i=0, rr=w40, cs=w34; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #126: @39 = (@39+@40) */
  for (i=0, rr=w39, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #127: @39 = (@19*@39) */
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #128: @37 = (@37+@39) */
  for (i=0, rr=w37, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #129: @37 = (@37+@25) */
  for (i=0, rr=w37, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #130: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #131: @35 = dot(@5, @34) */
  w35 = casadi_dot(3, wr05, w34);
  /* #132: @35 = (@0*@35) */
  w35  = (w00*w35);
  /* #133: @35 = (-@35) */
  w35 = (- w35 );
  /* #134: @41 = vertcat(@32, @17, @22, @37, @35, @34) */
  rr=w41;
  *rr++ = w32;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  *rr++ = w35;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #135: (@28[0, 1, 2, 3, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43] = @41) */
  for (cii=casadi_s7, rr=w28, cs=w41; cii!=casadi_s7+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #136: (@28[0, 4, 8, 12, 19, 25, 31, 37, 47, 57, 64, 71, 76, 81] = @41) */
  for (cii=casadi_s8, rr=w28, cs=w41; cii!=casadi_s8+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #137: @42 = 00 */
  /* #138: @29 = ones(14x1,2nz) */
  casadi_fill(w29, 2, 1.);
  /* #139: {NULL, @32, NULL, @35, NULL, NULL} = vertsplit(@29) */
  w32 = w29[0];
  w35 = w29[1];
  /* #140: @30 = vertcat(@42, @32) */
  rr=(&w30);
  *rr++ = w32;
  /* #141: @30 = @30' */
  /* #142: @16 = mac(@30,@15,@11) */
  casadi_copy(w11, 4, w16);
  casadi_mtimes((&w30), casadi_s9, wr15, casadi_s1, w16, casadi_s0, w, 0);
  /* #143: @16 = @16' */
  /* #144: @13 = mac(@30,@23,@11) */
  casadi_copy(w11, 4, w13);
  casadi_mtimes((&w30), casadi_s9, w23, casadi_s1, w13, casadi_s0, w, 0);
  /* #145: @13 = @13' */
  /* #146: @16 = (@16+@13) */
  for (i=0, rr=w16, cs=w13; i<4; ++i) (*rr++) += (*cs++);
  /* #147: {@30, @17} = vertsplit(@16) */
  w30 = w16[0];
  casadi_copy(w16+1, 3, w17);
  /* #148: @32 = vertcat(@31, @35) */
  rr=(&w32);
  *rr++ = w35;
  /* #149: @32 = @32' */
  /* #150: @9 = mac(@32,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w32), casadi_s10, wr08, casadi_s4, w09, casadi_s3, w, 0);
  /* #151: @9 = @9' */
  /* #152: @6 = mac(@32,@24,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w32), casadi_s10, w24, casadi_s4, w06, casadi_s3, w, 0);
  /* #153: @6 = @6' */
  /* #154: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #155: {@22, @37} = vertsplit(@9) */
  casadi_copy(w09, 3, w22);
  casadi_copy(w09+3, 3, w37);
  /* #156: @32 = (@19*@35) */
  w32  = (w19*w35);
  /* #157: @36 = (@20*@32) */
  w36  = (w20*w32);
  /* #158: @34 = dense(@36) */
  casadi_densify((&w36), casadi_s11, w34, 0);
  /* #159: @36 = project(@4) */
  casadi_sparsify(w04, (&w36), casadi_s11, 0);
  /* #160: @27 = dot(@36, @35) */
  w27 = casadi_dot(1, (&w36), (&w35));
  /* #161: @33 = dot(@35, @36) */
  w33 = casadi_dot(1, (&w35), (&w36));
  /* #162: @27 = (@27+@33) */
  w27 += w33;
  /* #163: @27 = (@27/@21) */
  w27 /= w21;
  /* #164: @25 = (@18*@27) */
  for (i=0, rr=w25, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w27);
  /* #165: @34 = (@34+@25) */
  for (i=0, rr=w34, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #166: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #167: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #168: @33 = dot(@18, @34) */
  w33 = casadi_dot(3, w18, w34);
  /* #169: @36 = project(@2) */
  casadi_sparsify(w02, (&w36), casadi_s11, 0);
  /* #170: @43 = dot(@32, @36) */
  w43 = casadi_dot(1, (&w32), (&w36));
  /* #171: @33 = (@33+@43) */
  w33 += w43;
  /* #172: @33 = (@33/@21) */
  w33 /= w21;
  /* #173: @43 = (2.*@27) */
  w43 = (2.* w27 );
  /* #174: @43 = (@38*@43) */
  w43  = (w38*w43);
  /* #175: @33 = (@33-@43) */
  w33 -= w43;
  /* #176: @25 = (@4*@33) */
  for (i=0, rr=w25, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w33);
  /* #177: @35 = (@10*@35) */
  w35  = (w10*w35);
  /* #178: @39 = dense(@35) */
  casadi_densify((&w35), casadi_s11, w39, 0);
  /* #179: @25 = (@25+@39) */
  for (i=0, rr=w25, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #180: @25 = (2.*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #181: @39 = (@2*@27) */
  for (i=0, rr=w39, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w27);
  /* #182: @40 = (@20*@34) */
  for (i=0, rr=w40, cs=w34; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #183: @39 = (@39+@40) */
  for (i=0, rr=w39, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #184: @39 = (@19*@39) */
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #185: @25 = (@25+@39) */
  for (i=0, rr=w25, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #186: @25 = (@25+@37) */
  for (i=0, rr=w25, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #187: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #188: @27 = dot(@5, @34) */
  w27 = casadi_dot(3, wr05, w34);
  /* #189: @27 = (@0*@27) */
  w27  = (w00*w27);
  /* #190: @27 = (-@27) */
  w27 = (- w27 );
  /* #191: @41 = vertcat(@30, @17, @22, @25, @27, @34) */
  rr=w41;
  *rr++ = w30;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  *rr++ = w27;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #192: (@28[4, 5, 6, 7, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53] = @41) */
  for (cii=casadi_s12, rr=w28, cs=w41; cii!=casadi_s12+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #193: (@28[1, 5, 9, 13, 20, 26, 32, 38, 48, 58, 65, 72, 77, 82] = @41) */
  for (cii=casadi_s13, rr=w28, cs=w41; cii!=casadi_s13+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #194: @29 = ones(14x1,2nz) */
  casadi_fill(w29, 2, 1.);
  /* #195: {NULL, @30, NULL, @27, NULL, NULL} = vertsplit(@29) */
  w30 = w29[0];
  w27 = w29[1];
  /* #196: @35 = vertcat(@42, @30) */
  rr=(&w35);
  *rr++ = w30;
  /* #197: @35 = @35' */
  /* #198: @16 = mac(@35,@15,@11) */
  casadi_copy(w11, 4, w16);
  casadi_mtimes((&w35), casadi_s14, wr15, casadi_s1, w16, casadi_s0, w, 0);
  /* #199: @16 = @16' */
  /* #200: @13 = mac(@35,@23,@11) */
  casadi_copy(w11, 4, w13);
  casadi_mtimes((&w35), casadi_s14, w23, casadi_s1, w13, casadi_s0, w, 0);
  /* #201: @13 = @13' */
  /* #202: @16 = (@16+@13) */
  for (i=0, rr=w16, cs=w13; i<4; ++i) (*rr++) += (*cs++);
  /* #203: {@35, @17} = vertsplit(@16) */
  w35 = w16[0];
  casadi_copy(w16+1, 3, w17);
  /* #204: @30 = vertcat(@31, @27) */
  rr=(&w30);
  *rr++ = w27;
  /* #205: @30 = @30' */
  /* #206: @9 = mac(@30,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w30), casadi_s15, wr08, casadi_s4, w09, casadi_s3, w, 0);
  /* #207: @9 = @9' */
  /* #208: @6 = mac(@30,@24,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w30), casadi_s15, w24, casadi_s4, w06, casadi_s3, w, 0);
  /* #209: @6 = @6' */
  /* #210: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #211: {@22, @25} = vertsplit(@9) */
  casadi_copy(w09, 3, w22);
  casadi_copy(w09+3, 3, w25);
  /* #212: @30 = (@19*@27) */
  w30  = (w19*w27);
  /* #213: @33 = (@20*@30) */
  w33  = (w20*w30);
  /* #214: @34 = dense(@33) */
  casadi_densify((&w33), casadi_s16, w34, 0);
  /* #215: @33 = project(@4) */
  casadi_sparsify(w04, (&w33), casadi_s16, 0);
  /* #216: @43 = dot(@33, @27) */
  w43 = casadi_dot(1, (&w33), (&w27));
  /* #217: @32 = dot(@27, @33) */
  w32 = casadi_dot(1, (&w27), (&w33));
  /* #218: @43 = (@43+@32) */
  w43 += w32;
  /* #219: @43 = (@43/@21) */
  w43 /= w21;
  /* #220: @37 = (@18*@43) */
  for (i=0, rr=w37, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #221: @34 = (@34+@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #222: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #223: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #224: @32 = dot(@18, @34) */
  w32 = casadi_dot(3, w18, w34);
  /* #225: @33 = project(@2) */
  casadi_sparsify(w02, (&w33), casadi_s16, 0);
  /* #226: @36 = dot(@30, @33) */
  w36 = casadi_dot(1, (&w30), (&w33));
  /* #227: @32 = (@32+@36) */
  w32 += w36;
  /* #228: @32 = (@32/@21) */
  w32 /= w21;
  /* #229: @36 = (2.*@43) */
  w36 = (2.* w43 );
  /* #230: @38 = (@38*@36) */
  w38 *= w36;
  /* #231: @32 = (@32-@38) */
  w32 -= w38;
  /* #232: @37 = (@4*@32) */
  for (i=0, rr=w37, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w32);
  /* #233: @10 = (@10*@27) */
  w10 *= w27;
  /* #234: @39 = dense(@10) */
  casadi_densify((&w10), casadi_s16, w39, 0);
  /* #235: @37 = (@37+@39) */
  for (i=0, rr=w37, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #236: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #237: @2 = (@2*@43) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w43;
  /* #238: @39 = (@20*@34) */
  for (i=0, rr=w39, cs=w34; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #239: @2 = (@2+@39) */
  for (i=0, rr=w02, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #240: @2 = (@19*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #241: @37 = (@37+@2) */
  for (i=0, rr=w37, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #242: @37 = (@37+@25) */
  for (i=0, rr=w37, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #243: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #244: @43 = dot(@5, @34) */
  w43 = casadi_dot(3, wr05, w34);
  /* #245: @43 = (@0*@43) */
  w43  = (w00*w43);
  /* #246: @43 = (-@43) */
  w43 = (- w43 );
  /* #247: @41 = vertcat(@35, @17, @22, @37, @43, @34) */
  rr=w41;
  *rr++ = w35;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  *rr++ = w43;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #248: (@28[8, 9, 10, 11, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63] = @41) */
  for (cii=casadi_s17, rr=w28, cs=w41; cii!=casadi_s17+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #249: (@28[2, 6, 10, 14, 21, 27, 33, 39, 49, 59, 66, 73, 78, 83] = @41) */
  for (cii=casadi_s18, rr=w28, cs=w41; cii!=casadi_s18+14; ++cii, ++cs) rr[*cii] = *cs;
  /* #250: @17 = ones(14x1,3nz) */
  casadi_fill(w17, 3, 1.);
  /* #251: {NULL, @35, @43, NULL, @10, NULL} = vertsplit(@17) */
  w35 = w17[0];
  w43 = w17[1];
  w10 = w17[2];
  /* #252: @27 = vertcat(@42, @35) */
  rr=(&w27);
  *rr++ = w35;
  /* #253: @27 = @27' */
  /* #254: @16 = mac(@27,@15,@11) */
  casadi_copy(w11, 4, w16);
  casadi_mtimes((&w27), casadi_s19, wr15, casadi_s1, w16, casadi_s0, w, 0);
  /* #255: @16 = @16' */
  /* #256: @11 = mac(@27,@23,@11) */
  casadi_mtimes((&w27), casadi_s19, w23, casadi_s1, w11, casadi_s0, w, 0);
  /* #257: @11 = @11' */
  /* #258: @16 = (@16+@11) */
  for (i=0, rr=w16, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #259: {@27, @17} = vertsplit(@16) */
  w27 = w16[0];
  casadi_copy(w16+1, 3, w17);
  /* #260: @35 = vertcat(@43, @31) */
  rr=(&w35);
  *rr++ = w43;
  /* #261: @35 = @35' */
  /* #262: @9 = mac(@35,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w35), casadi_s20, wr08, casadi_s4, w09, casadi_s3, w, 0);
  /* #263: @9 = @9' */
  /* #264: @6 = mac(@35,@24,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w35), casadi_s20, w24, casadi_s4, w06, casadi_s3, w, 0);
  /* #265: @6 = @6' */
  /* #266: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #267: {@22, @37} = vertsplit(@9) */
  casadi_copy(w09, 3, w22);
  casadi_copy(w09+3, 3, w37);
  /* #268: @35 = (@0*@10) */
  w35  = (w00*w10);
  /* #269: @34 = (@5*@35) */
  for (i=0, rr=w34, cr=wr05; i<3; ++i) (*rr++)  = ((*cr++)*w35);
  /* #270: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #271: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #272: @43 = dot(@18, @34) */
  w43 = casadi_dot(3, w18, w34);
  /* #273: @43 = (@43/@21) */
  w43 /= w21;
  /* #274: @25 = (@4*@43) */
  for (i=0, rr=w25, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #275: @25 = (2.*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #276: @2 = (@20*@34) */
  for (i=0, rr=w02, cs=w34; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #277: @2 = (@19*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #278: @25 = (@25+@2) */
  for (i=0, rr=w25, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #279: @25 = (@25+@37) */
  for (i=0, rr=w25, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #280: @43 = (@0/@12) */
  w43  = (w00/w12);
  /* #281: @43 = (@43*@10) */
  w43 *= w10;
  /* #282: @43 = (-@43) */
  w43 = (- w43 );
  /* #283: @35 = (@35/@12) */
  w35 /= w12;
  /* #284: @43 = (@43-@35) */
  w43 -= w35;
  /* #285: @26 = (@26*@43) */
  w26 *= w43;
  /* #286: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #287: @43 = dot(@5, @34) */
  w43 = casadi_dot(3, wr05, w34);
  /* #288: @43 = (@0*@43) */
  w43  = (w00*w43);
  /* #289: @26 = (@26+@43) */
  w26 += w43;
  /* #290: @26 = (-@26) */
  w26 = (- w26 );
  /* #291: @41 = vertcat(@27, @17, @22, @25, @26, @34) */
  rr=w41;
  *rr++ = w27;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  *rr++ = w26;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #292: @44 = @41[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s21, rr=w44, cs=w41; cii!=casadi_s21+11; ++cii) *rr++ = cs[*cii];
  /* #293: (@28[12, 13, 14, 15, 16, 17, 18, 67, 68, 69, 70] = @44) */
  for (cii=casadi_s22, rr=w28, cs=w44; cii!=casadi_s22+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #294: (@28[3, 7, 11, 15, 16, 22, 28, 67, 74, 79, 84] = @44) */
  for (cii=casadi_s23, rr=w28, cs=w44; cii!=casadi_s23+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #295: @16 = ones(14x1,4nz) */
  casadi_fill(w16, 4, 1.);
  /* #296: {NULL, NULL, @27, NULL, NULL, @17} = vertsplit(@16) */
  w27 = w16[0];
  casadi_copy(w16+1, 3, w17);
  /* #297: @26 = vertcat(@27, @31) */
  rr=(&w26);
  *rr++ = w27;
  /* #298: @26 = @26' */
  /* #299: @9 = mac(@26,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w26), casadi_s24, wr08, casadi_s4, w09, casadi_s3, w, 0);
  /* #300: @9 = @9' */
  /* #301: @6 = mac(@26,@24,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w26), casadi_s24, w24, casadi_s4, w06, casadi_s3, w, 0);
  /* #302: @6 = @6' */
  /* #303: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #304: {@22, @25} = vertsplit(@9) */
  casadi_copy(w09, 3, w22);
  casadi_copy(w09+3, 3, w25);
  /* #305: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (- *cs++ );
  /* #306: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #307: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #308: @26 = dot(@18, @17) */
  w26 = casadi_dot(3, w18, w17);
  /* #309: @26 = (@26/@21) */
  w26 /= w21;
  /* #310: @4 = (@4*@26) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) *= w26;
  /* #311: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #312: @18 = (@20*@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++)  = (w20*(*cs++));
  /* #313: @18 = (@19*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #314: @4 = (@4+@18) */
  for (i=0, rr=w04, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #315: @4 = (@4+@25) */
  for (i=0, rr=w04, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #316: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (- *cs++ );
  /* #317: @19 = dot(@5, @17) */
  w19 = casadi_dot(3, wr05, w17);
  /* #318: @0 = (@0*@19) */
  w00 *= w19;
  /* #319: @0 = (-@0) */
  w00 = (- w00 );
  /* #320: @45 = vertcat(@42, @31, @22, @4, @0, @17) */
  rr=w45;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w00;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #321: @9 = @45[:14:7;:3] */
  for (rr=w09, cs=w45+0; cs!=w45+14; cs+=7) for (ct=cs+0; ct!=cs+3; ct+=1) *rr++ = *ct;
  /* #322: (@28[22, 23, 24, 75, 80, 85] = @9) */
  for (cii=casadi_s25, rr=w28, cs=w09; cii!=casadi_s25+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #323: (@28[17, 23, 29, 75, 80, 85] = @9) */
  for (cii=casadi_s26, rr=w28, cs=w09; cii!=casadi_s26+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #324: @0 = ones(14x1,1nz) */
  w00 = 1.;
  /* #325: {NULL, NULL, @19, NULL, NULL, NULL} = vertsplit(@0) */
  w19 = w00;
  /* #326: @0 = vertcat(@19, @31) */
  rr=(&w00);
  *rr++ = w19;
  /* #327: @0 = @0' */
  /* #328: @9 = mac(@0,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w00), casadi_s27, wr08, casadi_s4, w09, casadi_s3, w, 0);
  /* #329: @9 = @9' */
  /* #330: @1 = mac(@0,@24,@1) */
  casadi_mtimes((&w00), casadi_s27, w24, casadi_s4, w01, casadi_s3, w, 0);
  /* #331: @1 = @1' */
  /* #332: @9 = (@9+@1) */
  for (i=0, rr=w09, cs=w01; i<6; ++i) (*rr++) += (*cs++);
  /* #333: {@22, @4} = vertsplit(@9) */
  casadi_copy(w09, 3, w22);
  casadi_copy(w09+3, 3, w04);
  /* #334: @9 = vertcat(@42, @31, @22, @4, @42, @31) */
  rr=w09;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  /* #335: @1 = @9[:6] */
  for (rr=w01, cs=w09+0; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #336: (@28[28:34] = @1) */
  for (rr=w28+28, cs=w01; rr!=w28+34; rr+=1) *rr = *cs++;
  /* #337: (@28[18, 24, 30, 36, 46, 56] = @1) */
  for (cii=casadi_s28, rr=w28, cs=w01; cii!=casadi_s28+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #338: @46 = @28' */
  casadi_trans(w28,casadi_s29, w46, casadi_s29, iw);
  /* #339: output[2][0] = @46 */
  casadi_copy(w46, 86, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s30;
    case 1: return casadi_s31;
    case 2: return casadi_s32;
    case 3: return casadi_s33;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s34;
    case 1: return casadi_s35;
    case 2: return casadi_s29;
    case 3: return casadi_s36;
    case 4: return casadi_s37;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 15;
  if (sz_w) *sz_w = 436;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 15*sizeof(casadi_int);
  if (sz_w) *sz_w = 436*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
