/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {35, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[36] = 
  {50., 0., 0., 0., 0., 0., 0., 50.,
  0., 0., 0., 0., 0., 0., 50., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 10.};
static const casadi_real casadi_c1[16] = 
  {1000., 0., 0., 0., 0., 1000., 0., 0.,
  0., 0., 1000., 0., 0., 0., 0., 1000.};

static const casadi_real casadi_zeros[35] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* quadrotor_mhe_trans_cost_ext_cost_fun:(i0[10],i1[4],i2[0],i3[35])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, *w03=w+38, *w04=w+44, *w05=w+47, *w06=w+50, *w07=w+53, *w08=w+59, w10, *w11=w+102, *w12=w+106;
  casadi_real *w13=w+110, *w15=w+130;
  const casadi_real *cr, *cs, *ct, *wr00, *wr04, *wr05, *wr06, *wr09, *wr14;
  /* #0: @0 = input[3][0] */
  wr00 = arg[3] ? arg[3] : casadi_zeros;
  /* #1: @1 = @0[34] */
  w01 = wr00[34];
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = zeros(1x6) */
  casadi_clear(w03, 6);
  /* #4: @4 = input[0][0] */
  casadi_copy(arg[0], 3, w04);
  /* #5: @5 = @0[:3] */
  wr05 = wr00+0;
  /* #6: @4 = (@4-@5) */
  for (i=0, rr=w04, cs=wr05; i<3; ++i) (*rr++) -= (*cs++);
  /* #7: @5 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w05);
  /* #8: @6 = @0[3:6] */
  wr06 = wr00+3;
  /* #9: @6 = (@5-@6) */
  for (i=0, rr=w06, cr=w05, cs=wr06; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #10: @7 = vertcat(@4, @6) */
  rr=w07;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  /* #11: @8 = @7' */
  casadi_copy(w07, 6, w08);
  /* #12: @9 = 
  [[50, 0, 0, 0, 0, 0], 
   [0, 50, 0, 0, 0, 0], 
   [0, 0, 50, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 10]] */
  wr09 = casadi_c0;
  /* #13: @3 = mac(@8,@9,@3) */
  for (i=0, rr=w03; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w08+j, ct=wr09+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #14: @10 = mac(@3,@7,@2) */
  casadi_copy((&w02), 1, (&w10));
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w03+j, ct=w07+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #15: @1 = (@1*@10) */
  w01 *= w10;
  /* #16: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #17: @10 = input[1][0] */
  w10 = arg[1] ? arg[1][0] : 0;
  /* #18: @4 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w04);
  /* #19: @12 = vertcat(@10, @4) */
  rr=w12;
  *rr++ = w10;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  /* #20: @13 = @12' */
  casadi_copy(w12, 4, w13);
  /* #21: @14 = 
  [[1000, 0, 0, 0], 
   [0, 1000, 0, 0], 
   [0, 0, 1000, 0], 
   [0, 0, 0, 1000]] */
  wr14 = casadi_c1;
  /* #22: @11 = mac(@13,@14,@11) */
  for (i=0, rr=w11; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w13+j, ct=wr14+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #23: @2 = mac(@11,@12,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w12+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #24: @1 = (@1+@2) */
  w01 += w02;
  /* #25: @4 = @0[31:34] */
  wr04 = wr00+31;
  /* #26: @2 = @0[6] */
  w02 = wr00[6];
  /* #27: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #28: @2 = (@2/@10) */
  w02 /= w10;
  /* #29: @6 = @0[7:10] */
  wr06 = wr00+7;
  /* #30: @6 = (@2*@6) */
  for (i=0, rr=w06, cs=wr06; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #31: @15 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w15);
  /* #32: @6 = (@6+@15) */
  for (i=0, rr=w06, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #33: @2 = @0[30] */
  w02 = wr00[30];
  /* #34: @15 = (@2*@5) */
  for (i=0, rr=w15, cs=w05; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #35: @2 = 1e-06 */
  w02 = 9.9999999999999995e-07;
  /* #36: @10 = dot(@5, @5) */
  w10 = casadi_dot(3, w05, w05);
  /* #37: @2 = (@2+@10) */
  w02 += w10;
  /* #38: @2 = sqrt(@2) */
  w02 = sqrt( w02 );
  /* #39: @15 = (@15*@2) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) *= w02;
  /* #40: @6 = (@6-@15) */
  for (i=0, rr=w06, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #41: @4 = (@4-@6) */
  for (i=0, rr=w04, cr=wr04, cs=w06; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #42: @2 = dot(@4, @4) */
  w02 = casadi_dot(3, w04, w04);
  /* #43: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #44: @1 = (@1+@2) */
  w01 += w02;
  /* #45: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 133;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 133*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
