/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {34, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[36] = 
  {50., 0., 0., 0., 0., 0., 0., 50.,
  0., 0., 0., 0., 0., 0., 50., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 10.};
static const casadi_real casadi_c1[16] = 
  {1000., 0., 0., 0., 0., 1000., 0., 0.,
  0., 0., 1000., 0., 0., 0., 0., 1000.};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_mhe_trans_cost_ext_cost_fun:(i0[10],i1[4],i2[0],i3[34])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+8, *w04=w+45, *w05=w+48, *w06=w+51, *w07=w+57, w09, *w10=w+100, w11, *w12=w+105;
  casadi_real *w13=w+109, *w15=w+129;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr04, *wr05, *wr08, *wr14;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x6) */
  casadi_clear(w01, 6);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w04);
  /* #7: @5 = @3[3:6] */
  wr05 = wr03+3;
  /* #8: @5 = (@4-@5) */
  for (i=0, rr=w05, cr=w04, cs=wr05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #9: @6 = vertcat(@2, @5) */
  rr=w06;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  /* #10: @7 = @6' */
  casadi_copy(w06, 6, w07);
  /* #11: @8 = 
  [[50, 0, 0, 0, 0, 0], 
   [0, 50, 0, 0, 0, 0], 
   [0, 0, 50, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 10]] */
  wr08 = casadi_c0;
  /* #12: @1 = mac(@7,@8,@1) */
  for (i=0, rr=w01; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w07+j, ct=wr08+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #13: @9 = mac(@1,@6,@0) */
  casadi_copy((&w00), 1, (&w09));
  for (i=0, rr=(&w09); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w06+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #14: @10 = zeros(1x4) */
  casadi_clear(w10, 4);
  /* #15: @11 = input[1][0] */
  w11 = arg[1] ? arg[1][0] : 0;
  /* #16: @2 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w02);
  /* #17: @12 = vertcat(@11, @2) */
  rr=w12;
  *rr++ = w11;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  /* #18: @13 = @12' */
  casadi_copy(w12, 4, w13);
  /* #19: @14 = 
  [[1000, 0, 0, 0], 
   [0, 1000, 0, 0], 
   [0, 0, 1000, 0], 
   [0, 0, 0, 1000]] */
  wr14 = casadi_c1;
  /* #20: @10 = mac(@13,@14,@10) */
  for (i=0, rr=w10; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w13+j, ct=wr14+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #21: @0 = mac(@10,@12,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w10+j, ct=w12+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #22: @9 = (@9+@0) */
  w09 += w00;
  /* #23: @2 = @3[31:34] */
  wr02 = wr03+31;
  /* #24: @0 = @3[6] */
  w00 = wr03[6];
  /* #25: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #26: @0 = (@0/@11) */
  w00 /= w11;
  /* #27: @5 = @3[7:10] */
  wr05 = wr03+7;
  /* #28: @5 = (@0*@5) */
  for (i=0, rr=w05, cs=wr05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #29: @15 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w15);
  /* #30: @5 = (@5+@15) */
  for (i=0, rr=w05, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #31: @0 = @3[30] */
  w00 = wr03[30];
  /* #32: @15 = (@0*@4) */
  for (i=0, rr=w15, cs=w04; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #33: @0 = 1e-06 */
  w00 = 9.9999999999999995e-07;
  /* #34: @11 = dot(@4, @4) */
  w11 = casadi_dot(3, w04, w04);
  /* #35: @0 = (@0+@11) */
  w00 += w11;
  /* #36: @0 = sqrt(@0) */
  w00 = sqrt( w00 );
  /* #37: @15 = (@15*@0) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) *= w00;
  /* #38: @5 = (@5-@15) */
  for (i=0, rr=w05, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #39: @2 = (@2-@5) */
  for (i=0, rr=w02, cr=wr02, cs=w05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #40: @0 = dot(@2, @2) */
  w00 = casadi_dot(3, w02, w02);
  /* #41: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #42: @9 = (@9+@0) */
  w09 += w00;
  /* #43: output[0][0] = @9 */
  if (res[0]) res[0][0] = w09;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
