/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[14] = 
  {14, 1, 0, 10, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {34, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};
static const casadi_int casadi_s6[3] = {14, 1, 1};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_mhe_trans_cost_ext_cost_0_fun_jac:(i0[10],i1[4],i2[0],i3[34])->(o0,o1[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w01, *w02=w+35, *w03=w+38, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, *w27=w+62, *w28=w+65, *w29=w+75;
  const casadi_real *cs, *wr00, *wr03;
  /* #0: @0 = input[3][0] */
  wr00 = arg[3] ? arg[3] : casadi_zeros;
  /* #1: @1 = @0[20] */
  w01 = wr00[20];
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = @0[10:13] */
  wr03 = wr00+10;
  /* #4: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=wr03; i<3; ++i) (*rr++) -= (*cs++);
  /* #5: @4 = @2[0] */
  for (rr=(&w04), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #6: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #7: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #8: @6 = @0[21] */
  w06 = wr00[21];
  /* #9: @7 = @2[1] */
  for (rr=(&w07), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #10: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #11: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #12: @5 = (@5+@8) */
  w05 += w08;
  /* #13: @8 = @0[22] */
  w08 = wr00[22];
  /* #14: @9 = @2[2] */
  for (rr=(&w09), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #15: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #16: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #17: @5 = (@5+@10) */
  w05 += w10;
  /* #18: @10 = @0[23] */
  w10 = wr00[23];
  /* #19: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w02);
  /* #20: @3 = @0[13:16] */
  wr03 = wr00+13;
  /* #21: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=wr03; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: @11 = @2[0] */
  for (rr=(&w11), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #23: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #24: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #25: @5 = (@5+@12) */
  w05 += w12;
  /* #26: @12 = @0[24] */
  w12 = wr00[24];
  /* #27: @13 = @2[1] */
  for (rr=(&w13), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #28: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #29: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #30: @5 = (@5+@14) */
  w05 += w14;
  /* #31: @14 = @0[25] */
  w14 = wr00[25];
  /* #32: @15 = @2[2] */
  for (rr=(&w15), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #33: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #34: @16 = (@14*@16) */
  w16  = (w14*w16);
  /* #35: @5 = (@5+@16) */
  w05 += w16;
  /* #36: @16 = @0[26] */
  w16 = wr00[26];
  /* #37: @17 = input[0][2] */
  w17 = arg[0] ? arg[0][6] : 0;
  /* #38: @18 = @0[16] */
  w18 = wr00[16];
  /* #39: @17 = (@17-@18) */
  w17 -= w18;
  /* #40: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #41: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #42: @5 = (@5+@18) */
  w05 += w18;
  /* #43: @18 = @0[27] */
  w18 = wr00[27];
  /* #44: @2 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w02);
  /* #45: @3 = @0[17:20] */
  wr03 = wr00+17;
  /* #46: @2 = (@2-@3) */
  for (i=0, rr=w02, cs=wr03; i<3; ++i) (*rr++) -= (*cs++);
  /* #47: @19 = @2[0] */
  for (rr=(&w19), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #48: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #49: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #50: @5 = (@5+@20) */
  w05 += w20;
  /* #51: @20 = @0[28] */
  w20 = wr00[28];
  /* #52: @21 = @2[1] */
  for (rr=(&w21), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #53: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #54: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #55: @5 = (@5+@22) */
  w05 += w22;
  /* #56: @22 = @0[29] */
  w22 = wr00[29];
  /* #57: @23 = @2[2] */
  for (rr=(&w23), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #58: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #59: @24 = (@22*@24) */
  w24  = (w22*w24);
  /* #60: @5 = (@5+@24) */
  w05 += w24;
  /* #61: output[0][0] = @5 */
  if (res[0]) res[0][0] = w05;
  /* #62: @25 = 00 */
  /* #63: @26 = zeros(3x1,0nz) */
  /* #64: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #65: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #66: @9 = (@9*@8) */
  w09 *= w08;
  /* #67: @3 = @2; (@3[2] += @9) */
  casadi_copy(w02, 3, w03);
  for (rr=w03+2, cs=(&w09); rr!=w03+3; rr+=1) *rr += *cs++;
  /* #68: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #69: @7 = (@7*@6) */
  w07 *= w06;
  /* #70: (@3[1] += @7) */
  for (rr=w03+1, cs=(&w07); rr!=w03+2; rr+=1) *rr += *cs++;
  /* #71: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #72: @4 = (@4*@1) */
  w04 *= w01;
  /* #73: (@3[0] += @4) */
  for (rr=w03+0, cs=(&w04); rr!=w03+1; rr+=1) *rr += *cs++;
  /* #74: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #75: @15 = (@15*@14) */
  w15 *= w14;
  /* #76: @27 = @2; (@27[2] += @15) */
  casadi_copy(w02, 3, w27);
  for (rr=w27+2, cs=(&w15); rr!=w27+3; rr+=1) *rr += *cs++;
  /* #77: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #78: @13 = (@13*@12) */
  w13 *= w12;
  /* #79: (@27[1] += @13) */
  for (rr=w27+1, cs=(&w13); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #80: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #81: @11 = (@11*@10) */
  w11 *= w10;
  /* #82: (@27[0] += @11) */
  for (rr=w27+0, cs=(&w11); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #83: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #84: @17 = (@17*@16) */
  w17 *= w16;
  /* #85: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #86: @23 = (@23*@22) */
  w23 *= w22;
  /* #87: (@2[2] += @23) */
  for (rr=w02+2, cs=(&w23); rr!=w02+3; rr+=1) *rr += *cs++;
  /* #88: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #89: @21 = (@21*@20) */
  w21 *= w20;
  /* #90: (@2[1] += @21) */
  for (rr=w02+1, cs=(&w21); rr!=w02+2; rr+=1) *rr += *cs++;
  /* #91: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #92: @19 = (@19*@18) */
  w19 *= w18;
  /* #93: (@2[0] += @19) */
  for (rr=w02+0, cs=(&w19); rr!=w02+1; rr+=1) *rr += *cs++;
  /* #94: @28 = vertcat(@25, @26, @3, @27, @17, @2) */
  rr=w28;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  *rr++ = w17;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  /* #95: @29 = dense(@28) */
  casadi_densify(w28, casadi_s0, w29, 0);
  /* #96: output[1][0] = @29 */
  casadi_copy(w29, 14, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 89;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 89*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
