/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = 
  {1, 6, 0, 1, 2, 3, 4, 5,
  6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[45] = 
  {6, 6, 0, 6, 12, 18, 24, 30,
  36, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5};
static const casadi_int casadi_s2[10] = 
  {1, 6, 0, 0, 0, 0, 1, 1,
  1, 0};
static const casadi_int casadi_s3[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s4[10] = 
  {3, 9, 15, 21, 31, 41, 48, 55,
  60, 65};
static const casadi_int casadi_s5[10] = 
  {1, 6, 0, 0, 0, 0, 0, 1,
  1, 0};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s7[10] = 
  {4, 10, 16, 22, 32, 42, 49, 56,
  61, 66};
static const casadi_int casadi_s8[10] = 
  {1, 6, 0, 0, 0, 0, 0, 0,
  1, 0};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s10[10] = 
  {5, 11, 17, 23, 33, 43, 50, 57,
  62, 67};
static const casadi_int casadi_s11[10] = 
  {1, 6, 0, 1, 1, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s12[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s13[7] = {0, 1, 2, 51, 52, 53, 54};
static const casadi_int casadi_s14[7] = {0, 6, 12, 51, 58, 63, 68};
static const casadi_int casadi_s15[10] = 
  {1, 6, 0, 0, 1, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s16[6] = {6, 7, 8, 59, 64, 69};
static const casadi_int casadi_s17[6] = {1, 7, 13, 59, 64, 69};
static const casadi_int casadi_s18[10] = 
  {1, 6, 0, 0, 0, 1, 1, 1,
  1, 0};
static const casadi_int casadi_s19[6] = {2, 8, 14, 20, 30, 40};
static const casadi_int casadi_s20[83] = 
  {10, 10, 0, 6, 12, 18, 28, 38,
  48, 55, 60, 65, 70, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 3, 4, 5,
  6, 7, 8, 9, 3, 4, 5, 6,
  7, 3, 4, 5, 6, 8, 3, 4,
  5, 6, 9};
static const casadi_int casadi_s21[3] = {10, 1, 1};
static const casadi_int casadi_s22[3] = {0, 1, 1};
static const casadi_int casadi_s23[3] = {34, 1, 1};
static const casadi_int casadi_s24[3] = {1, 1, 1};
static const casadi_int casadi_s25[3] = {0, 0, 1};
static const casadi_int casadi_s26[3] = {0, 10, 1};

static const casadi_real casadi_c0[36] = 
  {50., 0., 0., 0., 0., 0., 0., 50.,
  0., 0., 0., 0., 0., 0., 50., 0.,
  0., 0., 0., 0., 0., 10., 0., 0.,
  0., 0., 0., 0., 10., 0., 0., 0.,
  0., 0., 0., 10.};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess:(i0[10],i1[0],i2[0],i3[34])->(o0,o1[10],o2[10x10,70nz],o3[],o4[0x10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, *w02=w+8, *w04=w+45, *w05=w+48, *w06=w+51, *w07=w+57, *w09=w+99, w10, w11, *w12=w+107;
  casadi_real *w13=w+110, w14, w15, w16, *w17=w+116, *w18=w+119, *w19=w+155, w20, w21, *w22=w+160, w24, w25;
  casadi_real w26, w27, *w28=w+234, w29, *w30=w+238, *w31=w+241, *w32=w+244, w33, *w34=w+255, *w35=w+257, *w36=w+264, *w38=w+268;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr02, *wr03, *wr04, *wr05, *wr08;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x6) */
  casadi_clear(w01, 6);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 3, w02);
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[:3] */
  wr04 = wr03+0;
  /* #5: @2 = (@2-@4) */
  for (i=0, rr=w02, cs=wr04; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w04);
  /* #7: @5 = @3[3:6] */
  wr05 = wr03+3;
  /* #8: @5 = (@4-@5) */
  for (i=0, rr=w05, cr=w04, cs=wr05; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #9: @6 = vertcat(@2, @5) */
  rr=w06;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  /* #10: @7 = @6' */
  casadi_copy(w06, 6, w07);
  /* #11: @8 = 
  [[50, 0, 0, 0, 0, 0], 
   [0, 50, 0, 0, 0, 0], 
   [0, 0, 50, 0, 0, 0], 
   [0, 0, 0, 10, 0, 0], 
   [0, 0, 0, 0, 10, 0], 
   [0, 0, 0, 0, 0, 10]] */
  wr08 = casadi_c0;
  /* #12: @9 = mac(@7,@8,@1) */
  casadi_copy(w01, 6, w09);
  for (i=0, rr=w09; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w07+j, ct=wr08+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #13: @0 = mac(@9,@6,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w09+j, ct=w06+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #14: @2 = @3[31:34] */
  wr02 = wr03+31;
  /* #15: @10 = @3[6] */
  w10 = wr03[6];
  /* #16: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #17: @10 = (@10/@11) */
  w10 /= w11;
  /* #18: @5 = @3[7:10] */
  wr05 = wr03+7;
  /* #19: @12 = (@10*@5) */
  for (i=0, rr=w12, cs=wr05; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #20: @13 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w13);
  /* #21: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #22: @14 = @3[30] */
  w14 = wr03[30];
  /* #23: @13 = (@14*@4) */
  for (i=0, rr=w13, cs=w04; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #24: @15 = 1e-06 */
  w15 = 9.9999999999999995e-07;
  /* #25: @16 = dot(@4, @4) */
  w16 = casadi_dot(3, w04, w04);
  /* #26: @15 = (@15+@16) */
  w15 += w16;
  /* #27: @15 = sqrt(@15) */
  w15 = sqrt( w15 );
  /* #28: @17 = (@13*@15) */
  for (i=0, rr=w17, cr=w13; i<3; ++i) (*rr++)  = ((*cr++)*w15);
  /* #29: @12 = (@12-@17) */
  for (i=0, rr=w12, cs=w17; i<3; ++i) (*rr++) -= (*cs++);
  /* #30: @2 = (@2-@12) */
  for (i=0, rr=w02, cr=wr02, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #31: @16 = dot(@2, @2) */
  w16 = casadi_dot(3, w02, w02);
  /* #32: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #33: @0 = (@0+@16) */
  w00 += w16;
  /* #34: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #35: @9 = @9' */
  /* #36: @18 = @8' */
  for (i=0, rr=w18, cs=wr08; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #37: @6 = mac(@7,@18,@1) */
  casadi_copy(w01, 6, w06);
  for (i=0, rr=w06; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w07+j, ct=w18+i*6; k<6; ++k) *rr += cs[k*1]**ct++;
  /* #38: @6 = @6' */
  /* #39: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #40: {@12, @17} = vertsplit(@9) */
  casadi_copy(w09, 3, w12);
  casadi_copy(w09+3, 3, w17);
  /* #41: output[1][0] = @12 */
  casadi_copy(w12, 3, res[1]);
  /* #42: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #43: @2 = (2.*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #44: @0 = dot(@13, @2) */
  w00 = casadi_dot(3, w13, w02);
  /* #45: @16 = (2.*@15) */
  w16 = (2.* w15 );
  /* #46: @0 = (@0/@16) */
  w00 /= w16;
  /* #47: @12 = (@0*@4) */
  for (i=0, rr=w12, cs=w04; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #48: @12 = (2.*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #49: @19 = (@15*@2) */
  for (i=0, rr=w19, cs=w02; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #50: @19 = (@14*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #51: @12 = (@12+@19) */
  for (i=0, rr=w12, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #52: @12 = (@12+@17) */
  for (i=0, rr=w12, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #53: output[1][1] = @12 */
  if (res[1]) casadi_copy(w12, 3, res[1]+3);
  /* #54: @10 = (@10/@11) */
  w10 /= w11;
  /* #55: @12 = (-@2) */
  for (i=0, rr=w12, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #56: @20 = dot(@5, @12) */
  w20 = casadi_dot(3, wr05, w12);
  /* #57: @21 = (@10*@20) */
  w21  = (w10*w20);
  /* #58: @21 = (-@21) */
  w21 = (- w21 );
  /* #59: output[1][2] = @21 */
  if (res[1]) res[1][6] = w21;
  /* #60: output[1][3] = @12 */
  if (res[1]) casadi_copy(w12, 3, res[1]+7);
  /* #61: @22 = zeros(10x10,70nz) */
  casadi_clear(w22, 70);
  /* #62: @23 = zeros(3x1,0nz) */
  /* #63: @21 = ones(10x1,1nz) */
  w21 = 1.;
  /* #64: {NULL, @24, NULL, NULL} = vertsplit(@21) */
  w24 = w21;
  /* #65: @21 = vertcat(@23, @24) */
  rr=(&w21);
  *rr++ = w24;
  /* #66: @21 = @21' */
  /* #67: @9 = mac(@21,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w21), casadi_s2, wr08, casadi_s1, w09, casadi_s0, w, 0);
  /* #68: @9 = @9' */
  /* #69: @6 = mac(@21,@18,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w21), casadi_s2, w18, casadi_s1, w06, casadi_s0, w, 0);
  /* #70: @6 = @6' */
  /* #71: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #72: {@12, @17} = vertsplit(@9) */
  casadi_copy(w09, 3, w12);
  casadi_copy(w09+3, 3, w17);
  /* #73: @21 = (@14*@24) */
  w21  = (w14*w24);
  /* #74: @25 = (@15*@21) */
  w25  = (w15*w21);
  /* #75: @19 = dense(@25) */
  casadi_densify((&w25), casadi_s3, w19, 0);
  /* #76: @25 = project(@4) */
  casadi_sparsify(w04, (&w25), casadi_s3, 0);
  /* #77: @26 = dot(@25, @24) */
  w26 = casadi_dot(1, (&w25), (&w24));
  /* #78: @27 = dot(@24, @25) */
  w27 = casadi_dot(1, (&w24), (&w25));
  /* #79: @26 = (@26+@27) */
  w26 += w27;
  /* #80: @26 = (@26/@16) */
  w26 /= w16;
  /* #81: @28 = (@13*@26) */
  for (i=0, rr=w28, cr=w13; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #82: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #83: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #84: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #85: @27 = dot(@13, @19) */
  w27 = casadi_dot(3, w13, w19);
  /* #86: @25 = project(@2) */
  casadi_sparsify(w02, (&w25), casadi_s3, 0);
  /* #87: @29 = dot(@21, @25) */
  w29 = casadi_dot(1, (&w21), (&w25));
  /* #88: @27 = (@27+@29) */
  w27 += w29;
  /* #89: @27 = (@27/@16) */
  w27 /= w16;
  /* #90: @29 = (@0/@16) */
  w29  = (w00/w16);
  /* #91: @21 = (2.*@26) */
  w21 = (2.* w26 );
  /* #92: @21 = (@29*@21) */
  w21  = (w29*w21);
  /* #93: @27 = (@27-@21) */
  w27 -= w21;
  /* #94: @28 = (@4*@27) */
  for (i=0, rr=w28, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w27);
  /* #95: @24 = (@0*@24) */
  w24  = (w00*w24);
  /* #96: @30 = dense(@24) */
  casadi_densify((&w24), casadi_s3, w30, 0);
  /* #97: @28 = (@28+@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #98: @28 = (2.*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #99: @30 = (@2*@26) */
  for (i=0, rr=w30, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #100: @31 = (@15*@19) */
  for (i=0, rr=w31, cs=w19; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #101: @30 = (@30+@31) */
  for (i=0, rr=w30, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #102: @30 = (@14*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #103: @28 = (@28+@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #104: @28 = (@28+@17) */
  for (i=0, rr=w28, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #105: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #106: @26 = dot(@5, @19) */
  w26 = casadi_dot(3, wr05, w19);
  /* #107: @26 = (@10*@26) */
  w26  = (w10*w26);
  /* #108: @26 = (-@26) */
  w26 = (- w26 );
  /* #109: @32 = vertcat(@12, @28, @26, @19) */
  rr=w32;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  *rr++ = w26;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #110: (@22[18:28] = @32) */
  for (rr=w22+18, cs=w32; rr!=w22+28; rr+=1) *rr = *cs++;
  /* #111: (@22[3, 9, 15, 21, 31, 41, 48, 55, 60, 65] = @32) */
  for (cii=casadi_s4, rr=w22, cs=w32; cii!=casadi_s4+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #112: @26 = ones(10x1,1nz) */
  w26 = 1.;
  /* #113: {NULL, @24, NULL, NULL} = vertsplit(@26) */
  w24 = w26;
  /* #114: @26 = vertcat(@23, @24) */
  rr=(&w26);
  *rr++ = w24;
  /* #115: @26 = @26' */
  /* #116: @9 = mac(@26,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w26), casadi_s5, wr08, casadi_s1, w09, casadi_s0, w, 0);
  /* #117: @9 = @9' */
  /* #118: @6 = mac(@26,@18,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w26), casadi_s5, w18, casadi_s1, w06, casadi_s0, w, 0);
  /* #119: @6 = @6' */
  /* #120: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #121: {@12, @28} = vertsplit(@9) */
  casadi_copy(w09, 3, w12);
  casadi_copy(w09+3, 3, w28);
  /* #122: @26 = (@14*@24) */
  w26  = (w14*w24);
  /* #123: @27 = (@15*@26) */
  w27  = (w15*w26);
  /* #124: @19 = dense(@27) */
  casadi_densify((&w27), casadi_s6, w19, 0);
  /* #125: @27 = project(@4) */
  casadi_sparsify(w04, (&w27), casadi_s6, 0);
  /* #126: @21 = dot(@27, @24) */
  w21 = casadi_dot(1, (&w27), (&w24));
  /* #127: @25 = dot(@24, @27) */
  w25 = casadi_dot(1, (&w24), (&w27));
  /* #128: @21 = (@21+@25) */
  w21 += w25;
  /* #129: @21 = (@21/@16) */
  w21 /= w16;
  /* #130: @17 = (@13*@21) */
  for (i=0, rr=w17, cr=w13; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #131: @19 = (@19+@17) */
  for (i=0, rr=w19, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #132: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #133: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #134: @25 = dot(@13, @19) */
  w25 = casadi_dot(3, w13, w19);
  /* #135: @27 = project(@2) */
  casadi_sparsify(w02, (&w27), casadi_s6, 0);
  /* #136: @33 = dot(@26, @27) */
  w33 = casadi_dot(1, (&w26), (&w27));
  /* #137: @25 = (@25+@33) */
  w25 += w33;
  /* #138: @25 = (@25/@16) */
  w25 /= w16;
  /* #139: @33 = (2.*@21) */
  w33 = (2.* w21 );
  /* #140: @33 = (@29*@33) */
  w33  = (w29*w33);
  /* #141: @25 = (@25-@33) */
  w25 -= w33;
  /* #142: @17 = (@4*@25) */
  for (i=0, rr=w17, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #143: @24 = (@0*@24) */
  w24  = (w00*w24);
  /* #144: @30 = dense(@24) */
  casadi_densify((&w24), casadi_s6, w30, 0);
  /* #145: @17 = (@17+@30) */
  for (i=0, rr=w17, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #146: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #147: @30 = (@2*@21) */
  for (i=0, rr=w30, cr=w02; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #148: @31 = (@15*@19) */
  for (i=0, rr=w31, cs=w19; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #149: @30 = (@30+@31) */
  for (i=0, rr=w30, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #150: @30 = (@14*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #151: @17 = (@17+@30) */
  for (i=0, rr=w17, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #152: @17 = (@17+@28) */
  for (i=0, rr=w17, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #153: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #154: @21 = dot(@5, @19) */
  w21 = casadi_dot(3, wr05, w19);
  /* #155: @21 = (@10*@21) */
  w21  = (w10*w21);
  /* #156: @21 = (-@21) */
  w21 = (- w21 );
  /* #157: @32 = vertcat(@12, @17, @21, @19) */
  rr=w32;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  *rr++ = w21;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #158: (@22[28:38] = @32) */
  for (rr=w22+28, cs=w32; rr!=w22+38; rr+=1) *rr = *cs++;
  /* #159: (@22[4, 10, 16, 22, 32, 42, 49, 56, 61, 66] = @32) */
  for (cii=casadi_s7, rr=w22, cs=w32; cii!=casadi_s7+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #160: @21 = ones(10x1,1nz) */
  w21 = 1.;
  /* #161: {NULL, @24, NULL, NULL} = vertsplit(@21) */
  w24 = w21;
  /* #162: @21 = vertcat(@23, @24) */
  rr=(&w21);
  *rr++ = w24;
  /* #163: @21 = @21' */
  /* #164: @9 = mac(@21,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w21), casadi_s8, wr08, casadi_s1, w09, casadi_s0, w, 0);
  /* #165: @9 = @9' */
  /* #166: @6 = mac(@21,@18,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w21), casadi_s8, w18, casadi_s1, w06, casadi_s0, w, 0);
  /* #167: @6 = @6' */
  /* #168: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #169: {@12, @17} = vertsplit(@9) */
  casadi_copy(w09, 3, w12);
  casadi_copy(w09+3, 3, w17);
  /* #170: @21 = (@14*@24) */
  w21  = (w14*w24);
  /* #171: @25 = (@15*@21) */
  w25  = (w15*w21);
  /* #172: @19 = dense(@25) */
  casadi_densify((&w25), casadi_s9, w19, 0);
  /* #173: @25 = project(@4) */
  casadi_sparsify(w04, (&w25), casadi_s9, 0);
  /* #174: @33 = dot(@25, @24) */
  w33 = casadi_dot(1, (&w25), (&w24));
  /* #175: @26 = dot(@24, @25) */
  w26 = casadi_dot(1, (&w24), (&w25));
  /* #176: @33 = (@33+@26) */
  w33 += w26;
  /* #177: @33 = (@33/@16) */
  w33 /= w16;
  /* #178: @28 = (@13*@33) */
  for (i=0, rr=w28, cr=w13; i<3; ++i) (*rr++)  = ((*cr++)*w33);
  /* #179: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #180: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #181: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #182: @26 = dot(@13, @19) */
  w26 = casadi_dot(3, w13, w19);
  /* #183: @25 = project(@2) */
  casadi_sparsify(w02, (&w25), casadi_s9, 0);
  /* #184: @27 = dot(@21, @25) */
  w27 = casadi_dot(1, (&w21), (&w25));
  /* #185: @26 = (@26+@27) */
  w26 += w27;
  /* #186: @26 = (@26/@16) */
  w26 /= w16;
  /* #187: @27 = (2.*@33) */
  w27 = (2.* w33 );
  /* #188: @29 = (@29*@27) */
  w29 *= w27;
  /* #189: @26 = (@26-@29) */
  w26 -= w29;
  /* #190: @28 = (@4*@26) */
  for (i=0, rr=w28, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w26);
  /* #191: @0 = (@0*@24) */
  w00 *= w24;
  /* #192: @30 = dense(@0) */
  casadi_densify((&w00), casadi_s9, w30, 0);
  /* #193: @28 = (@28+@30) */
  for (i=0, rr=w28, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #194: @28 = (2.*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #195: @2 = (@2*@33) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) *= w33;
  /* #196: @30 = (@15*@19) */
  for (i=0, rr=w30, cs=w19; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #197: @2 = (@2+@30) */
  for (i=0, rr=w02, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #198: @2 = (@14*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #199: @28 = (@28+@2) */
  for (i=0, rr=w28, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #200: @28 = (@28+@17) */
  for (i=0, rr=w28, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #201: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #202: @33 = dot(@5, @19) */
  w33 = casadi_dot(3, wr05, w19);
  /* #203: @33 = (@10*@33) */
  w33  = (w10*w33);
  /* #204: @33 = (-@33) */
  w33 = (- w33 );
  /* #205: @32 = vertcat(@12, @28, @33, @19) */
  rr=w32;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  *rr++ = w33;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #206: (@22[38:48] = @32) */
  for (rr=w22+38, cs=w32; rr!=w22+48; rr+=1) *rr = *cs++;
  /* #207: (@22[5, 11, 17, 23, 33, 43, 50, 57, 62, 67] = @32) */
  for (cii=casadi_s10, rr=w22, cs=w32; cii!=casadi_s10+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #208: @34 = ones(10x1,2nz) */
  casadi_fill(w34, 2, 1.);
  /* #209: {@33, NULL, @0, NULL} = vertsplit(@34) */
  w33 = w34[0];
  w00 = w34[1];
  /* #210: @24 = vertcat(@33, @23) */
  rr=(&w24);
  *rr++ = w33;
  /* #211: @24 = @24' */
  /* #212: @9 = mac(@24,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w24), casadi_s11, wr08, casadi_s1, w09, casadi_s0, w, 0);
  /* #213: @9 = @9' */
  /* #214: @6 = mac(@24,@18,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w24), casadi_s11, w18, casadi_s1, w06, casadi_s0, w, 0);
  /* #215: @6 = @6' */
  /* #216: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #217: {@12, @28} = vertsplit(@9) */
  casadi_copy(w09, 3, w12);
  casadi_copy(w09+3, 3, w28);
  /* #218: @24 = (@10*@0) */
  w24  = (w10*w00);
  /* #219: @19 = (@5*@24) */
  for (i=0, rr=w19, cr=wr05; i<3; ++i) (*rr++)  = ((*cr++)*w24);
  /* #220: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #221: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #222: @33 = dot(@13, @19) */
  w33 = casadi_dot(3, w13, w19);
  /* #223: @33 = (@33/@16) */
  w33 /= w16;
  /* #224: @17 = (@4*@33) */
  for (i=0, rr=w17, cr=w04; i<3; ++i) (*rr++)  = ((*cr++)*w33);
  /* #225: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #226: @2 = (@15*@19) */
  for (i=0, rr=w02, cs=w19; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #227: @2 = (@14*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #228: @17 = (@17+@2) */
  for (i=0, rr=w17, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #229: @17 = (@17+@28) */
  for (i=0, rr=w17, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #230: @33 = (@10/@11) */
  w33  = (w10/w11);
  /* #231: @33 = (@33*@0) */
  w33 *= w00;
  /* #232: @33 = (-@33) */
  w33 = (- w33 );
  /* #233: @24 = (@24/@11) */
  w24 /= w11;
  /* #234: @33 = (@33-@24) */
  w33 -= w24;
  /* #235: @20 = (@20*@33) */
  w20 *= w33;
  /* #236: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #237: @33 = dot(@5, @19) */
  w33 = casadi_dot(3, wr05, w19);
  /* #238: @33 = (@10*@33) */
  w33  = (w10*w33);
  /* #239: @20 = (@20+@33) */
  w20 += w33;
  /* #240: @20 = (-@20) */
  w20 = (- w20 );
  /* #241: @32 = vertcat(@12, @17, @20, @19) */
  rr=w32;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  *rr++ = w20;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #242: @35 = @32[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s12, rr=w35, cs=w32; cii!=casadi_s12+7; ++cii) *rr++ = cs[*cii];
  /* #243: (@22[0, 1, 2, 51, 52, 53, 54] = @35) */
  for (cii=casadi_s13, rr=w22, cs=w35; cii!=casadi_s13+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #244: (@22[0, 6, 12, 51, 58, 63, 68] = @35) */
  for (cii=casadi_s14, rr=w22, cs=w35; cii!=casadi_s14+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #245: @36 = ones(10x1,4nz) */
  casadi_fill(w36, 4, 1.);
  /* #246: {@20, NULL, NULL, @12} = vertsplit(@36) */
  w20 = w36[0];
  casadi_copy(w36+1, 3, w12);
  /* #247: @33 = vertcat(@20, @23) */
  rr=(&w33);
  *rr++ = w20;
  /* #248: @33 = @33' */
  /* #249: @9 = mac(@33,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w33), casadi_s15, wr08, casadi_s1, w09, casadi_s0, w, 0);
  /* #250: @9 = @9' */
  /* #251: @6 = mac(@33,@18,@1) */
  casadi_copy(w01, 6, w06);
  casadi_mtimes((&w33), casadi_s15, w18, casadi_s1, w06, casadi_s0, w, 0);
  /* #252: @6 = @6' */
  /* #253: @9 = (@9+@6) */
  for (i=0, rr=w09, cs=w06; i<6; ++i) (*rr++) += (*cs++);
  /* #254: {@17, @19} = vertsplit(@9) */
  casadi_copy(w09, 3, w17);
  casadi_copy(w09+3, 3, w19);
  /* #255: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) *rr++ = (- *cs++ );
  /* #256: @12 = (2.*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #257: @12 = (2.*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #258: @33 = dot(@13, @12) */
  w33 = casadi_dot(3, w13, w12);
  /* #259: @33 = (@33/@16) */
  w33 /= w16;
  /* #260: @4 = (@4*@33) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) *= w33;
  /* #261: @4 = (2.*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #262: @13 = (@15*@12) */
  for (i=0, rr=w13, cs=w12; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #263: @13 = (@14*@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #264: @4 = (@4+@13) */
  for (i=0, rr=w04, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #265: @4 = (@4+@19) */
  for (i=0, rr=w04, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #266: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) *rr++ = (- *cs++ );
  /* #267: @14 = dot(@5, @12) */
  w14 = casadi_dot(3, wr05, w12);
  /* #268: @10 = (@10*@14) */
  w10 *= w14;
  /* #269: @10 = (-@10) */
  w10 = (- w10 );
  /* #270: @32 = vertcat(@17, @4, @10, @12) */
  rr=w32;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  *rr++ = w10;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #271: @9 = @32[:14:7;:3] */
  for (rr=w09, cs=w32+0; cs!=w32+14; cs+=7) for (ct=cs+0; ct!=cs+3; ct+=1) *rr++ = *ct;
  /* #272: (@22[6, 7, 8, 59, 64, 69] = @9) */
  for (cii=casadi_s16, rr=w22, cs=w09; cii!=casadi_s16+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #273: (@22[1, 7, 13, 59, 64, 69] = @9) */
  for (cii=casadi_s17, rr=w22, cs=w09; cii!=casadi_s17+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #274: @10 = ones(10x1,1nz) */
  w10 = 1.;
  /* #275: {@14, NULL, NULL, NULL} = vertsplit(@10) */
  w14 = w10;
  /* #276: @10 = vertcat(@14, @23) */
  rr=(&w10);
  *rr++ = w14;
  /* #277: @10 = @10' */
  /* #278: @9 = mac(@10,@8,@1) */
  casadi_copy(w01, 6, w09);
  casadi_mtimes((&w10), casadi_s18, wr08, casadi_s1, w09, casadi_s0, w, 0);
  /* #279: @9 = @9' */
  /* #280: @1 = mac(@10,@18,@1) */
  casadi_mtimes((&w10), casadi_s18, w18, casadi_s1, w01, casadi_s0, w, 0);
  /* #281: @1 = @1' */
  /* #282: @9 = (@9+@1) */
  for (i=0, rr=w09, cs=w01; i<6; ++i) (*rr++) += (*cs++);
  /* #283: {@17, @4} = vertsplit(@9) */
  casadi_copy(w09, 3, w17);
  casadi_copy(w09+3, 3, w04);
  /* #284: @37 = 00 */
  /* #285: @9 = vertcat(@17, @4, @37, @23) */
  rr=w09;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  /* #286: @1 = @9[:6] */
  for (rr=w01, cs=w09+0; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #287: (@22[12:18] = @1) */
  for (rr=w22+12, cs=w01; rr!=w22+18; rr+=1) *rr = *cs++;
  /* #288: (@22[2, 8, 14, 20, 30, 40] = @1) */
  for (cii=casadi_s19, rr=w22, cs=w01; cii!=casadi_s19+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #289: @38 = @22' */
  casadi_trans(w22,casadi_s20, w38, casadi_s20, iw);
  /* #290: output[2][0] = @38 */
  casadi_copy(w38, 70, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s21;
    case 1: return casadi_s22;
    case 2: return casadi_s22;
    case 3: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s24;
    case 1: return casadi_s21;
    case 2: return casadi_s20;
    case 3: return casadi_s25;
    case 4: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 338;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mhe_trans_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 11*sizeof(casadi_int);
  if (sz_w) *sz_w = 338*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
