/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nmpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {22, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* quadrotor_nmpc_expl_ode_fun:(i0[13],i1[4],i2[22])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+3, *w01=w+6, *w02=w+15, *w03=w+24, w04, w05, *w06=w+30, w07, w08, *w09=w+41, *w10=w+50;
  casadi_real w11, *w12=w+55, w14, w15, w16, w17, w18, w19, w20;
  const casadi_real *cr, *cs, *ct, *wr01, *wr12, *wr13;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #3: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr01 = casadi_c0;
  /* #4: @2 = zeros(3x3) */
  casadi_clear(w02, 9);
  /* #5: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w03);
  /* #6: @4 = @3[3] */
  for (rr=(&w04), cs=w03+3; cs!=w03+4; cs+=1) *rr++ = *cs;
  /* #7: @5 = (-@4) */
  w05 = (- w04 );
  /* #8: @6 = @2; (@6[3] = @5) */
  casadi_copy(w02, 9, w06);
  for (rr=w06+3, cs=(&w05); rr!=w06+4; rr+=1) *rr = *cs++;
  /* #9: @5 = @3[2] */
  for (rr=(&w05), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #10: (@6[6] = @5) */
  for (rr=w06+6, cs=(&w05); rr!=w06+7; rr+=1) *rr = *cs++;
  /* #11: (@6[1] = @4) */
  for (rr=w06+1, cs=(&w04); rr!=w06+2; rr+=1) *rr = *cs++;
  /* #12: @7 = @3[1] */
  for (rr=(&w07), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #13: @8 = (-@7) */
  w08 = (- w07 );
  /* #14: (@6[7] = @8) */
  for (rr=w06+7, cs=(&w08); rr!=w06+8; rr+=1) *rr = *cs++;
  /* #15: @8 = (-@5) */
  w08 = (- w05 );
  /* #16: (@6[2] = @8) */
  for (rr=w06+2, cs=(&w08); rr!=w06+3; rr+=1) *rr = *cs++;
  /* #17: (@6[5] = @7) */
  for (rr=w06+5, cs=(&w07); rr!=w06+6; rr+=1) *rr = *cs++;
  /* #18: @9 = (2.*@6) */
  for (i=0, rr=w09, cs=w06; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #19: @2 = mac(@9,@6,@2) */
  for (i=0, rr=w02; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w09+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #20: @1 = (@1+@2) */
  for (i=0, rr=w01, cr=wr01, cs=w02; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #21: @8 = ||@3||_F */
  w08 = casadi_norm_2(4, w03);
  /* #22: @10 = (@3/@8) */
  for (i=0, rr=w10, cr=w03; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #23: @8 = @10[0] */
  for (rr=(&w08), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #24: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #25: @6 = (@8*@6) */
  for (i=0, rr=w06, cs=w06; i<9; ++i) (*rr++)  = (w08*(*cs++));
  /* #26: @1 = (@1+@6) */
  for (i=0, rr=w01, cs=w06; i<9; ++i) (*rr++) += (*cs++);
  /* #27: @8 = 0 */
  w08 = 0.;
  /* #28: @11 = input[1][0] */
  w11 = arg[1] ? arg[1][0] : 0;
  /* #29: @12 = vertcat(@8, @8, @11) */
  rr=w12;
  *rr++ = w08;
  *rr++ = w08;
  *rr++ = w11;
  /* #30: @0 = mac(@1,@12,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w01+j, ct=w12+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #31: @13 = input[2][0] */
  wr13 = arg[2] ? arg[2] : casadi_zeros;
  /* #32: @8 = @13[17] */
  w08 = wr13[17];
  /* #33: @0 = (@0/@8) */
  for (i=0, rr=w00; i<3; ++i) (*rr++) /= w08;
  /* #34: @12 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w12);
  /* #35: @8 = 9.81 */
  w08 = 9.8100000000000005e+00;
  /* #36: @12 = (@12*@8) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w08;
  /* #37: @0 = (@0-@12) */
  for (i=0, rr=w00, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #38: @12 = @13[18:21] */
  wr12 = wr13+18;
  /* #39: @0 = (@0+@12) */
  for (i=0, rr=w00, cs=wr12; i<3; ++i) (*rr++) += (*cs++);
  /* #40: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+3);
  /* #41: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #42: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w00);
  /* #43: @11 = @0[0] */
  for (rr=(&w11), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #44: @14 = (@7*@11) */
  w14  = (w07*w11);
  /* #45: @14 = (-@14) */
  w14 = (- w14 );
  /* #46: @15 = @0[1] */
  for (rr=(&w15), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #47: @16 = (@5*@15) */
  w16  = (w05*w15);
  /* #48: @14 = (@14-@16) */
  w14 -= w16;
  /* #49: @16 = @0[2] */
  for (rr=(&w16), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #50: @17 = (@4*@16) */
  w17  = (w04*w16);
  /* #51: @14 = (@14-@17) */
  w14 -= w17;
  /* #52: @17 = @3[0] */
  for (rr=(&w17), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #53: @18 = (@17*@11) */
  w18  = (w17*w11);
  /* #54: @19 = (@5*@16) */
  w19  = (w05*w16);
  /* #55: @18 = (@18+@19) */
  w18 += w19;
  /* #56: @19 = (@4*@15) */
  w19  = (w04*w15);
  /* #57: @18 = (@18-@19) */
  w18 -= w19;
  /* #58: @19 = (@17*@15) */
  w19  = (w17*w15);
  /* #59: @20 = (@7*@16) */
  w20  = (w07*w16);
  /* #60: @19 = (@19-@20) */
  w19 -= w20;
  /* #61: @4 = (@4*@11) */
  w04 *= w11;
  /* #62: @19 = (@19+@4) */
  w19 += w04;
  /* #63: @17 = (@17*@16) */
  w17 *= w16;
  /* #64: @7 = (@7*@15) */
  w07 *= w15;
  /* #65: @17 = (@17+@7) */
  w17 += w07;
  /* #66: @5 = (@5*@11) */
  w05 *= w11;
  /* #67: @17 = (@17-@5) */
  w17 -= w05;
  /* #68: @3 = vertcat(@14, @18, @19, @17) */
  rr=w03;
  *rr++ = w14;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w17;
  /* #69: @3 = (@8*@3) */
  for (i=0, rr=w03, cs=w03; i<4; ++i) (*rr++)  = (w08*(*cs++));
  /* #70: output[0][2] = @3 */
  if (res[0]) casadi_copy(w03, 4, res[0]+6);
  /* #71: @8 = @13[21] */
  w08 = wr13[21];
  /* #72: @12 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w12);
  /* #73: @12 = (@12-@0) */
  for (i=0, rr=w12, cs=w00; i<3; ++i) (*rr++) -= (*cs++);
  /* #74: @12 = (@8*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #75: output[0][3] = @12 */
  if (res[0]) casadi_copy(w12, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nmpc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 87;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 87*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
