/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_nmpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {23, 1, 1};
static const casadi_int casadi_s3[18] = 
  {17, 1, 0, 14, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* quadrotor_nmpc_expl_vde_adj:(i0[13],i1[13],i2[4],i3[23])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+16, *w02=w+19, *w03=w+22, *w04=w+26, *w05=w+29, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+42, *w16=w+51, *w17=w+55, *w18=w+59, *w19=w+68, *w20=w+77, *w21=w+86, *w22=w+95, *w23=w+104;
  casadi_real *w24=w+113, w25, w26;
  const casadi_real *cr, *cs, *ct, *wr00, *wr01, *wr02, *wr03, *wr04, *wr19;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  wr01 = wr00;
  wr02 = wr00+3;
  wr03 = wr00+6;
  wr04 = wr00+10;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #4: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w01);
  /* #5: @6 = @1[2] */
  for (rr=(&w06), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #6: @7 = 0.5 */
  w07 = 5.0000000000000000e-01;
  /* #7: @3 = (@7*@3) */
  for (i=0, rr=w03, cs=wr03; i<4; ++i) (*rr++)  = (w07*(*cs++));
  /* #8: {@7, @8, @9, @10} = vertsplit(@3) */
  w07 = w03[0];
  w08 = w03[1];
  w09 = w03[2];
  w10 = w03[3];
  /* #9: @11 = (@6*@10) */
  w11  = (w06*w10);
  /* #10: @12 = @1[1] */
  for (rr=(&w12), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #11: @13 = (@12*@9) */
  w13  = (w12*w09);
  /* #12: @11 = (@11+@13) */
  w11 += w13;
  /* #13: @13 = @1[0] */
  for (rr=(&w13), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #14: @14 = (@13*@8) */
  w14  = (w13*w08);
  /* #15: @11 = (@11+@14) */
  w11 += w14;
  /* #16: @3 = @5; (@3[0] += @11) */
  casadi_copy(w05, 4, w03);
  for (rr=w03+0, cs=(&w11); rr!=w03+1; rr+=1) *rr += *cs++;
  /* #17: @11 = (@13*@9) */
  w11  = (w13*w09);
  /* #18: @14 = (@12*@8) */
  w14  = (w12*w08);
  /* #19: @11 = (@11-@14) */
  w11 -= w14;
  /* #20: @14 = (@6*@7) */
  w14  = (w06*w07);
  /* #21: @11 = (@11-@14) */
  w11 -= w14;
  /* #22: (@3[3] += @11) */
  for (rr=w03+3, cs=(&w11); rr!=w03+4; rr+=1) *rr += *cs++;
  /* #23: @11 = (@6*@8) */
  w11  = (w06*w08);
  /* #24: @14 = (@13*@10) */
  w14  = (w13*w10);
  /* #25: @11 = (@11-@14) */
  w11 -= w14;
  /* #26: @14 = (@12*@7) */
  w14  = (w12*w07);
  /* #27: @11 = (@11-@14) */
  w11 -= w14;
  /* #28: (@3[2] += @11) */
  for (rr=w03+2, cs=(&w11); rr!=w03+3; rr+=1) *rr += *cs++;
  /* #29: @12 = (@12*@10) */
  w12 *= w10;
  /* #30: @6 = (@6*@9) */
  w06 *= w09;
  /* #31: @12 = (@12-@6) */
  w12 -= w06;
  /* #32: @13 = (@13*@7) */
  w13 *= w07;
  /* #33: @12 = (@12-@13) */
  w12 -= w13;
  /* #34: (@3[1] += @12) */
  for (rr=w03+1, cs=(&w12); rr!=w03+2; rr+=1) *rr += *cs++;
  /* #35: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #36: @16 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w16);
  /* #37: @12 = ||@16||_F */
  w12 = casadi_norm_2(4, w16);
  /* #38: @17 = (@16/@12) */
  for (i=0, rr=w17, cr=w16; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #39: @13 = @17[3] */
  for (rr=(&w13), cs=w17+3; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #40: @6 = (-@13) */
  w06 = (- w13 );
  /* #41: @18 = @15; (@18[3] = @6) */
  casadi_copy(w15, 9, w18);
  for (rr=w18+3, cs=(&w06); rr!=w18+4; rr+=1) *rr = *cs++;
  /* #42: @6 = @17[2] */
  for (rr=(&w06), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #43: (@18[6] = @6) */
  for (rr=w18+6, cs=(&w06); rr!=w18+7; rr+=1) *rr = *cs++;
  /* #44: (@18[1] = @13) */
  for (rr=w18+1, cs=(&w13); rr!=w18+2; rr+=1) *rr = *cs++;
  /* #45: @13 = @17[1] */
  for (rr=(&w13), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #46: @11 = (-@13) */
  w11 = (- w13 );
  /* #47: (@18[7] = @11) */
  for (rr=w18+7, cs=(&w11); rr!=w18+8; rr+=1) *rr = *cs++;
  /* #48: @6 = (-@6) */
  w06 = (- w06 );
  /* #49: (@18[2] = @6) */
  for (rr=w18+2, cs=(&w06); rr!=w18+3; rr+=1) *rr = *cs++;
  /* #50: (@18[5] = @13) */
  for (rr=w18+5, cs=(&w13); rr!=w18+6; rr+=1) *rr = *cs++;
  /* #51: @13 = 0.952381 */
  w13 = 9.5238095238095233e-01;
  /* #52: @2 = (@13*@2) */
  for (i=0, rr=w02, cs=wr02; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #53: @13 = 0 */
  w13 = 0.;
  /* #54: @6 = input[2][0] */
  w06 = arg[2] ? arg[2][0] : 0;
  /* #55: @1 = vertcat(@13, @13, @6) */
  rr=w01;
  *rr++ = w13;
  *rr++ = w13;
  *rr++ = w06;
  /* #56: @1 = @1' */
  /* #57: @19 = mac(@2,@1,@15) */
  casadi_copy(w15, 9, w19);
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w01+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #58: @6 = dot(@18, @19) */
  w06 = casadi_dot(9, w18, w19);
  /* #59: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #60: (@5[0] += @6) */
  for (rr=w05+0, cs=(&w06); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #61: @6 = @17[0] */
  for (rr=(&w06), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #62: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #63: @20 = (@6*@19) */
  for (i=0, rr=w20, cs=w19; i<9; ++i) (*rr++)  = (w06*(*cs++));
  /* #64: @21 = (2.*@18) */
  for (i=0, rr=w21, cs=w18; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #65: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #66: @23 = mac(@22,@19,@15) */
  casadi_copy(w15, 9, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w19+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #67: @20 = (@20+@23) */
  for (i=0, rr=w20, cs=w23; i<9; ++i) (*rr++) += (*cs++);
  /* #68: @23 = @18' */
  for (i=0, rr=w23, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #69: @22 = mac(@19,@23,@15) */
  casadi_copy(w15, 9, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w19+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #70: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #71: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<9; ++i) (*rr++) += (*cs++);
  /* #72: @11 = @20[5] */
  for (rr=(&w11), cs=w20+5; cs!=w20+6; cs+=1) *rr++ = *cs;
  /* #73: (@20[5] = @13) */
  for (rr=w20+5, cs=(&w13); rr!=w20+6; rr+=1) *rr = *cs++;
  /* #74: @22 = @20; (@22[2] = @13) */
  casadi_copy(w20, 9, w22);
  for (rr=w22+2, cs=(&w13); rr!=w22+3; rr+=1) *rr = *cs++;
  /* #75: @14 = @22[7] */
  for (rr=(&w14), cs=w22+7; cs!=w22+8; cs+=1) *rr++ = *cs;
  /* #76: @11 = (@11-@14) */
  w11 -= w14;
  /* #77: (@5[1] += @11) */
  for (rr=w05+1, cs=(&w11); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #78: (@22[7] = @13) */
  for (rr=w22+7, cs=(&w13); rr!=w22+8; rr+=1) *rr = *cs++;
  /* #79: @19 = @22; (@19[1] = @13) */
  casadi_copy(w22, 9, w19);
  for (rr=w19+1, cs=(&w13); rr!=w19+2; rr+=1) *rr = *cs++;
  /* #80: @11 = @19[6] */
  for (rr=(&w11), cs=w19+6; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #81: @14 = @20[2] */
  for (rr=(&w14), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #82: @11 = (@11-@14) */
  w11 -= w14;
  /* #83: (@5[2] += @11) */
  for (rr=w05+2, cs=(&w11); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #84: @11 = @22[1] */
  for (rr=(&w11), cs=w22+1; cs!=w22+2; cs+=1) *rr++ = *cs;
  /* #85: (@19[6] = @13) */
  for (rr=w19+6, cs=(&w13); rr!=w19+7; rr+=1) *rr = *cs++;
  /* #86: @13 = @19[3] */
  for (rr=(&w13), cs=w19+3; cs!=w19+4; cs+=1) *rr++ = *cs;
  /* #87: @11 = (@11-@13) */
  w11 -= w13;
  /* #88: (@5[3] += @11) */
  for (rr=w05+3, cs=(&w11); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #89: @24 = (@5/@12) */
  for (i=0, rr=w24, cr=w05; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #90: @3 = (@3+@24) */
  for (i=0, rr=w03, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #91: @17 = (@17/@12) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) /= w12;
  /* #92: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<4; ++i) *rr++ = (- *cs++ );
  /* #93: @11 = dot(@17, @5) */
  w11 = casadi_dot(4, w17, w05);
  /* #94: @11 = (@11/@12) */
  w11 /= w12;
  /* #95: @17 = (@11*@16) */
  for (i=0, rr=w17, cs=w16; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #96: @3 = (@3+@17) */
  for (i=0, rr=w03, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #97: output[0][1] = @3 */
  if (res[0]) casadi_copy(w03, 4, res[0]+3);
  /* #98: @11 = 33.3333 */
  w11 = 3.3333333333333336e+01;
  /* #99: @4 = (@11*@4) */
  for (i=0, rr=w04, cs=wr04; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #100: @1 = (-@4) */
  for (i=0, rr=w01, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #101: @11 = @16[0] */
  for (rr=(&w11), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #102: @12 = (@11*@10) */
  w12  = (w11*w10);
  /* #103: @13 = @16[1] */
  for (rr=(&w13), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #104: @14 = (@13*@9) */
  w14  = (w13*w09);
  /* #105: @12 = (@12-@14) */
  w12 -= w14;
  /* #106: @14 = @16[2] */
  for (rr=(&w14), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #107: @25 = (@14*@8) */
  w25  = (w14*w08);
  /* #108: @12 = (@12+@25) */
  w12 += w25;
  /* #109: @25 = @16[3] */
  for (rr=(&w25), cs=w16+3; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #110: @26 = (@25*@7) */
  w26  = (w25*w07);
  /* #111: @12 = (@12-@26) */
  w12 -= w26;
  /* #112: (@1[2] += @12) */
  for (rr=w01+2, cs=(&w12); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #113: @12 = (@13*@10) */
  w12  = (w13*w10);
  /* #114: @26 = (@11*@9) */
  w26  = (w11*w09);
  /* #115: @12 = (@12+@26) */
  w12 += w26;
  /* #116: @26 = (@25*@8) */
  w26  = (w25*w08);
  /* #117: @12 = (@12-@26) */
  w12 -= w26;
  /* #118: @26 = (@14*@7) */
  w26  = (w14*w07);
  /* #119: @12 = (@12-@26) */
  w12 -= w26;
  /* #120: (@1[1] += @12) */
  for (rr=w01+1, cs=(&w12); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #121: @25 = (@25*@9) */
  w25 *= w09;
  /* #122: @14 = (@14*@10) */
  w14 *= w10;
  /* #123: @25 = (@25-@14) */
  w25 -= w14;
  /* #124: @11 = (@11*@8) */
  w11 *= w08;
  /* #125: @25 = (@25+@11) */
  w25 += w11;
  /* #126: @13 = (@13*@7) */
  w13 *= w07;
  /* #127: @25 = (@25-@13) */
  w25 -= w13;
  /* #128: (@1[0] += @25) */
  for (rr=w01+0, cs=(&w25); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #129: output[0][2] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+7);
  /* #130: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #131: @19 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr19 = casadi_c0;
  /* #132: @15 = mac(@21,@18,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #133: @19 = (@19+@15) */
  for (i=0, rr=w19, cr=wr19, cs=w15; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #134: @18 = (@6*@18) */
  for (i=0, rr=w18, cs=w18; i<9; ++i) (*rr++)  = (w06*(*cs++));
  /* #135: @19 = (@19+@18) */
  for (i=0, rr=w19, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #136: @18 = @19' */
  for (i=0, rr=w18, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #137: @1 = mac(@18,@2,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w18+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #138: {NULL, NULL, @6} = vertsplit(@1) */
  w06 = w01[2];
  /* #139: output[0][3] = @6 */
  if (res[0]) res[0][10] = w06;
  /* #140: output[0][4] = @4 */
  if (res[0]) casadi_copy(w04, 3, res[0]+11);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_nmpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_nmpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_nmpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_nmpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_nmpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 119;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_nmpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 119*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
